---
abstract: 'Use index() instead of regex for literal substring matching'
author:
  - 'Dean Hamstead <dean@fragfest.com.au>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::More: '0'
  Test::Perl::Critic: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150013'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-Policy-Performance-ProhibitRegexForSimpleSubstring
no_index:
  directory:
    - t
provides:
  Perl::Critic::Policy::Performance::ProhibitRegexForSimpleSubstring:
    file: lib/Perl/Critic/Policy/Performance/ProhibitRegexForSimpleSubstring.pm
    version: '0.01'
requires:
  PPIx::Regexp: '0.091'
  Perl::Critic: '0'
  parent: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/djzort/perl-critic-policy-probhibitregexforsimplesubstrings/issues
  homepage: https://github.com/djzort/perl-critic-policy-probhibitregexforsimplesubstrings
  repository: https://github.com/djzort/perl-critic-policy-probhibitregexforsimplesubstrings.git
version: '0.01'
x_generated_by_perl: v5.40.3
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: MIT
