name             = ExtUtils-CFeatureTest
abstract         = Convenient build-time tool for testing C language environment
author           = Michael Conrad <mike@nrdvana.net>
license          = Perl_5
copyright_holder = Michael Conrad

[MetaResources]
bugtracker.web   = https://github.com/nrdvana/perl-ExtUtils-CFeatureTest/issues
repository.web   = https://github.com/nrdvana/perl-ExtUtils-CFeatureTest
repository.url   = https://github.com/nrdvana/perl-ExtUtils-CFeatureTest.git
repository.type  = git

[@Git]
[Git::Contributors]
[Git::GatherDir]
include_untracked = 0
exclude_filename = META.json   ; The copies in version control are only for
exclude_filename = Makefile.PL ; letting GitHub Actions run without installing
                               ; dzil on every execution.

[Git::NextVersion]
[OurPkgVersion]
overwrite = 1

[MakeMaker]
[Manifest]
[License]
[ExtraTests]
[Test::Pod::Coverage::Configurable]
[PodSyntaxTests]

; authordep Dist::Zilla::Plugin::Test::Pod::Coverage::Configurable
; authordep Pod::Coverage::TrustPod
; authordep Test::Pod
[AutoPrereqs]
[Prereqs / ConfigureRequires]
ExtUtils::CBuilder = 0.2800
[UploadToCPAN]
[MetaYAML]
[MetaJSON]
