[DEFAULT]
# DEFAULT STARTING VARIABLES 
# BECAREFUL under linux ! values ​​should not be followed by blank
# BECAREFUL under linux ! lines must end with windows CR LF
# => SEE END OF CONFIG FILE FOR SPECIFIC CONFIGURATIONS DEPENDING ON HOSTNAME
# Release : 20211027.1223
iniEdtk		=local
EDTK_CORP		=oEdtk
EDTK_DICO		=$EDTK_DIR_CONFIG/edtk_dico.ini
EDTK_DICO_POST	=$EDTK_DIR_CONFIG/postal_dico.ini
EDTK_SNIP_ADDR	=$EDTK_DIR_CONFIG/snip_address.ini
EDTK_SNIP_RATE	=0
EDTK_LANG		=EN
EDTK_LOG_LVL            = 4


[ENVDESC]
# DEFAULT ENVIRONNEMENT DESCRIPTION
# EDTK_PRGPATH is defined by oEdtk to show current path 
EDTK_DIR_BASE		=$EDTK_PRGPATH
EDTK_TYPE_ENV		=Dev
EDTK_DIR_APPTMP 	=/tmp
EDTK_DIR_DATA_IN	=$EDTK_DIR_APPTMP
EDTK_DIR_APP 		=$EDTK_DIR_BASE
EDTK_DIR_CONFIG		=$EDTK_DIR_APP/config
EDTK_DIR_DOCSCRIPT 	=$EDTK_DIR_APP
EDTK_DIR_LIB 		=$EDTK_DIR_APP
EDTK_DIR_LOG 		=$EDTK_DIR_APPTMP
EDTK_DIR_DB 		=$EDTK_DIR_APPTMP
#EDTK_DIR_SCRIPT	=$EDTK_DIR_APP/$EDTK_PRGNAME
EDTK_DIR_SCRIPT		=$EDTK_DIR_APP
EDTK_DIR_EDOCMNGR	=$EDTK_DIR_APPTMP
EDTK_DIR_DOCLIB		=$EDTK_DIR_CONFIG
EDTK_DIR_OUTMNGR	=$EDTK_DIR_APPTMP
EDTK_DIR_TMPLATE	=$EDTK_DIR_APP
EDTK_DOCLIB_LOCK	=$EDTK_DIR_APPTMP/doclib.lock
EDTK_FDATAIN		=$EDTK_DIR_APPTMP
EDTK_FDATAOUT		=$EDTK_DIR_APPTMP
EDTK_FDATWORK		=$EDTK_DIR_APPTMP
EDTK_OUTMNGR_MERGE	=no
EDTK_PRGNAME		=
EDTK_VCS_LOCATION	=
EDTK_WATERMARKTEXT	=Test Edition

EDTK_BIN_PERL		=/usr/bin/perl
EDTK_EXT_COMP_OMGR 	=omgr
EDTK_EXT_COMPO	 	=$EDTK_EXT_LATEX
EDTK_EXT_COMSET 	=sty
EDTK_EXT_DATA		=DAT
EDTK_EXT_DEFAULT	=$EDTK_EXT_PDF
EDTK_EXT_EXCEL		=xls
EDTK_EXT_LATEX		=tex
EDTK_EXT_PCL		=pcl
EDTK_EXT_PDF		=pdf
EDTK_EXT_PERL		=pl
EDTK_EXT_WORK		=txt

EDTK_WAITRUN		=8
EDTK_XLS_MAX_ROW	=30000

; create table edtk_tracking (ed_tstamp varchar(14) not null, ed_sngl_id varchar(25) not null, ed_seq integer      not null, ed_app varchar(20) not null, ed_user varchar(10) not null, ed_corp varchar(8)  not null, ed_account varchar(8), ed_mod_ed char, ed_job_evt char, ed_obj_typ varchar(3), ed_obj_count integer, ed_child_typ varchar(3), ed_child_id varchar(32), ed_parent_id varchar(32), ed_host varchar(32), ed_source varchar(128), ed_message varchar(256),  ed_k0_name varchar(8),ed_k0_val varchar(128), ed_k1_name varchar(8),ed_k1_val varchar(128), ed_k2_name varchar(8),ed_k2_val varchar(128), ed_k3_name varchar(8),ed_k3_val varchar(128), ed_k4_name varchar(8),ed_k4_val varchar(128), ed_k5_name varchar(8),ed_k5_val varchar(128), ed_k6_name varchar(8),ed_k6_val varchar(128), ed_k7_name varchar(8),ed_k7_val varchar(128), ed_k8_name varchar(8),ed_k8_val varchar(128), ed_k9_name varchar(8),ed_k9_val varchar(128), ed_k10_name varchar(8),ed_k10_val varchar(128) );

[EDTK_DB]
# ENVIRONNMENT VARIABLES FOR DATABASE
EDTK_DB_FetchHashKeyName=NAME_lc
EDTK_DBI_TRACKING		=edtk_tracking
EDTK_DBI_ACQUIT			=edtk_acq
EDTK_DBI_OUTMNGR		=edtk_metadata
EDTK_DBI_OUTMNGR_STATS	=edtk_metadata_stats
EDTK_DBI_DISTRIB		=edtk_distrib
EDTK_DBI_DISTRIB_STATS	=edtk_distrib_stats
EDTK_MAX_USER_KEY		=10
EDTK_TRACKING_KEYS		=o_design,o_param,o_status,chanelid,cod_cais,cod_ctrt,ls_child
EDTK_TRACK_MODE 		=SQLite
EDTK_DBI_PARAM			=DBI:SQLite:dbname=$EDTK_DIR_DB/oedtk_param.tmp
EDTK_DBI_DSN			=DBI:SQLite:dbname=$EDTK_DIR_DB/oedtk_db.tmp
EDTK_DBI_DSN_USER		=oedtk
EDTK_DBI_DSN_PASS		=dev-oedtk-test
EDTK_DBI_DSN_BAK		=DBI:SQLite:dbname=$EDTK_DIR_DB/oedtk_db.tmp
EDTK_DBI_DSN_BAK_USER	=DBI_DSN_BAK_USER
EDTK_DBI_DSN_BAK_PASS	=DBI_DSN_BAK_PASS
EDTK_TRACK_SIG			=warn
EDTK_DB_MAX_DAYS_KEPT		=2
EDTK_DB_MAX_DAYS_KEPT_STATS =100
EDTK_DB_MAX_DAYS_TRACKED	=400
EDTK_DB_MAX_DAYS_AGREGED	=600
EDTK_DB_CHECK_AUTO			=NO
EDTK_DB_CHECK_MONTH_DAY 	=15


[EDTK_STATS]
EDTK_DBI_STATS		=$EDTK_DBI_DSN
EDTK_DSN_STATS		=$EDTK_DBI_DSN
EDTK_DBI_STATS_USER	=$EDTK_DBI_DSN_USER
EDTK_DSN_STATS_USER	=$EDTK_DBI_DSN_USER
EDTK_DBI_STATS_PASS	=$EDTK_DBI_DSN_PASS
EDTK_DSN_STATS_PASS	=$EDTK_DBI_DSN_PASS
EDTK_STATS_TRACKING	=$EDTK_DBI_TRACKING
EDTK_STATS_OUTMNGR	=$EDTK_DBI_OUTMNGR_STATS
EDTK_STATS_DISTRIB	=$EDTK_DBI_DISTRIB_STATS
EDTK_STATS_ACQUIT	=$EDTK_DBI_ACQUIT
EDTK_CSV_HEADER_METADATA =ed_refiddoc,ed_idldoc,ed_idseqpg,ed_seqdoc,ed_idjob,ed_cpdest,ed_villdest,ed_iddest,ed_nomdest,ed_idemet,ed_dtedtion,ed_typprod,ed_portadr,ed_adrln1,ed_cleged1,ed_adrln2,ed_cleged2,ed_adrln3,ed_cleged3,ed_adrln4,ed_cleged4,ed_adrln5,ed_corp,ed_doclib,ed_refimp,ed_adrln6,ed_source,ed_owner,ed_host,ed_ididx,ed_catdoc,ed_codrupt,ed_idlot,ed_seqlot,ed_dtlot,ed_idfiliere,ed_seqpgdoc,ed_nbpgdoc,ed_poidsunit,ed_nbenc,ed_encpds,ed_bac_insert,ed_typed,ed_modedi,ed_formatp,ed_pgorien,ed_formflux,ed_idpli,ed_nbdocpli,ed_numpgpli,ed_nbpgpli,ed_nbfpli,ed_listerefenc,ed_pdspli,ed_typobj,ed_status,ed_dtposte,ed_country,ed_idcontract,ed_idproduct,ed_workflow,ed_chanel_out
EDTK_CSV_HEADER_DISTRIB  =ed_idldoc,ed_idseqpg,ed_seqdoc,ed_idjob,ed_idlot,ed_seqlot,ed_dtlot,ed_idfiliere,ed_seqpgdoc,ed_nbpgdoc,ed_workflow,ed_chanel_out
; pour mysql uniquement :
EDTK_STATS_SQL00	=show table status
EDTK_STATS_SQL01	=select table_name as `table`, round((data_length + index_length) / 1024 / 1024) as `size (mb)` from information_schema.tables order by (data_length + index_length) desc
EDTK_STATS_SQL02	=select * from edtk_admin order by ed_action_date desc
EDTK_STATS_SQL03	=select avg(ed_action_duration), ed_oedtk_release from edtk_admin group by ed_oedtk_release order by ed_oedtk_release desc
EDTK_STATS_SQL04	=select distinct table_name, index_name from information_schema.statistics
; standard
EDTK_STATS_SQL10	=select * from edtk_tracking where (ed_message like '%deadlock%' or ed_message like '%fail%') order by ed_tstamp desc;
EDTK_STATS_SQL11	=select * from edtk_tracking where (ed_message like 'compo_%' or ed_message like 'distri_%') order by ed_tstamp desc limit 500
EDTK_STATS_SQL12	=select * from edtk_tracking where ed_message like '%deadlock%' order by ed_tstamp desc limit 100
EDTK_STATS_SQL90	=$EDTK_PRGPATH/sql/SCT-PROD.sql
EDTK_STATS_SQL99	=select * from edtk_tracking where ed_tstamp > ? limit 100


[MAIL]
EDTK_MAIL_TO		=myMail@mail.org
EDTK_MAIL_TST		=myMail@mail.org
EDTK_MAIL_SENDER	=myMail@mail.org
EDTK_MAIL_SUBJ		=Editions Externalis�es du %date � %time
EDTK_MAIL_SMTP		=smtp.myOrg.org
EDTK_MAIL_REFER 	=$EDTK_DIR_CONFIG/mail.bat.txt
EDTK_MAIL_OMGR		=$EDTK_DIR_CONFIG/mail.txt.test
EDTK_MAIL_LIST_1	=


[COMPO]
# ENVIRONNMENT VARIABLES FOR LaTeX COMPO
EDTK_BIN_COMPO		=$EDTK_DIR_BASE/
EDTK_COMPO          =pdflatex -halt-on-error
EDTK_COMPO_CMD_PDF	=pdflatex -halt-on-error
EDTK_COMPO_CMD_DVI	=latex -halt-on-error
EDTK_COMPO_CMD_DVIPDF=dvipdfm
EDTK_COMPO_LIB		=$EDTK_DIR_CONFIG/edtkdoc.cls
; Uncomment to override default aysnchronous setting :
;EDTK_COMPO_ASYNC	=yes


[EDOCMNGR]
EDMS_INDEX_COLS		=ed_refiddoc,ed_corp,ed_source,edms_idldoc_seqpg,ed_dtedtion,ed_cleged1,ed_iddest,ed_nomdest,ed_villdest,ed_idemet,ed_cleged2,ed_cleged3,ed_cleged4,ed_owner,edms_filename
EDMS_DATE_FORMAT	=%Y/%m/%d
;EDMS_IDX_FORMAT	=SCOPMASTER
EDMS_IDX_FORMAT		=DOCUBASE
EDMS_FTP_HOST		=edmsftpsrv
EDMS_FTP_PORT		=22
EDMS_FTP_USER		=ftp_tst_docubase
EDMS_FTP_PASS		=docubase
EDMS_FTP_DIR_IDX 	=webservice/in
EDMS_FTP_DIR_DOCS	=webservice/work
EDTK_EDOCS_LINK		=
EDMS_HTML_HOST		=docubase
EDMS_URL_LOOKUP		=http://$EDMS_HTML_HOST/rheaweb/controler?cmd=list&action=newquery&baseid=182&query=WILD(3,%s)&view=%d&j_username=%surl&j_password=%scrm
EDMS_BIN_GS			=/usr/bin/gs


# END FOR STANDARD VARIABLES
# REDEFINED VARIABLES BY HOSTNAMES SHOULD FOLLOW
# (HOSTNAMES SHOULD ALWAYS BE UPPERCASE)

[UDEV-6DOC]
; HOSTNAME EXAMPLE
# VM sur MILARE
EDTK_DBI_DSN		=DBI:mysql:database=nbtrack;host=192.168.0.21;port=3306;mysql_local_infile=true
# VM sur 7480-GT
# ;mysql_server_prepare=1 pose des problèmes
# EDTK_DBI_DSN		=DBI:mysql:database=nbtrack;host=192.168.43.1;port=3306;mysql_local_infile=true dev-oedtk-mysql
EDTK_DBI_DSN_USER	=udev-6doc
EDTK_TYPE_ENV		=Dev

[EADGBE]
EDTK_DIR_APPTMP 	=/tmp
EDTK_TYPE_ENV		=Dev
EDTK_DBI_DSN_USER	=greg
#EDTK_DBI_DSN		=dbi:Pg:dbname=oedtk;host=localhost;port=5432

[THINKBOOK-G2]
EDTK_DIR_APPTMP 	=/tmp
EDTK_TYPE_ENV		=Dev
EDTK_DBI_DSN_USER	=grc
EDTK_DBI_DSN		=dbi:Pg:dbname=oedtk;host=localhost;port=5432
#EDTK_DBI_DSN		=DBI:mysql:database=oedtk;host=192.168.1.188;port=3306;mysql_local_infile=true
#EDTK_DBI_DSN		=DBI:mysql:database=oedtk;host=192.168.1.188;port=3306
