:r database
go
:r dumpdb
go
drop procedure sp__get_tmp_error
go
drop procedure sp__grep
go
drop procedure sp__auditdb                    
go
drop procedure sp__auditsecurity              
go
drop procedure sp__badindex
go
drop procedure sp__bcp                        
go
drop procedure sp__block                      
go
drop procedure sp__checkkey                       
go
drop procedure sp__collist
go
drop procedure sp__date                       
go
drop procedure sp__datediff                   
go
drop procedure sp__dbspace                    
go
drop procedure sp__depends
go
drop procedure sp__dumpdevice                 
go
drop procedure sp__flowchart
go
drop procedure sp__diskdevice
go
drop procedure sp__help                       
go
drop procedure sp__helpcolumn                 
go
drop procedure sp__helpdb                     
go
drop procedure sp__helpdbdev                  
go
drop procedure sp__helpdefault                
go
drop procedure sp__helpdevice                 
go
drop procedure sp__helpgroup                  
go
drop procedure sp__helpindex                  
go
drop procedure sp__helplogin                  
go
drop procedure sp__helpmirror                 
go
drop procedure sp__helpobject                 
go
drop procedure sp__helpproc                   
go
drop procedure sp__helprule                   
go
drop procedure sp__helpsegment                
go
drop procedure sp__helptable                  
go
drop procedure sp__helptext
go
drop procedure sp__helptrigger                
go
drop procedure sp__helpuser                   
go
drop procedure sp__helpview                   
go
drop procedure sp__iostat
go
drop procedure sp__isactive
go
drop procedure sp__indexspace                 
go
drop procedure sp__lock                       
go
drop procedure sp__lockt
go
drop procedure sp__ls
go
drop procedure sp__noindex                    
go
drop procedure sp__quickstats                 
go
drop procedure sp__read_write
go
drop procedure sp__revalias                   
go
drop procedure sp__revdb                      
go
drop procedure sp__revdevice                  
go
drop procedure sp__revgroup                   
go
drop procedure sp__revtable                   
go
drop procedure sp__revsegment
go
drop procedure sp__revindex                   
go
drop procedure sp__revlogin                   
go
drop procedure sp__revmirror                  
go
drop procedure sp__revuser                    
go
drop procedure sp__segment                    
go
drop procedure sp__server                     
go
drop procedure sp__syntax
go
drop procedure sp__trigger
go
drop procedure sp__vdevno                     
go
drop procedure sp__who                        
go
drop procedure sp__whoactive
go
drop procedure sp__whodo
go
go
drop procedure sp__colconflict                
go
drop procedure sp__colnull                    
go
drop procedure sp__find_missing_index         
go
drop procedure sp__helprotect                 
go
drop procedure sp__id                         
go
drop procedure sp__proclib_version            
go
drop procedure sp__stat2                      
go
drop procedure sp__stat                       
go
drop procedure sp__add_record                 
go
drop procedure sp__show_record
go
drop procedure sp__monitor
go
drop procedure sp__auditoption
go
drop table record
go
drop table record_backup
go
