--- #YAML:1.0
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
name: mb-JSON
version: 0.07
abstract: JSON encode/decode for multibyte (UTF-8) strings
author:
  - ina <ina.cpan@gmail.com>
license: perl
generated_by: pmake.bat version 0.41
requires:
  Carp: 0
  ExtUtils::MakeMaker: 5.4302
  perl: 5.00503
minimum_perl_version: 5.00503
provides:
  mb::JSON:
    file: lib/mb/JSON.pm
    version: 0.07
  mb::JSON::Boolean:
    file: lib/mb/JSON.pm
    version: 0.07
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: https://github.com/ina-cpan/mb-JSON/issues
  repository: https://github.com/ina-cpan/mb-JSON
