---
distro: Perl-Critic-Policy-ValuesAndExpressions-ProhibitDefinedBeforeLength
version: 0.002
author_path: T/TE/TEODESIAN/Perl-Critic-Policy-ValuesAndExpressions-ProhibitDefinedBeforeLength-0.002.tar.gz
