---
distro: Perl-Critic-Policy-ValuesAndExpressions-ProhibitLiteralArithmetic
version: 0.001
author_path: T/TE/TEODESIAN/Perl-Critic-Policy-ValuesAndExpressions-ProhibitLiteralArithmetic-0.001.tar.gz
