openapi: 3.1.0
info:
  title: Chat API
  description: An API to programmatically create your own Chat Applications.
  version: 0.0.0
tags:
  - name: Tokens
    description: Manage Chat tokens.
    externalDocs:
      url: https://signalwire.com/docs/apis
      description: Developer documentation on SignalWire REST APIs
paths:
  /tokens:
    post:
      operationId: create_chat_token
      summary: Generate a new Chat Token
      description: |-
        Generate a Chat Token to be used to authenticate clients to the Chat Service.

        #### Permissions

        The API token used to authenticate must have the following scope(s) enabled to make a successful request: _Chat_.

        [Learn more about API scopes](/docs/platform/your-signalwire-api-space).
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatToken'
        '400':
          description: The request is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode400'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode401'
        '422':
          description: The request contains invalid parameters. See errors for details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatToken422Error'
      tags:
        - Tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewChatToken'
security:
  - SignalWireBasicAuth: []
components:
  schemas:
    ChatChannel:
      type: object
      unevaluatedProperties:
        anyOf:
          - $ref: '#/components/schemas/ChatPermissionWithRead'
          - $ref: '#/components/schemas/ChatPermissionWithWrite'
      description: |-
        User-defined channel names. Each channel is an object with `read` and/or `write` properties.
        Max of 500 channels. Either `read`, `write`, or both are required inside each channel and default to `false`.
        Each channel name can be up to 250 characters. Channel names cannot start with the reserved prefix `sw_`.
        Must be valid JSON.
      examples:
        - channel1:
            read: true
            write: true
          channel2:
            read: true
            write: false
    ChatPermissionWithRead:
      type: object
      required:
        - read
      properties:
        read:
          type: boolean
          description: Gives the token read access to the channel.
          examples:
            - true
        write:
          type: boolean
          description: Gives the token write access to the channel.
          examples:
            - false
      title: Read Permission
    ChatPermissionWithWrite:
      type: object
      required:
        - write
      properties:
        read:
          type: boolean
          description: Gives the token read access to the channel.
          examples:
            - true
        write:
          type: boolean
          description: Gives the token write access to the channel.
          examples:
            - false
      title: Write Permission
    ChatState:
      type: object
      unevaluatedProperties: {}
      description: An arbitrary JSON object available to store stateful application information in. Must be valid JSON and have a maximum size of 2,000 characters.
      examples:
        - key: value
          key2: value2
    ChatToken:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: The generated Chat Token.
          examples:
            - eyJ0eXAiOiJWUlQiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2MjIxMjAxMjMsI...wMCwicnNlIjo5MDB9-BqG-DqC5LhpsdMWEFjhVkTBpQ
    ChatToken422Error:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Types.StatusCodes.RestApiErrorItem'
          description: List of validation errors.
      description: The request contains invalid parameters. See errors for details.
      examples:
        - statusCode: 422
          errors:
            - type: validation_error
              code: missing_required_parameter
              message: A required parameter is missing from the request. Please refer to the technical reference for a complete list of parameters.
              attribute: ttl
              url: https://signalwire.com/docs/apis/error-codes
    NewChatToken:
      type: object
      required:
        - ttl
        - channels
      properties:
        ttl:
          type: integer
          minimum: 1
          maximum: 43200
          description: The maximum time, in minutes, that the access token will be valid for. Between 1 and 43,200 (30 days).
          examples:
            - 60
        channels:
          allOf:
            - $ref: '#/components/schemas/ChatChannel'
          minProperties: 1
          maxProperties: 500
          description: User-defined channel names with read/write permissions. Max of 500 channels. Channel names cannot start with the reserved prefix `sw_` and can be up to 250 characters.
          examples:
            - channel1:
                read: true
                write: true
              channel2:
                read: true
                write: false
        member_id:
          type: string
          maxLength: 250
          description: The unique identifier of the member. Up to 250 characters. If not specified, a random UUID will be generated.
          examples:
            - 3fa85f64-5717-4562-b3fc-2c963f66afa6
        state:
          allOf:
            - $ref: '#/components/schemas/ChatState'
          description: An arbitrary JSON object available to store stateful application information in. Must be valid JSON and have a maximum size of 2,000 characters.
          examples:
            - key: value
              key2: value2
          default: {}
    Types.StatusCodes.RestApiErrorItem:
      type: object
      required:
        - type
        - code
        - message
        - url
      properties:
        type:
          type: string
          description: The category of error.
          examples:
            - validation_error
        code:
          type: string
          description: A specific error code.
          examples:
            - invalid_parameter
        message:
          type: string
          description: A description of what caused the error.
          examples:
            - Name must be present
        attribute:
          anyOf:
            - type: string
            - type: 'null'
          description: The request parameter that caused the error, if applicable.
          examples:
            - name
        url:
          type: string
          description: A link to documentation about this error.
          examples:
            - https://signalwire.com/docs/apis/error-codes
      description: Details about a specific error.
    Types.StatusCodes.StatusCode400:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          enum:
            - Bad Request
      description: The request is invalid.
    Types.StatusCodes.StatusCode401:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          enum:
            - Unauthorized
      description: Access is unauthorized.
  securitySchemes:
    SignalWireBasicAuth:
      type: http
      scheme: Basic
      description: |-
        SignalWire Basic Authentication using Project ID and API Token.

        The client sends HTTP requests with the Authorization header containing
        the word Basic followed by a space and a base64-encoded string of project_id:token.
        The project ID will be used as the username and the API token as the password.

        Example:
        ```
        Authorization: Basic base64(project_id:token)
        ```
      x-fern-basic:
        username:
          name: project_id
          env: SIGNALWIRE_PROJECT_ID
        password:
          name: api_token
          env: SIGNALWIRE_API_TOKEN
servers:
  - url: https://{space_name}.signalwire.com/api/chat
    description: Endpoint
    variables:
      space_name:
        default: '{Your_Space_Name}'
