/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "../asn1src/MAP-MS-DataTypes.asn"
 * 	`asn1c -gen-PER -fskeletons-copy -fnative-types`
 */

#include "CSG-SubscriptionData.h"

static asn_TYPE_member_t asn_MBR_CSG_SubscriptionData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CSG_SubscriptionData, csg_Id),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_CSG_Id,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csg-Id"
		},
	{ ATF_POINTER, 4, offsetof(struct CSG_SubscriptionData, expirationDate),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"expirationDate"
		},
	{ ATF_POINTER, 3, offsetof(struct CSG_SubscriptionData, extensionContainer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 2, offsetof(struct CSG_SubscriptionData, lipa_AllowedAPNList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LIPA_AllowedAPNList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"lipa-AllowedAPNList"
		},
	{ ATF_POINTER, 1, offsetof(struct CSG_SubscriptionData, plmn_Id),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMN_Id,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"plmn-Id"
		},
};
static int asn_MAP_CSG_SubscriptionData_oms_1[] = { 1, 2, 3, 4 };
static ber_tlv_tag_t asn_DEF_CSG_SubscriptionData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CSG_SubscriptionData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 0, 0, 0 }, /* csg-Id at 1100 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* expirationDate at 1101 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* extensionContainer at 1102 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, 0, 0 }, /* lipa-AllowedAPNList at 1104 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 4, 0, 0 } /* plmn-Id at 1105 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CSG_SubscriptionData_specs_1 = {
	sizeof(struct CSG_SubscriptionData),
	offsetof(struct CSG_SubscriptionData, _asn_ctx),
	asn_MAP_CSG_SubscriptionData_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_CSG_SubscriptionData_oms_1,	/* Optional members */
	2, 2,	/* Root/Additions */
	2,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CSG_SubscriptionData = {
	"CSG-SubscriptionData",
	"CSG-SubscriptionData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CSG_SubscriptionData_tags_1,
	sizeof(asn_DEF_CSG_SubscriptionData_tags_1)
		/sizeof(asn_DEF_CSG_SubscriptionData_tags_1[0]), /* 1 */
	asn_DEF_CSG_SubscriptionData_tags_1,	/* Same as above */
	sizeof(asn_DEF_CSG_SubscriptionData_tags_1)
		/sizeof(asn_DEF_CSG_SubscriptionData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CSG_SubscriptionData_1,
	5,	/* Elements count */
	&asn_SPC_CSG_SubscriptionData_specs_1	/* Additional specs */
};

