/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "../asn1src/MAP-MS-DataTypes.asn"
 * 	`asn1c -gen-PER -fskeletons-copy -fnative-types`
 */

#include "NoteMsPresentForGprsArg.h"

static asn_TYPE_member_t asn_MBR_NoteMsPresentForGprsArg_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NoteMsPresentForGprsArg, imsi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"imsi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NoteMsPresentForGprsArg, sgsn_Address),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GSN_Address,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sgsn-Address"
		},
	{ ATF_POINTER, 2, offsetof(struct NoteMsPresentForGprsArg, ggsn_Address),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GSN_Address,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ggsn-Address"
		},
	{ ATF_POINTER, 1, offsetof(struct NoteMsPresentForGprsArg, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"extensionContainer"
		},
};
static int asn_MAP_NoteMsPresentForGprsArg_oms_1[] = { 2, 3 };
static ber_tlv_tag_t asn_DEF_NoteMsPresentForGprsArg_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_NoteMsPresentForGprsArg_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* imsi at 2388 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sgsn-Address at 2389 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ggsn-Address at 2390 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* extensionContainer at 2391 */
};
static asn_SEQUENCE_specifics_t asn_SPC_NoteMsPresentForGprsArg_specs_1 = {
	sizeof(struct NoteMsPresentForGprsArg),
	offsetof(struct NoteMsPresentForGprsArg, _asn_ctx),
	asn_MAP_NoteMsPresentForGprsArg_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_NoteMsPresentForGprsArg_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_NoteMsPresentForGprsArg = {
	"NoteMsPresentForGprsArg",
	"NoteMsPresentForGprsArg",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_NoteMsPresentForGprsArg_tags_1,
	sizeof(asn_DEF_NoteMsPresentForGprsArg_tags_1)
		/sizeof(asn_DEF_NoteMsPresentForGprsArg_tags_1[0]), /* 1 */
	asn_DEF_NoteMsPresentForGprsArg_tags_1,	/* Same as above */
	sizeof(asn_DEF_NoteMsPresentForGprsArg_tags_1)
		/sizeof(asn_DEF_NoteMsPresentForGprsArg_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_NoteMsPresentForGprsArg_1,
	4,	/* Elements count */
	&asn_SPC_NoteMsPresentForGprsArg_specs_1	/* Additional specs */
};

