/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "../asn1src/MAP-MS-DataTypes.asn"
 * 	`asn1c -gen-PER -fskeletons-copy -fnative-types`
 */

#ifndef	_SRES_H_
#define	_SRES_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SRES */
typedef OCTET_STRING_t	 SRES_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SRES;
asn_struct_free_f SRES_free;
asn_struct_print_f SRES_print;
asn_constr_check_f SRES_constraint;
ber_type_decoder_f SRES_decode_ber;
der_type_encoder_f SRES_encode_der;
xer_type_decoder_f SRES_decode_xer;
xer_type_encoder_f SRES_encode_xer;
per_type_decoder_f SRES_decode_uper;
per_type_encoder_f SRES_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SRES_H_ */
#include <asn_internal.h>
