/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-OM-DataTypes"
 * 	found in "../asn1src/MAP-OM-DataTypes.asn"
 * 	`asn1c -gen-PER -fskeletons-copy -fnative-types`
 */

#ifndef	_TraceNE_TypeList_H_
#define	_TraceNE_TypeList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TraceNE_TypeList {
	TraceNE_TypeList_msc_s	= 0,
	TraceNE_TypeList_mgw	= 1,
	TraceNE_TypeList_sgsn	= 2,
	TraceNE_TypeList_ggsn	= 3,
	TraceNE_TypeList_rnc	= 4,
	TraceNE_TypeList_bm_sc	= 5,
	TraceNE_TypeList_mme	= 6,
	TraceNE_TypeList_sgw	= 7,
	TraceNE_TypeList_pgw	= 8,
	TraceNE_TypeList_eNB	= 9
} e_TraceNE_TypeList;

/* TraceNE-TypeList */
typedef BIT_STRING_t	 TraceNE_TypeList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TraceNE_TypeList;
asn_struct_free_f TraceNE_TypeList_free;
asn_struct_print_f TraceNE_TypeList_print;
asn_constr_check_f TraceNE_TypeList_constraint;
ber_type_decoder_f TraceNE_TypeList_decode_ber;
der_type_encoder_f TraceNE_TypeList_encode_der;
xer_type_decoder_f TraceNE_TypeList_decode_xer;
xer_type_encoder_f TraceNE_TypeList_encode_xer;
per_type_decoder_f TraceNE_TypeList_decode_uper;
per_type_encoder_f TraceNE_TypeList_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TraceNE_TypeList_H_ */
#include <asn_internal.h>
