/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "../asn1src/MAP-MS-DataTypes.asn"
 * 	`asn1c -gen-PER -fskeletons-copy -fnative-types`
 */

#ifndef	_VGCSDataList_H_
#define	_VGCSDataList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VoiceGroupCallData;

/* VGCSDataList */
typedef struct VGCSDataList {
	A_SEQUENCE_OF(struct VoiceGroupCallData) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VGCSDataList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VGCSDataList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VoiceGroupCallData.h"

#endif	/* _VGCSDataList_H_ */
#include <asn_internal.h>
