---
abstract: 'a Perl module for parsing and formatting date fields in chess game databases in PGN format'
author:
  - 'Ingram Braun <carlorff1@gmail.com>'
build_requires:
  Chess::PGN::Parse: '0.20'
  Test::More: '1.001014'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DateTime-Format-PGN
requires:
  DateTime::Incomplete: '0.08'
  Params::Validate: '1.23'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=DateTime-Format-PGN
  homepage: https://ingram-braun.net/public/programming/perl/chess-databases-pgn-date-format-parser/
  repository: git://github.com/CarlOrff/DateTime-Format-PGN.git
version: '1.01'
x_generated_by_perl: v5.40.2
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
