---
abstract: 'Async Kafka client using EV'
author:
  - vividsnow
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.98'
configure_requires:
  EV::MakeMaker: '0'
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: EV-Kafka
no_index:
  directory:
    - t
    - inc
    - t
    - xt
    - src
    - eg
    - bench
requires:
  EV: '4.11'
  XSLoader: '0.02'
  perl: '5.012'
resources:
  bugtracker: https://github.com/vividsnow/perl5-ev-kafka/issues
  repository: https://github.com/vividsnow/perl5-ev-kafka.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
