INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (2, 'DIO', 'get_dio', '1', 'production,rollout,dev', 'DBI', 'hash', NULL, 'select  cd_id,cd_namespace,cd_name,cd_version,cd_sysclass,cd_type,cd_cache,cd_return,cd_stmt,cd_stmt_noarg,cd_cache_expire,cd_profile,cd_repl,cd_action,cd_audit from core_dio where cd_id = ?', '', 'never', '1', '', '', NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1027, 'DIO', 'dio_update', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_update(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', '', 'never', '1', '', '', NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1058, 'DIO', 'dio_exp_delete', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_exp_delete(?,?)', '', NULL, '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1056, 'DIO', 'dio_expkey_insert', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_expkey_insert(?,?,?)', '', NULL, '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1026, 'DIO', 'dio_insert', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_insert(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', '', 'never', '1', '', '', NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1055, 'DIO', 'get_dio_exp_keys', '1', 'production,rollout,dev', 'DBI', 'arrayofscalar', NULL, 'select ck_key from core_dio_cache_exp_key where ck_cd_id = ? and ck_exp_id = ? order by ck_key', '', NULL, '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1059, 'DIO', 'dio_exp_insert', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_exp_insert(?,?)', '', NULL, '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1022, 'DIO', 'get_namespaces', '1', 'production,rollout,dev', 'DBI', 'arrayofarray', NULL, 'select distinct cd_namespace from core_dio order by cd_namespace', '', 'never', '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1, 'DIO', 'dio_list', '1', 'production,rollout,dev', 'DBI', 'arrayofhash', NULL, 'select  cd_id,cd_namespace,cd_name,cd_version,cd_sysclass,cd_type,cd_cache,cd_profile,cd_repl,cd_action,cd_audit from core_dio order by cd_namespace, cd_name, cd_sysclass, cd_version', '', 'never', '1', '', 'select', NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1075, 'DIO', 'profile_on', '1', 'production,rollout,dev', 'DBI', 'none', NULL, 'update core_dio set cd_profile = ''1'' where cd_id = ?', '', 'never', '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1035, 'DIO', 'dio_outkey_delete', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_outkey_delete(?,?)', '', 'never', '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1029, 'DIO', 'dio_delete', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_delete(?)', '', NULL, '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1025, 'DIO', 'get_dio_exps', '1', 'production,rollout,dev', 'DBI', 'arrayofhash', NULL, 'select ce_exp_id, cd_name from core_dio, core_dio_cache_exp where ce_cd_id = ? and cd_id = ce_exp_id order by cd_name', '', NULL, '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1100, 'DIO', 'dio_audit_insert', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_audit_insert(?,?,?,?)', '', 'never', '1', '', '', ' ');
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1057, 'DIO', 'dio_expkey_delete', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_expkey_delete(?,?,?)', '', NULL, '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1032, 'DIO', 'dio_inkey_delete', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_inkey_delete(?,?)', '', NULL, '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1074, 'DIO', 'profile_off', '1', 'production,rollout,dev', 'DBI', 'none', NULL, 'update core_dio set cd_profile = null where cd_id = ?', '', 'never', '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1028, 'DIO', 'dio_duplicate', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_duplicate(?)', '', NULL, '1', NULL, NULL, NULL);
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1030, 'DIO', 'dio_inkey_insert', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_inkey_insert(?,?,?,?,?,?,?)', '', 'never', '1', '', '', ' ');
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1031, 'DIO', 'dio_inkey_update', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_inkey_update(?,?,?,?,?,?,?,?)', '', 'never', '1', '', '', ' ');
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1033, 'DIO', 'dio_outkey_insert', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_outkey_insert(?,?,?,?,?,?)', '', 'never', '1', '', '', ' ');
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1034, 'DIO', 'dio_outkey_update', '1', 'production,rollout,dev', 'DBI', 'scalar', NULL, 'select dio_outkey_update(?,?,?,?,?,?,?)', '', 'never', '1', '', '', ' ');
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1024, 'DIO', 'get_dio_outkey', '1', 'production,rollout,dev', 'DBI', 'hash', NULL, 'select co_name,co_pos,co_default,co_key,co_inout from core_dio_outkey where co_cd_id = ? and co_name = ?', '', 'never', '1', '', '', ' ');
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (4, 'DIO', 'get_dio_outkeys', '1', 'production,rollout,dev', 'DBI', 'arrayofhash', NULL, 'select co_name,co_pos,co_default,co_key,co_inout from core_dio_outkey where co_cd_id = ? order by co_pos', '', 'never', '1', '', '', ' ');
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (1023, 'DIO', 'get_dio_inkey', '1', 'production,rollout,dev', 'DBI', 'hash', NULL, 'select ci_name,ci_pos,ci_req,ci_default, ci_key,ci_inout from core_dio_inkey where ci_cd_id = ? and ci_name = ?', '', 'never', '1', '', '', ' ');
INSERT INTO core_dio (cd_id, cd_namespace, cd_name, cd_version, cd_sysclass, cd_type, cd_return, cd_cache, cd_stmt, cd_stmt_noarg, cd_cache_expire, cd_profile, cd_repl, cd_action, cd_audit) VALUES (3, 'DIO', 'get_dio_inkeys', '1', 'production,rollout,dev', 'DBI', 'arrayofhash', NULL, 'select ci_name,ci_pos,ci_req,ci_default,ci_key,ci_inout from core_dio_inkey where ci_cd_id = ? order by ci_pos', '', 'never', '1', '', '', ' ');

commit;

