PGXN Graphic Identity
=====================

<p><a rel="license" href="https://creativecommons.org/licenses/by/4.0/">
  <img alt="Creative Commons License" src="https://licensebuttons.net/l/by/4.0/88x31.png" />
</a></p>

<p>The <span xmlns:dct="https://purl.org/dc/terms/" href="https://purl.org/dc/dcmitype/StillImage" property="dct:title" rel="dct:type">PGXN Graphic Identity</span>
by <a xmlns:cc="https://creativecommons.org/ns" href="https://justatheory.com/" property="cc:attributionName" rel="cc:attributionURL">David E. Wheeler</a>,
including the type treatments of the word "PGXN" and the phrase "PostgreSQL
Extension Network", as well as the gear logo, is licensed under a
<a rel="license" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
Based on a work at <a xmlns:dct="https://purl.org/dc/terms/" href="https://pgxn.org/art/" rel="dct:source">pgxn.org</a>.
Design by Strongrrl.</p>

### Logo Type ###

* The text "PGXN" is composed in
  [Bank Gothic BT](https://www.myfonts.com/collections/bank-gothic-font-bitstream)
* The text "PostgreSQL Extension Network" is rendered in
  [Myriad](https://www.myfonts.com/collections/myriad-font-adobe) 215 LT condensed

### Logo Art ###

* PGXN Logo Type:
  [EPS](/ui/img/pgxn.eps) |
  [SVG](/ui/img/pgxn.svg) |
  [PNG](/ui/img/pgxn.png)
* PGXN Logo White Gear:
  [EPS](/ui/img/gear.eps) |
  [SVG](/ui/img/gear.svg) |
  [PNG](/ui/img/gear-512.png)
* PGXN Logo White Gear on Blue:
  [EPS](/ui/img/icon.eps) |
  [SVG](/ui/img/icon.svg) |
  [PNG](/ui/img/icon-512.png)
* PGXN Logo Black Gear:
  [EPS](/ui/img/gear-black.eps) |
  [SVG](/ui/img/gear-black.svg) |
  [PNG](/ui/img/gear-black-512.png)
