name    = Store-Indexed
version = 0.1
author  = mc@radiopiloten.de
license = Perl_5
copyright_holder = Milan Chrobok
copyright_year   = 2026

; Manually list the plugins from @Basic, excluding [MakeMaker]
[GatherDir]
exclude_filename = Makefile.PL
exclude_filename = README
exclude_filename = MANIFEST
exclude_filename = META.json
exclude_filename = META.yml
exclude_filename = .project

exclude_directory = debian
[PruneCruft]
[ManifestSkip]
[MetaYAML]
[License]
[Readme]
[ExtraTests]
[ExecDir]
[ShareDir]
[Manifest]
[TestRelease]
[ConfirmRelease]
[UploadToCPAN]

; Add your custom plugins
[AutoPrereqs]
[PkgVersion]

; This replaces the standard MakeMaker
[MakeMaker::Awesome]
header = my $inc = '-I.';
WriteMakefile_arg = INC => $inc
; Explicitly tell it to look for the XS file
header = sub MY::postamble { return '$(OBJECT) : Indexed.xs'; }

[ReadmeAnyFromPod / MarkdownInRoot]
filename = README.md
