;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.001

name=Desktop-Workspace-Util
[@Author::PERLANCAR]
:version=0.610

[Prereqs / TestRequires]
;Test::More=0.98

[Prereqs]
perl=5.010001
strict=0
warnings=0
Desktop::KDEActivity::Util=0.002
Desktop::Open=0.004
Exporter=5.57
IPC::System::Options=0.339
List::Util=1.54
List::Util::Find=0.004
Log::ger=0.038
Perinci::Sub::Util=0.472

[Prereqs / DevelopX_spec]
-phase=develop
-relationship=x_spec
Rinci=1.1.102

