---
abstract: 'High-performance URL router built on a Ragel-generated state machine'
author:
  - vividsnow
build_requires:
  Devel::Size: '0'
  Encode: '0'
  ExtUtils::MakeMaker: '0'
  Test::LeakTrace: '0'
  Test::More: '0'
  URI::Escape::XS: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Router-Ragel
no_index:
  directory:
    - t
    - inc
provides:
  Router::Ragel:
    file: lib/Router/Ragel.pm
    version: '0.02'
requires:
  Inline: '0'
  Inline::C: '0'
  Inline::Filters::Ragel: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/vividsnow/Router-Ragel/issues
  repository: https://github.com/vividsnow/Router-Ragel.git
version: '0.02'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
