name    = Map-Metro-Plugin-Map-Lyon
author  = Philippe Bruhat (BooK) <book@cpan.org>
license = Perl_5
copyright_holder = Philippe Bruhat (BooK)
; copyright_year = 2015-2026

; file modifiers
[OurPkgVersion]
[PodWeaver]

; file generators
[ManifestSkip]
[Manifest]
[License]
[MakeMaker]

[PruneCruft]
[PruneFiles]
match    = mess/.*
match    = cover_db

[GatherDir]

[MapMetro::MakeLinePod]

; prereqs
[AutoPrereqs]

[Prereqs]
perl = 5.014
Moose = 2.000
Map::Metro = 0.1900

[Prereqs / BuildRequires]
Test::CPAN::Meta =
Test::Pod =

[Prereqs / TestRequires]
Test::More = 0.88

; metadata
[MetaYAML]
[MetaJSON]
[MetaProvides::Package]

[MetaNoIndex]
directory = t
directory = xt
directory = inc
directory = share
directory = eg
directory = examples

[ShareDir]

[Keywords]
keywords = metro lyon

[MetaResources]
repository.web    = http://github.com/book/Map-Metro-Plugin-Map-Lyon
repository.url    = http://github.com/book/Map-Metro-Plugin-Map-Lyon.git
repository.type   = git
bugtracker.web    = http://rt.cpan.org/NoAuth/Bugs.html?Dist=Map-Metro-Plugin-Map-Lyon
bugtracker.mailto = bug-map-metro-plugin-map-lyon@rt.cpan.org

; tests
[MetaTests]
[ExtraTests]
[Test::ReportPrereqs]
[PodSyntaxTests]
;[PodCoverageTests]

; release
[NextRelease]
format = %v %{yyyy-MM-dd}d %P

[Git::NextVersion]
first_version = 1.000

[TestRelease]
[ConfirmRelease]
[UploadToCPAN]

; git
[Git::Check]
[Git::Commit]
commit_msg  = Changes for version %v
changelog   = Changes

[Git::Tag]
tag_format  = v%v
tag_message = %N v%v

[Git::Push]
push_to     = origin
push_to     = github
