---
abstract: 'Non-blocking, multi-worker asynchronous wrapper for DBIx::Class'
author:
  - 'Mohammad Sajid Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  DBI: '0'
  DBIx::Class: '0'
  ExtUtils::MakeMaker: '0'
  File::Copy: '0'
  File::Spec: '0'
  File::Temp: '0'
  Future::AsyncAwait: '0'
  SQL::Translator: '0.11018'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Class-Async
no_index:
  directory:
    - t
    - inc
provides:
  DBIx::Class::Async:
    file: lib/DBIx/Class/Async.pm
    version: '0.64'
  DBIx::Class::Async::Exception:
    file: lib/DBIx/Class/Async/Exception.pm
    version: '0.64'
  DBIx::Class::Async::Exception::AmbiguousColumn:
    file: lib/DBIx/Class/Async/Exception/AmbiguousColumn.pm
    version: '0.64'
  DBIx::Class::Async::Exception::Factory:
    file: lib/DBIx/Class/Async/Exception/Factory.pm
    version: '0.64'
  DBIx::Class::Async::Exception::MissingColumn:
    file: lib/DBIx/Class/Async/Exception/MissingColumn.pm
    version: '0.64'
  DBIx::Class::Async::Exception::NoSuchRelationship:
    file: lib/DBIx/Class/Async/Exception/NoSuchRelationship.pm
    version: '0.64'
  DBIx::Class::Async::Exception::NotInStorage:
    file: lib/DBIx/Class/Async/Exception/NotInStorage.pm
    version: '0.64'
  DBIx::Class::Async::Exception::RelationshipAsColumn:
    file: lib/DBIx/Class/Async/Exception/RelationshipAsColumn.pm
    version: '0.64'
  DBIx::Class::Async::ResultSet:
    file: lib/DBIx/Class/Async/ResultSet.pm
    version: '0.64'
  DBIx::Class::Async::ResultSet::Pager:
    file: lib/DBIx/Class/Async/ResultSet/Pager.pm
    version: '0.64'
  DBIx::Class::Async::ResultSetColumn:
    file: lib/DBIx/Class/Async/ResultSetColumn.pm
    version: '0.64'
  DBIx::Class::Async::Row:
    file: lib/DBIx/Class/Async/Row.pm
    version: '0.64'
  DBIx::Class::Async::Schema:
    file: lib/DBIx/Class/Async/Schema.pm
    version: '0.64'
  DBIx::Class::Async::SelectNormaliser:
    file: lib/DBIx/Class/Async/SelectNormaliser.pm
    version: '0.64'
  DBIx::Class::Async::Storage:
    file: lib/DBIx/Class/Async/Storage.pm
    version: '0.64'
  DBIx::Class::Async::Storage::DBI:
    file: lib/DBIx/Class/Async/Storage/DBI.pm
    version: '0.64'
  DBIx::Class::Async::Storage::DBI::Cursor:
    file: lib/DBIx/Class/Async/Storage/DBI/Cursor.pm
    version: '0.64'
requires:
  CHI: '0'
  Carp: '0'
  DBIx::Class: '0.082841'
  DBIx::Class::InflateColumn::Serializer: '0'
  Data::Page: '0'
  Digest::MD5: '0'
  Future: '0'
  IO::Async::Function: '0'
  IO::Async::Loop: '0'
  JSON: '0'
  JSON::MaybeXS: '0'
  Metrics::Any: '0'
  Scalar::Util: '0'
  Time::HiRes: '0'
  Try::Tiny: '0'
  Type::Params: '0'
  Types::Standard: '0'
  perl: '5.014'
resources:
  bugtracker: https://github.com/manwar/DBIx-Class-Async/issues
  repository: https://github.com/manwar/DBIx-Class-Async.git
version: '0.64'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
