---
abstract: Amazon::S3::Lite
author:
  - 'Rob Lauer <rlauer@treasurersbriefcase.com>'
build_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
  HTTP::Tiny: '0'
  IO::Scalar: '0'
  JSON::PP: '4.16'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Amazon-S3-Lite
no_index:
  directory:
    - t
    - inc
provides:
  Amazon::S3::Lite:
    file: lib/Amazon/S3/Lite.pm
    version: v1.1.5
  Amazon::S3::Lite::Credentials:
    file: lib/Amazon/S3/Lite/Credentials.pm
    version: v1.1.5
  Amazon::S3::Lite::Logger:
    file: lib/Amazon/S3/Lite/Logger.pm
    version: v1.1.5
requires:
  Amazon::Signature4::Lite: v1.0.0
  HTTP::Tiny: '0.088'
  IO::Socket::SSL: '0'
  List::Util: '0'
  Net::SSLeay: '0'
  URI::Escape: '5.34'
  XML::Twig: '0'
  perl: '5.010'
resources:
  bugtracker: http://github.com/rlauer6/Amazon-S3-Lite/issues
  homepage: http://github.com/rlauer6/Amazon-S3-Lite.git
  repository: git://github.com/rlauer6/Amazon-S3-Lite.git
version: v1.1.5
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
