; SPDX-FileCopyrightText: 2014 Koichi SATOH <r.sekia@gmail.com>
; SPDX-FileCopyrightText: 2026 Wesley Schwengle <waterkip@cpan.org>
;
; SPDX-License-Identifier: MIT

name    = Lingua-TermWeight
author  = Wesley Schwengle <waterkip@cpan.org>
license = MIT
copyright_holder = Wesley Schwengle
copyright_year   = 2026

[@Author::WATERKIP]
[Prereqs / TestNeeds]
-phase = test
Import::Into    = 1.002003
Test::Most = 0
Sub::Override = 0
