---
abstract: 'Perl TUI Framework (Turbo Vision 2.0 Port)'
author:
  - 'J. Schneider'
build_requires:
  Devel::Refcount: '0.10'
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0.43'
  Test::More: '0.95'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: TUI-Vision
no_index:
  directory:
    - t
    - inc
provides:
  PerlX::Assert::PP:
    file: lib/PerlX/Assert/PP.pm
    version: '0.04'
  TUI::App:
    file: lib/TUI/App.pm
    version: v2.0.2
  TUI::ColorSel:
    file: lib/TUI/ColorSel.pm
    version: v2.0.2
  TUI::Dialogs:
    file: lib/TUI/Dialogs.pm
    version: v2.0.2
  TUI::Drivers:
    file: lib/TUI/Drivers.pm
    version: v2.0.2
  TUI::Editors:
    file: lib/TUI/Editors.pm
    version: v2.0.2
  TUI::Gadgets:
    file: lib/TUI/Gadgets.pm
    version: v2.0.2
  TUI::Help:
    file: lib/TUI/Help.pm
    version: v2.0.2
  TUI::Memory:
    file: lib/TUI/Memory.pm
    version: v2.0.2
  TUI::MsgBox:
    file: lib/TUI/MsgBox.pm
    version: v2.0.2
  TUI::Objects:
    file: lib/TUI/Objects.pm
    version: v2.0.2
  TUI::StdDlg:
    file: lib/TUI/StdDlg.pm
    version: v2.0.2
  TUI::TextView:
    file: lib/TUI/TextView.pm
    version: v2.0.2
  TUI::Validate:
    file: lib/TUI/Validate.pm
    version: v2.0.2
  TUI::Views:
    file: lib/TUI/Views.pm
    version: v2.0.2
  TUI::Vision:
    file: lib/TUI/Vision.pm
    version: v2.0.2
  TUI::toolkit:
    file: lib/TUI/toolkit.pm
    version: v2.0.2
recommends:
  PerlX::Assert: '0.905'
  Sub::Util: '1.40'
  Type::Params: '2.000001'
requires:
  Carp: '1.01'
  Class::Struct: '0'
  Devel::StrictMode: '0.003'
  Encode: '0'
  Import::Into: '1.002005'
  Importer: '0.026'
  Module::Loaded: '0'
  Params::Check: '0'
  Scalar::List::Utils: '1.36'
  Termbox::PP: v0.6.0
  Terminal::WCWidth: '0'
  UNIVERSAL::Object: '0.17'
  autodie::Scope::Guard: '0'
  perl: '5.014'
resources:
  bugtracker: https://github.com/brickpool/TUI-Vision/issues
  repository: https://github.com/brickpool/TUI-Vision.git
version: '2.000002'
x_homepage: http://brickpool.de
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
