---
abstract: File::Process
author:
  - 'Rob Lauer <rclauer@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
  Text::CSV_XS: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Process
no_index:
  directory:
    - t
    - inc
provides:
  File::Process:
    file: lib/File/Process.pm
    version: v1.0.0
  File::Process::Utils:
    file: lib/File/Process/Utils.pm
    version: v1.0.0
requires:
  IO::Scalar: '2.113'
  JSON: '4.10'
  Readonly: '2.05'
  perl: '5.010'
resources:
  bugtracker: https://github.com/rlauer6/File-Process/issues
  homepage: https://github.com/rlauer6/File-Process
  repository: https://github.com/rlauer6/File-Process
version: v1.0.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
