---
abstract: 'Find out whether chmod can really take access away, so tests know when to skip'
author:
  - 'Nigel Horne <njh@nigelhorne.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::DescribeMe: '0'
  Test::Mockingbird: '0.13'
  Test::Most: '0'
  Test::Returns: '0.04'
  Test::Warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150015'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Permissions
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Cwd: '0'
  Errno: '0'
  Exporter: '0'
  File::Path: '2.07'
  File::Spec: '0'
  File::Temp: '0'
  IPC::System::Simple: '0'
  Params::Get: '0.17'
  Params::Validate::Strict: '0.40'
  Readonly: '0'
  Return::Set: '0'
  Test::More: '0'
  autodie: '0'
  perl: '5.026'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Test-Permissions
  homepage: https://metacpan.org/pod/Test::Permissions
  repository: git://github.com/nigelhorne/Test-Permissions.git
version: v0.001.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
