---
abstract: Database independent interface for Perl
author:
  - DBI team (dbi-users@perl.org)
build_requires:
  perl: '5.008001'
configure_requires:
  ExtUtils::MakeMaker: '6.48'
dynamic_config: 1
generated_by: Author, CPAN::Meta::Converter version 2.150013
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBI
provides:
  DBI:
    file: DBI.pm
    version: '1.653'
recommends:
  Encode: '3.24'
  Test::More: '1.302224'
requires:
  Module::Load: '0.22'
  Test::More: '0.96'
  XSLoader: '0'
  perl: '5.012000'
resources:
  IRC: irc://irc.perl.org/#dbi
  bugtracker: https://github.com/perl5-dbi/dbi/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/perl5-dbi/dbi
version: '1.653'
