---
abstract: 'Lucy search engine library.'
author:
  - 'Lucy search project'
build_requires:
  Clownfish: '0.007'
  Clownfish::CFC: '0.007'
  Devel::PPPort: '3.14'
  ExtUtils::CBuilder: '0.21'
  ExtUtils::ParseXS: '3'
  Module::Build: '0.280801'
configure_requires:
  Clownfish: '0.007'
  Clownfish::CFC::Perl::Build: '0.007'
  Module::Build: '0.280801'
dynamic_config: 1
generated_by: 'Module::Build version 0.4232, CPAN::Meta::Converter version 2.150010'
keywords:
  - search
  - lucy
  - lucene
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lucy
no_index:
  directory:
    - buildlib
    - devel
    - sample
  package:
    - Lucy::Test
requires:
  Clownfish: '0.007'
  perl: v5.8.3
resources:
  bugtracker: https://github.com/lucysearch/lucy/issues
  homepage: https://github.com/lucysearch/lucy
  repository: https://github.com/lucysearch/lucy.git
version: v0.7.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
