---
abstract: 'Script initialization and utility functions for Test2::Harness'
author:
  - 'Chad Granum <exodist@cpan.org>'
build_requires:
  Test2::V0: '1.302199'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Yath-Script
requires:
  Carp: '0'
  Cwd: '3.75'
  File::Spec: '0'
  Getopt::Yath: '2.000008'
  Importer: '0.025'
  perl: '5.014000'
resources:
  bugtracker: https://github.com/Test-More/Test2-Harness/issues
  repository: https://github.com/Test-More/Test2-Harness/
version: '2.000012'
x_generated_by_perl: v5.42.2
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
