---
abstract: 'do math with correct handling of significant figures'
author:
  - 'Sullivan Beck (https://github.com/SBECK-github/)'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Inter: '1.09'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-SigFigs
no_index:
  directory:
    - t
    - inc
provides:
  Math::SigFigs:
    file: lib/Math/SigFigs.pm
    version: '1.22'
requires:
  Carp: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/SBECK-github/Math-SigFigs/issues
  homepage: https://github.com/SBECK-github/Math-SigFigs
  repository: git://github.com/SBECK-github/Math-SigFigs.git
version: '1.22'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
