=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::files-file_id-content - Documentation for the /files/{file_id}/content path.

=head1 OPERATIONS

=head2 GET /files/{file_id}/content

=head3 downloadFile

  $client->download_file({
      body => { ... },
  });

Returns the contents of the specified file.

=head4 Path/query parameters

=over

=item * C<file_id> (in path, required, string) - The ID of the file to use for this request.

=back

=head4 Responses

B<200 - OK>

Content-Type: application/json

Example:

    "string"

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2026 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut
