=encoding utf8

=head1 NAME

OpenAPI::Client::OpenAI::Path::vector_stores-vector_store_id-files-file_id-content - Documentation for the /vector_stores/{vector_store_id}/files/{file_id}/content path.

=head1 DESCRIPTION

This document describes the API endpoint at C</vector_stores/{vector_store_id}/files/{file_id}/content>.

=head1 PATHS


=head2 C<GET /vector_stores/{vector_store_id}/files/{file_id}/content>

Retrieve vector store file content


Retrieve the parsed contents of a vector store file.



=head3 Operation ID

C<retrieveVectorStoreFileContent>

    $client->retrieveVectorStoreFileContent( ... );

=head3 Parameters

=over 4

=item * C<vector_store_id> (in path) (Required) - The ID of the vector store.

Type: C<string>



=item * C<file_id> (in path) (Required) - The ID of the file within the vector store.

Type: C<string>



=back


=head3 Responses


=head4 Status Code: C<200>

OK


=head4 Content Types:

=over 4


=item * C<application/json>

Example (See the L<OpenAI spec for more detail|https://github.com/openai/openai-openapi/blob/master/openapi.yaml>):

    {
       "data" : [
          null
       ]
    }


=back

=head1 SEE ALSO

L<OpenAPI::Client::OpenAI::Path>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023-2025 by Nelson Ferraz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.0 or,
at your option, any later version of Perl 5 you may have available.

=cut