use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007004
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib ) );
__DATA__
API
Alders
Alders'
Andy
Boris
DB
Dave
Eilam
Eilam's
Florian
GitHub
Greg
Inc
Jack
MAXMIND
MAXMIND's
MaxMind
MaxMind's
Olaf
Oschwald
Oschwald's
PayPal
Ragwitz
Ran
Reader
Rolsky
Rolsky's
VERSIONING
XS
YYY
YYYZZZ
Zentner
bzentner
drolsky
github
goschwald
lib
libmaxminddb
oalders
rafl
reilam
versioning
