---
abstract: 'Official Perl client library for the InternetData API'
author:
  - 'Mslm Dev <support@internetdata.io>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
keywords:
  - ip-data
  - ip-database
  - asn
  - geolocation
  - mmdb
  - network-data
  - ip-intelligence
  - dataset-download
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: InternetData
no_index:
  directory:
    - t
    - inc
    - t
requires:
  IO::Socket::SSL: '2.009'
  Mojolicious: '9.00'
  perl: '5.022'
resources:
  bugtracker: https://github.com/internetdata/sdk-perl/issues
  homepage: https://internetdata.io
  repository: https://github.com/internetdata/sdk-perl.git
version: v1.3.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
