;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version = 0.091

name    = Module-CheckVersion

[GenPericmdScript]
url=/Module/CheckVersion/check_module_version
cmdline=inline

[@Author::PERLANCAR]
:version=0.610

[Prereqs / TestRequires]
;Test::More=0.98

[Prereqs]
perl=5.010001
strict=0
warnings=0
Exporter=5.57
File::Slurper=0
File::Temp=0.2310
HTTP::Tiny=0.057
JSON::MaybeXS=0
Parse::CPAN::Packages=0

[Prereqs / DevelopX_spec]
-phase=develop
-relationship=x_spec
Rinci=1.1.102
