;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.003

name=App-KBLIUtils

[GenPericmdScript / GenPericmdScript compare-kbli-2020-2025-codes]
url=/App/KBLIUtils/compare_kbli_2020_2025_codes
read_config=0
read_env=0
enable_log=1

[GenPericmdScript / GenPericmdScript get-kbli-2020-description]
url=/App/KBLIUtils/get_kbli_2020_description
read_config=0
read_env=0
enable_log=1

[GenPericmdScript / GenPericmdScript get-kbli-2025-description]
url=/App/KBLIUtils/get_kbli_2025_description
read_config=0
read_env=0
enable_log=1

[GenPericmdScript / GenPericmdScript get-kbli-2020-title]
url=/App/KBLIUtils/get_kbli_2020_title
read_config=0
read_env=0
enable_log=1

[GenPericmdScript / GenPericmdScript get-kbli-2025-title]
url=/App/KBLIUtils/get_kbli_2025_title
read_config=0
read_env=0
enable_log=1

[GenPericmdScript / GenPericmdScript list-kbli-2020-codes]
url=/App/KBLIUtils/list_kbli_2020_codes
read_config=0
read_env=0
pass_cmdline_object=1
enable_log=1

[GenPericmdScript / GenPericmdScript list-kbli-2025-codes]
url=/App/KBLIUtils/list_kbli_2025_codes
read_config=0
read_env=0
pass_cmdline_object=1
enable_log=1

[InsertExecsList]

[@Author::PERLANCAR]
:version=0.610

[Prereqs]
perl=5.010001
strict=0
warnings=0
Perinci::Sub::Gen::AccessTable=0.592
TableData::Business::ID::KBLI::2020::Code=0
TableData::Business::ID::KBLI::2025::Code=0

[Prereqs / DevelopX_spec]
-phase=develop
-relationship=x_spec
Rinci=1.1.102
