=encoding UTF-8

=head1 NAME

Gungho::Component::Authentication.ja - Gungho認証親クラス

=head1 SYNOPSIS

   package MyAuth;
   use base qw(Gungho::Component::Authentication);

=head1 DESCRIPTION

Gungho::Component::AuthenticationはWWW認証の親クラスとして使用されます。

HTTPレスポンスのヘッダーを確認し、UnauthorizedやProxy Authentication Required
等が返ってきている場合はauthenticate()を呼んで認証を行います

=head1 METHODS

=head2 authenticate($is_proxy, $auth_params, $request, $response)

実際の認証を行います。継承クラスが実装を提供する必要があります。
認証が成功した場合は正を返し、失敗した場合は負を返します。

認証が失敗した場合に必要なHTTPリクエスト等もC<authenticate()>内で再ディスパッチ
する必要があります。

=head2 check_authentication_challenge($c, $req, $res)

HTTPレスポンスヘッダーに認証チャレンジが含まれているかどうか確認し、
必要なC<authenticate()>メソッドを呼び出します。

=cut