---
abstract: 'Pattern based string generator library and CLI'
author:
  - 'Magnus Weinberg <magnus.weinberg@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Wildling
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.014'
resources:
  bugtracker: https://github.com/dotmonk/wildling/issues
  homepage: https://github.com/dotmonk/wildling
  repository: https://github.com/dotmonk/wildling.git
version: v2.0.7
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
