---
abstract: 'DBI driver for Cloudflare D1 (serverless SQLite)'
author:
  - 'Aldo Montes Zapata <amontes@cpan.org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBD-D1
no_index:
  directory:
    - t
    - inc
requires:
  DBI: '1.640'
  HTTP::Tiny: '0.070'
  IO::Socket::SSL: '1.42'
  JSON::PP: '2.97'
  Net::SSLeay: '1.49'
  perl: '5.014'
resources:
  bugtracker: https://github.com/amzt/DBD-D1/issues
  repository: https://github.com/amzt/DBD-D1.git
version: '0.02'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
