---
abstract: 'Epub reader built with Perl and Chandra'
author:
  - 'lnation <email@lnation.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Chandra-EPUB
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Zip: '0'
  Chandra: '0.06'
  Encode: '0'
  File::ShareDir: '1.00'
  MIME::Base64: '0'
  perl: '5.008003'
version: '0.02'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
