---
abstract: 'list and extract Electron ASAR (Atom Shell Archive) files'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker: '7.0'
  File::Find: '0'
  File::Spec: '0'
  strict: '0'
  warnings: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150015'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Archive-Asar
no_index:
  directory:
    - t
    - inc
    - xt
recommends:
  Cpanel::JSON::XS: '0'
requires:
  Carp: '0'
  Fcntl: '0'
  JSON::PP: '0'
  constant: '0'
  perl: '5.036000'
resources:
  bugtracker: https://codeberg.org/mauke/Archive-Asar/issues
  repository: https://codeberg.org/mauke/Archive-Asar.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
