name    = Sys-OsRelease
author  = Ian Kluft <https://github.com/ikluft>
license = Artistic_2_0
copyright_holder = Ian Kluft
copyright_year   = 2022-2026

main_module     = lib/Sys/OsRelease.pm

[Prereqs]
perl = 5.022
version = 0
[ModuleBuild]

[InstallGuide]
[MetaJSON]
[AutoPrereqs]
[PkgVersion]
[NextRelease]
time_zone = America/Los_Angeles
[PodWeaver]
[GitHub::Meta]

[Test::Perl::Critic]
critic_config = perlcritic.rc
[PodSyntaxTests]
[Test::CPAN::Changes]
[Test::UnusedVars]

[Git::Check]
allow_dirty = dist.ini
allow_dirty = Changes
untracked_files = warn
[PreviousVersion::Changelog]
[NextVersion::Semantic]
major = MAJOR, API CHANGE
minor = MINOR, ENHANCEMENTS, SECURITY
revision = REVISION, BUG FIXES, DOCS

[Git::Commit]
allow_dirty = dist.ini
allow_dirty = Changes
commit_msg  = Sys::OsRelease v%V%n%n%c
[Git::Tag]
tag_format = v%v
tag_message = Sys::OsRelease v%V%n%n%c
[Git::Push]

[@Filter]
-bundle = @Basic
-remove = MakeMaker
option = for_basic

;[RPM]
;spec_file = Sys-OsRelease.spec
;sign = 1
;ignore_build_deps = 0
