---
abstract: 'Validate against Crypt::SaltedHash hashes with Crypt::Passphrase'
author:
  - 'Robert Rothenberg <perl@rhizomnic.com>'
build_requires:
  Crypt::SysRandom: '0'
  Digest::MD5: '2.25'
  Digest::SHA: '5.96'
  ExtUtils::MakeMaker: '7.22'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Metadata: '1.000015'
  Plack::Middleware::ContentLength: '0'
  Plack::Middleware::Head: '0'
  Test2::Require::Module: '0'
  Test2::V0: '0'
  Test::Differences: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
keywords:
  - authentication
  - auth
  - salted
  - hash
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-Passphrase-SaltedHash
provides:
  Crypt::Passphrase::SaltedHash:
    file: lib/Crypt/Passphrase/SaltedHash.pm
    version: '0.02'
requires:
  Crypt::Passphrase::Validator: '0'
  Digest: '1.19'
  MIME::Base64: '0'
  parent: '0'
  perl: v5.6.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/robrwo/perl-Crypt-Passphrase-SaltedHash/issues
  repository: git://github.com/robrwo/perl-Crypt-Passphrase-SaltedHash.git
version: '0.02'
x_authority: cpan:RRWO
x_generated_by_perl: v5.42.1
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: Artistic-2.0
