---
abstract: 'persistence for Perl data structures'
author:
  - 'Perl 5 Porters'
build_requires:
  ExtUtils::MakeMaker: '6.31'
  File::Temp: '0'
  Test::More: '0.82'
configure_requires:
  ExtUtils::MakeMaker: '6.31'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Storable
no_index:
  directory:
    - t
    - inc
provides:
  Storable:
    file: lib/Storable.pm
    version: '3.41'
requires:
  XSLoader: '0'
resources:
  bugtracker: https://github.com/Perl/perl5/issues
version: '3.41'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
