---
abstract: 'Fast 64-bit PRNG with guaranteed minimum 2^64 period'
author:
  - 'Scott Baker <https://www.perturb.org>'
build_requires:
  ExtUtils::MakeMaker: '6.64'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-Random-Biski64
no_index:
  directory:
    - t
    - inc
optional_features:
  Windows:
    description: 'Windows CSPRNG support'
    recommends:
      Win32::API: '0'
requires:
  Carp: '0'
  perl: '5.012000'
resources:
  bugtracker: https://github.com/bakers/perl-Math-Random-Biski64/issues
  homepage: https://github.com/bakers/perl-Math-Random-Biski64
  repository: https://github.com/bakers/perl-Math-Random-Biski64.git
version: v0.2.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
