use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007002
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
cpanreporter
exe
metabase
na
skipfile
David
Golden
dagolden
Alexandr
Ciornii
alexchorny
Breno
de
Oliveira
garu
Christian
Walde
walde
Ed
mohawk2
Joel
Maslak
jmaslak
Kent
Fredric
kentfredric
Matthew
Musgrove
mr
Patrice
Clement
monsieurp
Reini
Urban
rurban
Scott
Wiersdorf
scott
Slaven
Rezic
slaven
lib
CPAN
Reporter
API
Config
FAQ
History
PrereqCheck
