;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.002

name=App-FzfUtils

[GenPericmdScript / GenPericmdScript cs-select]
url=/App/FzfUtils/cs_select
read_config=0
read_env=0
enable_log=1

[GenPericmdScript / GenPericmdScript fzf2clip]
url=/App/FzfUtils/fzf2clip
read_config=0
read_env=0
enable_log=1

[GenPericmdScript / GenPericmdScript fzf2clip-loop]
url=/App/FzfUtils/fzf2clip_loop
read_config=0
read_env=0
enable_log=1

[InsertExecsList]

[@Author::PERLANCAR]
:version=0.610

[Prereqs]
perl=5.010001
strict=0
warnings=0
Clipboard::Any=0.011
File::Temp=0.2310
IPC::Open2=0
JSON::PP=0
Log::ger=0.038
Org::Parser::Tiny=0.005
Text::ANSI::Util=0.22

[Prereqs / DevelopX_spec]
-phase=develop
-relationship=x_spec
Rinci=1.1.102

