---
abstract: 'Fatpack-style bundler with PPI-based minification for standalone Perl scripts'
author:
  - 'Nicolas Mendoza <mendoza@pvv.ntnu.no>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-SlimPacker
no_index:
  directory:
    - t
    - inc
requires:
  App::FatPacker: '0'
  Module::CoreList: '0'
  PPI: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/nicomen/App-SlimPacker/issues
  repository: https://github.com/nicomen/App-SlimPacker
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
