[GatherDir]
[PruneCruft]
[ManifestSkip]
[Manifest]
[License]
[PkgVersion]
[PodWeaver]
[PodCoverageTests]
[PodSyntaxTests]
[Test::Perl::Critic]
[Test::Version]
[TestRelease]
[ConfirmRelease]
[UploadToCPAN]

[MetaResources]
repository.url = https://github.com/tfrayner/catalyst-plugin-openidconnect.git
repository.web = https://github.com/tfrayner/catalyst-plugin-openidconnect
repository.type = git

[@Git]
push_to = origin
tag_format = v%v
changelog = Changes

[Prereqs]
perl = 5.020

; Gather from cpanfile if present
[Prereqs / ConfigGatherDir]
