---
abstract: 'OpenID Connect provider plugin for Catalyst'
author:
  - 'Tim F. Rayner <tfrayner@cpan.org>'
build_requires:
  Test::Deep: '0'
  Test::Exception: '0'
  Test::MockObject: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.52'
  Module::CPANfile: '1.1'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-OpenIDConnect
no_index:
  directory:
    - t
    - inc
requires:
  Bytes::Random::Secure: '0'
  Catalyst: '0'
  Catalyst::Runtime: '5.90100'
  Config::General: '0'
  Crypt::Misc: '0'
  Crypt::OpenSSL::RSA: '0.38'
  Crypt::PK::RSA: '0'
  Data::UUID: '0'
  DateTime: '0'
  DateTime::Format::ISO8601: '0'
  Digest::SHA: '0'
  JSON::MaybeXS: '0'
  MIME::Base64: '0'
  Module::Runtime: '0'
  Moose: '0'
  Try::Tiny: '0'
  URI: '0'
  namespace::autoclean: '0'
  perl: '5.020'
resources:
  bugtracker: https://github.com/tfrayner/catalyst-plugin-openidconnect/issues
  repository: https://github.com/tfrayner/catalyst-plugin-openidconnect.git
version: '0.15'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
