name    = Catalyst-Plugin-Statsd
author  = Robert Rothenberg <perl@rhizomnic.com>
license = Artistic_2_0
copyright_holder = Robert Rothenberg
copyright_year   = 2018-2026

[Keywords]
keyword = Catalyst
keyword = StatsD
keyword = metrics
keyword = monitoring

[Meta::Contributors]
contributor = Slaven Rezić <slaven@rezic.de>

[GatherDir]
exclude_match = cpanfile*
exclude_filename = LICENSE
exclude_filename = SECURITY.md
exclude_filename = doap.xml
prune_directory = ^local
[PruneCruft]
[CPANFile]
[License]
[DOAP]
[ExecDir]
[ShareDir]
[MakeMaker]
[Manifest]
[TestRelease]
[CheckExtraTests]
[ConfirmRelease]
[UploadToCPAN]

[RecommendedPrereqs]
[AutoPrereqs]

; [EnsurePrereqsInstalled]
; :version = 0.003
; type = requires
; type = recommends

[Prereqs / BuildRequires ]
-phase = build
-relationship = requires
ExtUtils::MakeMaker = 7.22
Module::Metadata = 1.000015

[Prereqs / DevelopRequires ]
-phase = develop
-relationship = requires
Software::Security::Policy::Individual = 0.10
Test::CVE = 0.11
Test2::Require::AuthorTesting = 0

[Prereqs / RuntimeRequires]
Catalyst =  5.90123
Plack::Middleware::Statsd = v0.9.0

[SecurityPolicy]
; authordep Software::Security::Policy::Individual
-policy = Individual
timeframe = 2 weeks
perl_support_years = 10
git_url = https://github.com/robrwo/CatalystX-Statsd
report_url = https://github.com/robrwo/CatalystX-Statsd/security/advisories

[GitHub::Meta]
repo = git://github.com/robrwo/CatalystX-Statsd.git

[PodWeaver]
; authordep Pod::Weaver::Plugin::AppendPrepend
; authordep Pod::Weaver::Section::Contributors
; authordep Pod::Weaver::Section::SourceGitHub

[UsefulReadme]
type     = gfm
filename = README.md
location = build

[CopyFilesFromBuild]
copy = LICENSE
copy = README.md
copy = SECURITY.md
copy = cpanfile
copy = doap.xml

[PruneFiles]
match = ~$

[Metadata]
x_authority    = cpan:RRWO

[MetaProvides::Package]
[MetaJSON]
[MetaYAML]

[Prereqs / TestRequires ]
-phase = test
-relationship = requires
Net::Statsd::Tiny = v0.3.0
Plack::Middleware::MethodOverride = 0

[PodSyntaxTests]
[Test::DistManifest]
[Test::CleanNamespaces]
[Test::EOF]
[Test::EOL]
:version = 0.14
[Test::Fixme]
[Test::MinimumVersion]
[Test::NoTabs]
[Test::Perl::Critic]
critic_config = t/etc/perlcritic.rc

[Test::Pod::Coverage::Configurable]
[Test::Pod::LinkCheck]
[Test::Portability]
; authordep Test::TrailingSpace
[Test::TrailingSpace]
filename_regex = \.(?:p[lm]|pod)\z
[Test::Kwalitee]
[Test::ReportPrereqs]
:version = 0.027
version_extractor = Module::Metadata
verify_prereqs = 1
include = List::MoreUtils
include = Log::Dispatch
include = Log::Dispatch::Array
include = Term::Size::Perl
include = Term::Size::Win32
include = Net::Statsd::Tiny
include = Crypt::Mac::HMAC

[Test::CVE]
[MojibakeTests]
[Test::MixedScripts]
; authordep Test::MixedScripts
[Test::CPAN::Changes]
; authordep Test::CPAN::Changes

[Test::PodSpelling]
[Test::UnusedVars]

[MetaTests]

[Test::Version]
[Test::Compile]
; authordep Test::Compile
filename = xt/00-compile.t

[@Git]
allow_dirty = dist.ini
push_to     = origin master:master
tag_format  = %v
commit_msg  = %v%n%n%c

[Git::Contributors]
:version = 0.019

[RewriteVersion]
[NextRelease]
[BumpVersionAfterRelease]

[Git::Commit / Commit_Changes] ; commit Changes (for new dev)
allow_dirty_match = ^lib/
commit_msg = Commit Changes and bump $VERSION
