name             = WWW-RobotRules
author           = Gisle Aas <gisle@activestate.com>
license          = Perl_5
copyright_holder = Gisle Aas
copyright_year   = 1995

[Git::GatherDir]
exclude_filename = LICENSE
exclude_filename = META.json
exclude_filename = Makefile.PL
exclude_filename = perlimports.toml
exclude_filename = precious.toml
exclude_filename = .perltidyrc
exclude_filename = README.md

[MetaConfig]
[MetaProvides::Package]
[MetaNoIndex]
directory = t
directory = xt

[MetaYAML]
[MetaJSON]
[MetaResources]
x_MailingList = mailto:libwww@perl.org

[Git::Contributors]
[GithubMeta]
issues = 1
user = libwww-perl

[Manifest]
[License]
[InstallGuide]
:version = 1.200013

[Prereqs::FromCPANfile]

[MakeMaker]

[MojibakeTests]
[Test::Version]
[Test::ReportPrereqs]

[Test::Compile]
:version = 2.059
bail_out_on_fail = 1
xt_mode = 1
; WWW::RobotRules::DB_File needs the optional, non-core DB_File module
skip = WWW::RobotRules::DB_File

[Test::Portability]
[Test::EOL]

[Test::MinimumVersion]
[PodSyntaxTests]

[Test::Pod::Coverage::Configurable]
skip = WWW::RobotRules::AnyDBM_File
skip = WWW::RobotRules::DB_File
trustme = WWW::RobotRules => qr/^(?:Version|is_me|visit|no_visits|last_visit|fresh_until|push_rules|clear_rules|rules|dump)$/

[Test::PodSpelling]
wordlist = Pod::Wordlist
stopword = AnyDBM
stopword = Aas
stopword = Ardo
stopword = cybermapper
stopword = DBM
stopword = diskcaching
stopword = Gisle
stopword = Hakan
stopword = Koster
stopword = Martijn
stopword = RobotUA
stopword = txt

[Git::Check]
allow_dirty =

[CheckStrictVersion]
decimal_only = 1

[RunExtraTests]
[CheckChangeLog]
[CheckChangesHasContent]
[TestRelease]

[UploadToCPAN]

[ReadmeAnyFromPod / Markdown_Readme]
source_filename = lib/WWW/RobotRules.pm
type = markdown
filename = README.md
location = root
phase = release

[CopyFilesFromRelease]
filename = META.json
filename = LICENSE

[@Git::VersionManager]
commit_files_after_release = META.json
commit_files_after_release = LICENSE
commit_files_after_release = README.md

[Git::Push]

[ConfirmRelease]
