---
abstract: 'A lightweight ULID (Universally Unique Lexicographically Sortable Identifier) generator'
author:
  - 'Scott Baker'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ULID-Tiny
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::SysRandom: '0.007'
  Time::HiRes: '0'
  perl: '5.016'
resources:
  repository: https://github.com/scottchiefbaker/perl-ULID-Tiny.git
version: v1.0.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
