name = Mojo-ATProto-OAuth
author = Ben van Staveren <ben@beardeddutchman.services>
license = Perl_5
copyright_holder = Ben van Staveren

main_module = lib/Mojo/ATProto/OAuth.pm

[MetaResources]
repository.url  = https://tangled.org/beardeddutchman.services/mojo-atproto-oauth/
repository.web  = https://tangled.org/beardeddutchman.services/mojo-atproto-oauth/
repository.type = git
bugtracker.web  = https://tangled.org/beardeddutchman.services/mojo-atproto-oauth/issues

[MetaJSON]
[MetaProvides::Package]

[Git::GatherDir]
[Git::NextVersion]
first_version = 1.00
version_regexp = ^(.+)$
[Git::Tag]
tag_format = %v
[Git::Push]

[OurPkgVersion]

[@Filter]
-bundle = @Basic
-remove = GatherDir
-remove = Readme
#-remove = UploadToCPAN

[AutoPrereqs]

[Prereqs]
JSON = 0

[Prereqs / RuntimeRecommends]
Mojo::SQLite = 0
Mojo::Pg     = 0
