---
abstract: 'shuffle sequences while preserving their k-let counts'
author:
  - 'Michael T. Wolfinger <michael@wolfinger.eu>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
keywords:
  - bioinformatics
  - 'sequence shuffling'
  - k-let
  - k-mer
  - 'dinucleotide shuffling'
  - RNA
  - DNA
  - 'null model'
  - uShuffle
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Ushuffle
no_index:
  directory:
    - t
    - inc
provides:
  Ushuffle:
    file: lib/Ushuffle.pm
    version: '1.00'
  Ushuffle::Shuffler:
    file: lib/Ushuffle.pm
    version: '1.00'
requires:
  perl: '5.010001'
resources:
  bugtracker: https://github.com/mtw/ushuffle-perl/issues
  repository: https://github.com/mtw/ushuffle-perl.git
version: '1.00'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
