#!/usr/bin/perl

use strict;
use warnings;
use MMM;
use MMM::MirrorTask;
use MMM::Utils;

my $mmm = MMM->new(
    configfile => $ENV{MMM_CONFIG},
    verbosity => 0,
);

if (($ARGV[0] || '') eq 'autoconf') {
    if ($mmm && $mmm->get_tasks_by_name($mmm->list_tasks)) {
        print "yes\n";
        exit(0);
    } else {
        print "No mmm found";
        exit(1);
    }
} elsif (($ARGV[0] || '') eq 'config') {
    print <<EOF;
graph_title Sync count done by mmm
graph_args --base 1000 --lower-limit 0
graph_vlabel Count
graph_category mmm
EOF

    foreach ($mmm->get_tasks_by_name($mmm->list_tasks)) {
        $_->is_disable and next;
        my $n = $_->name;
        $n =~ s:(/|-|\.):_:g;
        printf "%s.label %s\n", $n, $_->name;
        printf "%s.min 0\n", $n;
        printf "%s.type DERIVE\n", $n;
        printf "%s.cdef %s,3600,*\n", $n, $n;
    }
} else {
    foreach ($mmm->get_tasks_by_name($mmm->list_tasks)) {
        $_->is_disable and next;
        my $n = $_->name;
        $n =~ s:(/|-|\.):_:g;
        my %info = $_->state_info();
        printf("%s.value %d\n", $n, ($info{job}{processed_count} || 0));
    }
}

__END__
