---
abstract: 'Perl port of the termbox2 terminal library'
author:
  - 'J. Schneider'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  File::Temp: '0'
  Test::More: '1.302188'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Termbox-PP
no_index:
  directory:
    - t
    - inc
  package:
    - Termbox
recommends:
  Encode: '0'
  Getopt::Long: '0'
  List::Util: '0'
  Pod::Usage: '0'
  Time::HiRes: '0'
  Unicode::EastAsianWidth::Detect: '0'
  lib: '0'
requires:
  Carp: '0'
  Exporter: '0'
  IO::File: '0'
  Params::Check: '0'
  Scalar::Util: '0'
  Win32::API: '0.75'
  Win32::Console: '0.1'
  Win32::IPC: '1.11'
  Win32API::File: '0.1201'
  constant: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/brickpool/Termbox/issues
  repository: https://github.com/brickpool/Termbox.git
version: v0.5.1
x_homepage: http://brickpool.de
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
