#!usr/bin/perl;
use Terse::Helper;
Terse::Helper->new()->run(@ARGV);
__END__

=head1 NAME
  
terse - CLA for generating a Terse application skeleton.
  
=head1 USAGE

        lnation:High lnation$ terse --name Moon::Shine

	plackup -p 3000 -s Starman MoonShine.psgi

	visit http://localhost:3000/

	terse --name Sky # Generates an application skeleton
	terse --name Sky --model Sun # Generate an application model
	terse --name Sky --view Moon # Generate an application view
	terse --name Sky --controller Stars # Generate an application controller
	terse --name Sky --plugin Satellites # Generate an application plugin
  
=cut
