---
abstract: 'Implements application default credentials and project ID detection.'
author:
  - 'C.J. Collier <CJCOLLIER@CPAN.ORG>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0'
  Test::LWP::UserAgent: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Google-Auth
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: '0.48'
  JSON::MaybeXS: '0'
  Log::Any: '0'
  Moo: '0'
  URI: '0'
  perl: '5.006'
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
