Received: from VE1EUR03FT004.eop-EUR03.prod.protection.outlook.com
 (10.152.18.56) by VE1EUR03HT067.eop-EUR03.prod.protection.outlook.com
 (10.152.19.97) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256) id 15.20.1143.11; Sat, 15
 Sep 2018 01:38:07 +0000
Subject: Invoice 548_KUFN530642878
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="foo"

--foo
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

=0DInvoice details as follows.

NO_B_548_KUFN530642878_09_15_2018.doc



---
Aurora Dominguez
Aurora.Dominguez@exeltis.com


--foo
Content-Type: application/msword;
	name="NO_B_548_KUFN530642878_09_15_2018.doc"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="NO_B_548_KUFN530642878_09_15_2018.doc"

UkVEQUNURUQK

--foo--
