---
abstract: 'Store your sessions via DBIx::Class'
author:
  - 'Andrew Rodland <andrew@cleverdomain.org>'
build_requires:
  FindBin: '0'
  Test::More: '0'
  Test::Warn: '0.20'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-Session-Store-DBIC
no_index:
  directory:
    - t
requires:
  Carp: '0'
  Catalyst: '5.65'
  Catalyst::Exception: '0'
  Catalyst::Plugin::Session::Store::Delegate: '0.05'
  Class::Accessor::Fast: '0'
  DBIx::Class: '0.07000'
  MIME::Base64: '0'
  MRO::Compat: '0'
  Scalar::Util: '0'
  Storable: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Plugin-Session-Store-DBIC
  license: https://dev.perl.org/licenses/
  repository: https://github.com/perl-catalyst/Catalyst-Plugin-Session-Store-DBIC.git
version: '0.15'
x_generated_by_perl: v5.42.2
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
