#!/usr/bin/perl
# (c) 2001-2021 Vlado Keselj https://web.cs.dal.ca/~vlado vlado@dnlp.ca
#
# starfish - a script for using Starfish.pm
#
# The script runs the function starfish_cmd with a list of files and
# options given in the command line.
#
# For more documentation, please consult Text::Starfish.pm.

use Text::Starfish;
starfish_cmd(@ARGV);
