name = "WebService-Mailgun"
badges = ["github-actions"]
module_maker = "ModuleBuildTiny"
markdown_maker = "Pod::Markdown::Github"
[FileGatherer]
exclude_match = ["Dockerfile", "docker-compose.yml", ".pause", "CLAUDE.md", "^\\.github/"]
