--- #YAML:1.0
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
name: LTSV-LINQ
version: 1.07
abstract: LINQ-style query interface for LTSV files
author:
  - ina <ina@cpan.org>
license: perl
generated_by: pmake.bat
requires:
  perl: 5.00503
  strict: 1.01
  vars: 0
  warnings: 0
build_requires:
  Test: 1.122
minimum_perl_version: 5.00503
provides:
  LTSV::LINQ:
    file: lib/LTSV/LINQ.pm
    version: 1.07
  LTSV::LINQ::Ordered:
    file: lib/LTSV/LINQ.pm
    version: 1.07
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: https://github.com/ina-cpan/LTSV-LINQ/issues
  repository: https://github.com/ina-cpan/LTSV-LINQ
