# Amoebozoa
Amoebozoa	steelblue
# Opisthokonta
Opisthokonta	darkmagenta
# SAR
Stramenopiles	crimson
Alveolata	crimson
Rhizaria	crimson
# Archaeplastida
Viridiplantae	forestgreen
Rhodophyta	forestgreen
Glaucocystophyceae	forestgreen
# Excavata: Discoba
Jakobida	saddlebrown
Heterolobosea	saddlebrown
Euglenozoa	saddlebrown
# Excavata: Malawimonas
Malawimonadidae	saddlebrown
# Excavata: Metamonada
Fornicata	saddlebrown
Parabasalia	saddlebrown
Oxymonadida	saddlebrown
Trimastix	saddlebrown
