use ExtUtils::MakeMaker;
$Verbose = 1;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
WriteMakefile(
    'NAME'	=> 'XSTEST::RPCB1',
    'VERSION'	=> '49.1',
    'LIBS'	=> ['-lnsl'],   # e.g., '-lm' 
    'DEFINE'	=> '',     # e.g., '-DHAVE_SOMETHING' 
    'INC'	=> '',     # e.g., '-I/usr/include/other' 
    'XSPROTOARG'	=> '-noprototypes',
    'depend'	=> {'RPCB1.c' => 'Rpcb1.xsh'},
);
