use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007004
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( examples lib script t xt ) );
__DATA__
Alex
Andrew
Dagfinn
David
Dieter
Etheridge
Fowler
Glenn
Graham
Hans
Howarth
Ilmari
JAWNSY
Jesse
Jonathan
Karen
Knop
Kogman
Leermakers
Lowe
Luehrs
Lukas
Mai
Mannsåker
Marc
Mark
Mims
Pali
Paul
Pearcey
Peter
Rabbitson
Ricardo
Rudolf
Signes
Stosberg
Tiny
Try
Yates
Yu
Yuval
alex
anaxagoras
awalker
ayates
cebjyre
chromatic
cm
davidl
doy
ether
haarg
hdp
ilmari
irc
lib
mai
marc
mark
nothingmuch
pali
paul
ribasushi
rjbs
rudolf
walkeraj
יובל
קוג
