---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POE-Component-CPAN-SQLite-Info
no_index:
  directory:
    - t
    - inc
requires:
  CPAN::SQLite::Info: '0'
  Carp: '0'
  File::Spec: '0'
  LWP::UserAgent: '0'
  POE: '0'
  POE::Filter::Line: '0'
  POE::Filter::Reference: '0'
  POE::Wheel::Run: '0'
  Test::More: '0'
version: '0.12'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
