use inc::Module::Install::DSL 0.83;

all_from lib/Acme/Mom/Yours.pm
requires Angerwhale
requires App::CamelPKI
requires App::HistHub
requires Buscador
requires Catalyst::Authentication::Credential::OpenID
requires Catalyst::Example::InstantCRUD
requires CommitBit
requires Devel::ebug::HTTP
requires Foorum
requires Handel
requires Jifty
requires Jifty::Plugin::ModelMap
requires MojoMojo
requires Osgood::Server
requires Task::Catalyst::Tutorial
requires Task::CatInABox
requires Task::Email::PEP::All
requires Task::SOSA
requires Test::Apocalypse
requires Titanium
requires Padre
requires Parley
requires Pod::Browser
requires Reaction
