---
abstract: 'INI file reader with variable references and function calls'
author:
  - 'Abdul al Hazred <451@gmx.eu>'
build_requires:
  Config: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  TAP::Harness: '3.26'
  Test::Exception: '0.36'
  Test::More: '0.98'
  Test::Simple: '0.98'
  Test::Warn: '0.37'
  constant: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-INI-RefVars
no_index:
  directory:
    - t
    - inc
provides:
  Config::INI::RefVars:
    file: lib/Config/INI/RefVars.pm
    version: '1.03'
requires:
  Carp: '0'
  Config: '0'
  Cwd: '0'
  File::Basename: '0'
  File::Spec::Functions: '0'
  constant: '0'
  feature: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  repository: https://github.com/AAHAZRED/perl-Config-INI-RefVars.git
version: '1.03'
x_bugtracker:
  web: https://github.com/AAHAZRED/perl-Config-INI-RefVars/issues
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
