---
abstract: 'YAMLScript shared library'
author:
  - 'Ingy dot Net <ingy@ingy.net>'
build_requires:
  Alien::Build::MM: '0.25'
  Alien::Build::Plugin::Download::Negotiate: '1.30'
  Config: '0'
  HTML::LinkExtor: '0'
  HTTP::Tiny: '0.044'
  IO::Socket::SSL: '1.56'
  Mozilla::CA: '0'
  Net::SSLeay: '1.49'
  Test2::V0: '0.000159'
  Test::Alien: '2.80'
  URI: '0'
  URI::Escape: '0'
configure_requires:
  Alien::Build: '2.80'
  Alien::Build::MM: '2.80'
  Alien::Build::Plugin::Download::GitHub: '0.10'
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-YAMLScript
no_index:
  directory:
    - t
    - inc
requires:
  Alien::Base: '0'
  Alien::Build: '0.25'
  Cpanel::JSON::XS: '4.37'
  Mozilla::CA: '0'
  perl: '5.016'
resources:
  bugtracker: https://github.com/yaml/yamlscript/issues
  homepage: https://yamlscript.org
  repository: https://github.com/yaml/yamlscript.git
version: v0.2.25
x_alienfile:
  generated_by: 'Alien::Build::MM version 2.84'
  requires:
    share:
      Alien::Build::Plugin::Download::Negotiate: '1.30'
      Config: '0'
      HTML::LinkExtor: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      Mozilla::CA: '0'
      Net::SSLeay: '1.49'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
