---
abstract: 'turn file changes into Mojo events'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Copy: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  Mojo::Promise: '0'
  Scalar::Util: '0'
  Test2::IPC: '0'
  Test2::V0: '0'
  Test::More: '0'
  experimental: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-File-ChangeNotify
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: '5'
  File::ChangeNotify: '0'
  Mojo::Base: '0'
  Mojo::EventEmitter: '0'
  Mojo::IOLoop::Subprocess: '0'
  PerlX::Maybe: '0'
  Scalar::Util: '0'
  experimental: '0'
  feature: '0'
  perl: '5.020'
resources:
  bugtracker: https://github.com/Corion/Mojo-File-ChangeNotify/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/Mojo-File-ChangeNotify.git
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
