---
abstract: 'Get basic statistical functions, like in R, but with Perl using XS for performance'
author:
  - 'David E. Condon <dec986@gmail.com>'
build_requires:
  Test::Exception: '0'
  Test::LeakTrace: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.48'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Stats-LikeR
requires:
  Devel::Confess: '0'
  Scalar::Util: '1.22'
  autodie: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/hhg7/stats/issues
  homepage: https://metacpan.org/dist/stats
  repository: https://github.com/hhg7/stats.git
version: '0.16'
x_generated_by_perl: v5.42.2
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
