---
abstract: 'SQLite storage backend for Net::Blossom::Server'
author:
  - 'Net::Blossom contributors'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  strictures: '2'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Blossom-Server-Backend-SQLite
no_index:
  directory:
    - t
    - inc
requires:
  Class::Tiny: '1.001'
  DBD::SQLite: '0'
  DBI: '0'
  Net::Blossom: '0.001001'
  Net::Blossom::Server: '0.001003'
  perl: '5.016'
  strictures: '2'
resources:
  bugtracker: https://github.com/NicholasBHubbard/Net-Blossom/issues
  homepage: https://github.com/NicholasBHubbard/Net-Blossom
  repository: https://github.com/NicholasBHubbard/Net-Blossom.git
version: '0.001003'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
