;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.002

name=App-XWindowManagerUtils

[GenPericmdScript / GenPericmdScript list-xwm-windows]
url=/App/XWindowManagerUtils/list_xwm_windows
enable_log=1
read_config=0
read_env=0

[GenPericmdScript / GenPericmdScript get-xwm-window-kde-activity]
url=/App/XWindowManagerUtils/get_xwm_window_kde_activity
enable_log=1
read_config=0
read_env=0

[InsertExecsList]

[@Author::PERLANCAR]
:version=0.610

[Prereqs / TestRequires]
;Test::More=0.98

[Prereqs]
perl=5.010001
strict=0
warnings=0
Exporter=5.57
IPC::System::Options=0.339
Log::ger=0.038

[Prereqs / DevelopX_spec]
-phase=develop
-relationship=x_spec
Rinci=1.1.102
