---
abstract: 'Async MariaDB/MySQL client using libmariadb and EV'
author:
  - vividsnow
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.98'
configure_requires:
  Alien::MariaDB: '0'
  EV::MakeMaker: '0'
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: EV-MariaDB
no_index:
  directory:
    - t
    - inc
provides:
  EV::MariaDB:
    file: lib/EV/MariaDB.pm
    version: '0.01'
requires:
  Alien::MariaDB: '0'
  EV: '4.11'
  perl: '5.012'
resources:
  bugtracker: https://github.com/vividsnow/perl5-ev-mariadb/issues
  repository: https://github.com/vividsnow/perl5-ev-mariadb.git
version: '0.02'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
