openapi: "3.0.0"
info:
  description: "This is a sample configuration"
  version: "1"
  title: "Example Config"
  termsOfService: "http://toterms/"
  contact:
    email: "developer@example.org"
  license:
    name: "Your-License"
    url: "http://license-link/"
tags:
- name: "example"
  description: "Some example"
  externalDocs:
    description: "Find out more"
    url: "http://example"
servers:
  - url: '/v1/'
  - url: 'http://localhost:8089/v1/'
paths:
  '/hcheck':
    get:
      description: 'Returns a 200 response and Perl package name as text when the service is available'
      responses:
        200:
          description: 'alive'
          content:
            'text/plain':
              example: "Service-name: async-microservice-time\nAPI-version: 1"
        405:
          $ref: '#/components/responses/Method-Not-Allowed'
components:
  responses:
    'Method-Not-Allowed':
      description: 'Method not allowed for this route.'
      headers:
        Allow:
          description: 'Comma-separated list of allowed HTTP methods for the route.'
          schema:
            type: string
            example: 'GET'
      content:
        'text/plain':
          example: 'method not allowed'
        'application/json':
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  err_status:
                    type: integer
                    example: 405
                  err_msg:
                    type: string
                    example: 'method not allowed'
externalDocs:
  description: "Find out more about Async::Microservice"
  url: "https://metacpan.org/pod/Async::Microservice"
