---
abstract: 'Parse and format datetimes with strptime patterns, returning DateTime::Lite objects'
author:
  - 'Jacques Deguest (jack@deguest.jp)'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '1.302162'
  Test::Pod: '1.52'
  lib: '0'
  open: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DateTime-Format-Lite
no_index:
  directory:
    - t
    - inc
    - t
    - inc
requires:
  DateTime::Lite: v0.5.0
  DateTime::Locale::FromCLDR: v0.8.2
  Exporter: '0'
  Locale::Unicode: v0.4.0
  POSIX: '0'
  Scalar::Util: '0'
  Wanted: v0.1.0
  perl: '5.010001'
  strict: '0'
  vars: '0'
  warnings: '0'
  warnings::register: '0'
resources:
  bugtracker: https://gitlab.com/jackdeguest/DateTime-Format-Lite/issues
  repository: https://gitlab.com/jackdeguest/DateTime-Format-Lite
version: v0.1.0
x_contributors: []
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
