---
abstract: 'Role for Class::JSON_Object'
author:
  - 'Johan Vromans <jv@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Object::Pad: '0.814'
  Test2::Suite: '0'
configure_requires:
  ExtUtils::MakeMaker: '7.54'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-JSON_Object
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: '7.54'
  Object::Pad: '0.814'
  Test2::Suite: '0'
  perl: '5.026000'
resources:
  license: https://dev.perl.org/licenses/
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
