;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.002

name=Games-Cards-Troika-Util

[GenPericmdScript / GenPericmdScript troika-list-cards]
url=/Games/Cards/Troika/Util/troika_list_cards
read_config=0
read_env=0
use_utf8=1
enable_log=1

[GenPericmdScript / GenPericmdScript troika-list-cards-shuffled]
url=/Games/Cards/Troika/Util/troika_list_cards_shuffled
read_config=0
read_env=0
use_utf8=1
enable_log=1

[InsertExecsList]

[@Author::PERLANCAR]
:version=0.610

[Prereqs / TestRequires]
;Test::More=0.98

[Prereqs]
perl=5.010001
strict=0
warnings=0
List::Util=1.54
Perinci::Sub::Util=0.472
TableData::Games::Cards::Troika=0

[Prereqs / DevelopX_spec]
-phase=develop
-relationship=x_spec
Rinci=1.1.102

