---
abstract: 'Move forward and backward in the drand48/rand() sequence'
author:
  - 'Stig Palmquist <stig@stig.io>'
build_requires:
  Test::More: '0.88'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.051, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-Rand48-Cursor
provides:
  Math::Rand48::Cursor:
    file: lib/Math/Rand48/Cursor.pm
    version: '0.001'
requires:
  Math::BigFloat: '0'
  Math::BigInt: '0'
  perl: '5.034'
version: '0.001'
x_generated_by_perl: v5.42.2
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
