=pod

=encoding utf8

=head1 NAME

L<Novel::Robot::Browser> 

get/post url, return unicode content, auto detect CJK charset

自动化获取网页内容，并解码为unicode，主要是自动检测网页的中文字符集

=head1 FUNCTION

=head2 request_url
  
    my $agent = 'default'; # default, firefox, chrome
    my $browser = Novel::Robot::Browser->new( agent => $agent );
	
=head3  get

    my $url = 'http://www.jjwxc.net/onebook.php?novelid=14838';
    my $content_get_ref = $browser->request_url($url);

=head3  post

    my $form_url = 'http://www.jjwxc.net/search.php';
    my $post_data = {
		'key1' => 'value1', 
		'key2' => 'value2', 
    };
    my $content_post_ref = $browser->request_url($form_url, $post_data);


=head2 read_moz_cookie
    
    #firefox sqlite3 : cookies.sqlite
    $browser->read_moz_cookie($mozilla_cookies_sqlite_file, $domain);

    #netscape http cookie file: cookie.txt
    #same as: curl -b cookie.txt -c cookie.txt http://www.xxx.com
    $browser->read_moz_cookie($netscape_http_cookie_file, $domain);

    #cookie string: name1=value1; name2=value2
    #same as: curl -b "name1=value1; name2=value2" http://www.xxx.com
    $browser->read_moz_cookie($cookie_string, $domain);

=cut
