---
abstract: 'Creates HTML based photo albums'
author:
  - 'Johan Vromans (jvromans@squirrel.nl)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150013'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Album
no_index:
  directory:
    - t
    - inc
  file:
    - lib/Album/Tutorial.pm
requires:
  File::Spec: '0'
  Getopt::Long: '2.13'
  Image::Info: '1.16'
resources:
  license: https://dev.perl.org/licenses/
version: v1.901.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
