---
abstract: 'Enforce protected subroutine access (Java/C++ semantics)'
author:
  - 'Nigel Horne <njh@nigelhorne.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  IPC::System::Simple: '0'
  Test::DescribeMe: '0'
  Test::Memory::Cycle: '0'
  Test::Most: '0'
  Test::Needs: '0'
  Test::Returns: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150015'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sub-Protected
no_index:
  directory:
    - t
    - inc
provides:
  Sub::Protected:
    file: lib/Sub/Protected.pm
    version: '0.03'
requires:
  Attribute::Handlers: '0'
  B::Hooks::EndOfScope: '0'
  Carp: '0'
  Params::Get: '0'
  Params::Validate::Strict: '0.33'
  Readonly: '0'
  Return::Set: '0'
  Sub::Identify: '0'
  perl: '5.010'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Sub-Protected
  homepage: https://metacpan.org/pod/Sub::Protected
  repository: git://github.com/nigelhorne/Sub-Protected.git
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
