# .licensizer.yml
author: |
    Please contribute patches to the project on Github:
    
        https://github.com/mschilli/log4perl
    
    Please submit bug reports or requests for enhancements on
    the project's Github issues above.
    
    Authors (please contact them via Github, not directly):
    Mike Schilli <m@perlmeister.com>,
    Kevin Goess <cpan@goess.org>
    
    Contributors (in alphabetical order):
    Ateeq Altaf, Cory Bennett, Jens Berthold, Jeremy Bopp, Tony Cook,
    Hutton Davidson, Chris R. Donnelly, Matisse Enzer, Hugh Esco,
    James FitzGibbon, Anthony Foiani, Carl Franks, Dennis Gregorovic,
    Andy Grundman, Paul Harrington, Alexander Hartmaier, David Hull,
    Ed J, Robert Jacobson, Jason Kohles, William E Little Jr,
    Jeff Macdonald, Markus Peter, Nicolas R, Peter Rabbitson,
    Brett Rann, Erik Selberg, Aaron Straup Cope, Lars Thegler,
    David Viner, Mike Whitaker, Mac Yang.

license: |
  Copyright 2002-2026 by Mike Schilli E<lt>m@perlmeister.comE<gt>
  and Kevin Goess E<lt>cpan@goess.orgE<gt>.

  This library is free software; you can redistribute it and/or modify
  it under the same terms as Perl itself.
