use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007004
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( examples lib script t xt ) );
__DATA__
Alexandr
Ciornii
Etheridge
Florian
Hooks
Kang
Karen
Liu
Parser
Pit
Ragwitz
Vincent
Zefram
alexchorny
ether
gugod
irc
lib
perl
rafl
zefram
