=head1 NAME

Evo::Immune - Perl extension for GA for the biological immune system 

=head1 SYNOPSIS

  use Evo::Immune;

=head1 DESCRIPTION

genetic algorithm for the immune system

=head2 EXPORT

=head1 SEE ALSO

=head1 AUTHOR

koboldwiz, E<lt>koboldwiz@yahoo.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2021 by koboldwiz 

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.28.2 or,
at your option, any later version of Perl 5 you may have available.


=cut

