---
abstract: 'Composable ORM builder.'
author:
  - 'Chad Granum <exodist@cpan.org>'
build_requires:
  Hash::Merge: '0.12'
  Parallel::Runner: '0.013'
  Test2::Tools::QuickDB: '0.000051'
  Test2::Util: '0.000060'
  Test2::V0: '0.000060'
  ok: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-QuickORM
requires:
  Atomic::Pipe: '0.029'
  Carp: '0'
  Compress::Zstd: '0.06'
  Cpanel::JSON::XS: '3.0224'
  DBD::SQLite: '1.64'
  DBI: '1.628'
  Data::Dumper: '2.171'
  DateTime: '0'
  DateTime::Format::SQLite: '0'
  Importer: '0.025'
  List::Util: '1.56'
  Module::Pluggable: '5.1'
  Object::HashBase: '0.016'
  POSIX: '0'
  Role::Tiny: '2.000003'
  Role::Tiny::With: '2.000003'
  SQL::Abstract: '2.000001'
  Scalar::Util: '1.56'
  Scope::Guard: '0.20'
  Storable: '0'
  Sub::Util: '1.40'
  Time::HiRes: '0'
  UUID: '0.36'
  constant: '0'
  overload: '0'
  parent: '0'
  perl: '5.014000'
resources:
  bugtracker: https://github.com/exodist/DBIx-QuickORM/issues
  repository: https://github.com/exodist/DBIx-QuickORM/
version: '0.000025'
x_generated_by_perl: v5.42.2
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
