---
abstract: 'Require explicit return in eval blocks'
author:
  - 'Blaine Motsinger <blaine@renderorange.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Perl::Critic: '1.126'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-Policy-ErrorHandling-RequireReturnFromEval
no_index:
  directory:
    - t
    - inc
requires:
  Perl::Critic: '1.126'
  Perl::Critic::Utils: '0'
  parent: '0'
  perl: '5.010001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/renderorange/perl-critic-policy-errorhandling-requirereturnfromeval/issues
  repository: https://github.com/renderorange/perl-critic-policy-errorhandling-requirereturnfromeval.git
version: '1.00'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
