name    = Dancer2-Serializer-Dumper
author  = Dancer Core Developers
license = Perl_5
copyright_holder = Alexis Sukrieh
copyright_year   = 2021

[@Basic]

; versioning stack.  Note that next version is determined automatically unless
; you set V= when running - do that for minor/major bumps, not patch releases.
[Git::NextVersion]   ; decides the version (honours V)
[OurPkgVersion]      ; stamps it into # VERSION in your modules
[NextRelease]        ; stamps it + date into Changes, manages {{$NEXT}}
[Git::Tag]
[Git::Commit]        ; sweeps up the post-release Changes rewrite

filename = Changes

[AutoPrereqs]

[Prereqs]
Moo = 0
Dancer2 = 0

[MetaResources]
homepage        = http://perldancer.org/
bugtracker.web  = https://github.com/PerlDancer/Dancer2-Serializer-Dumper/issues
repository.url  = git://github.com/PerlDancer/Dancer2-Serializer-Dumper.git
repository.web  = https://github.com/PerlDancer/Dancer2-Serializer-Dumper
repository.type = git
x_IRC           = irc://irc.perl.org/#dancer
x_WebIRC        = https://chat.mibbit.com/#dancer@irc.perl.org

[ReadmeAnyFromPod / MarkdownInRoot]
filename = README.mkdn
