---
abstract: 'Build and install Net-SNMP'
author:
  - 'Eric A. Miller <emiller AT cpan DOT org>'
build_requires:
  Alien::Build: '2.84'
  Alien::Build::MM: '0.25'
  Archive::Tar: '0'
  Config: '0'
  Devel::FindPerl: '0'
  HTTP::Tiny: '0.044'
  IO::Socket::SSL: '1.56'
  IO::Zlib: '0'
  Mozilla::CA: '0'
  Net::SSLeay: '1.49'
  Test::Alien: '2.84'
  Test::More: '0.94'
  URI: '0'
configure_requires:
  Alien::Build: '2.84'
  Alien::Build::MM: '2.84'
  Alien::Build::Plugin::Digest::Negotiate: '0'
  ExtUtils::MakeMaker: '7.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-SNMP
no_index:
  directory:
    - t
    - inc
requires:
  Alien::Base: '2.84'
  Alien::Build: '0.25'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/ollyg/Alien-SNMP/issues
  repository: https://github.com/ollyg/Alien-SNMP.git
version: '4.0509050200'
x_alienfile:
  generated_by: 'Alien::Build::MM version 2.84'
  requires:
    share:
      Archive::Tar: '0'
      Config: '0'
      Devel::FindPerl: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      IO::Zlib: '0'
      Mozilla::CA: '0'
      Net::SSLeay: '1.49'
      URI: '0'
    system: {}
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
