---
abstract: 'Efficient web framework built with modern core classes'
author:
  - 'Cesar Tessarin, <cesar@tessarin.com.br>'
build_requires:
  ExtUtils::MakeMaker: '0'
  HTTP::Request::Common: '6.0'
configure_requires:
  ExtUtils::MakeMaker: '7'
  File::ShareDir::Install: '0.14'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Minima
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: '2.1'
  File::Share: '0.27'
  Hash::MultiValue: '0.16'
  JSON: '4.10'
  Path::Tiny: '0.142'
  Plack: '1.0050'
  Router::Simple: '0.17'
  Template: '3.100'
  YAML::XS: v0.904.0
  perl: '5.040000'
resources:
  bugtracker: https://github.com/tessarin/Minima/issues
  repository: https://github.com/tessarin/Minima
version: v0.8.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
