---
abstract: 'Program in YAML - Code is Data'
author:
  - 'Ingy dot Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0.000159'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: YAMLScript
no_index:
  directory:
    - t
    - inc
requires:
  Alien::YAMLScript: v0.2.12
  Cpanel::JSON::XS: '4.37'
  FFI::CheckLib: '0.31'
  FFI::Platypus: '2.08'
  perl: '5.016'
resources:
  bugtracker: https://github.com/yaml/yamlscript/issues
  homepage: https://yamlscript.org
  repository: https://github.com/yaml/yamlscript.git
version: v0.2.25
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
