=pod

=encoding utf8

=head1 Net-BaruwaAPI

Perl bindings for the Baruwa REST API

=for HTML <a href="https://travis-ci.org/akissa/Net-BaruwaAPI"><img src="https://travis-ci.org/akissa/Net-BaruwaAPI.svg?branch=master" /></a>

=for HTML <a href="https://codecov.io/gh/akissa/Net-BaruwaAPI"><img src="https://codecov.io/gh/akissa/Net-BaruwaAPI/branch/master/graph/badge.svg" alt="Coverage via Codecov" /></a>

=for HTML <a href="https://www.mozilla.org/MPL/2.0/"><img src="https://img.shields.io/badge/license-MPLv2-blue.svg?style=flat-square" /></a>


=head2 Installation

You can install this module with a CPAN client, which will resolve
and install the dependencies:

	cpan Net::BaruwaAPI

To manually install this module, run the following commands:

	perl Build.PL
	./Build
	./Build test
	./Build install

=head2 Support and Documentation

After installing, you can find documentation for this module with the
perldoc command.

    perldoc Net::BaruwaAPI

You can also look for information at:

    RT, CPAN's request tracker (report bugs here)
        http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-BaruwaAPI

    AnnoCPAN, Annotated CPAN documentation
        http://annocpan.org/dist/Net-BaruwaAPI

    CPAN Ratings
        http://cpanratings.perl.org/d/Net-BaruwaAPI

    Search CPAN
        http://search.cpan.org/dist/Net-BaruwaAPI/

=head2 Contributing

=over 4

=item * Fork it (https://github.com/akissa/Net-BaruwaAPI/fork)

=item * Create your feature branch (`git checkout -b my-new-feature`)

=item * Commit your changes (`git commit -am 'Add some feature'`)

=item * Push to the branch (`git push origin my-new-feature`)

=item * Create new Pull Request

=back


=head2 License and Copyright

Copyright (C) 2015-2019 Andrew Colin Kissa

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at L<http://mozilla.org/MPL/2.0/>.

=cut
