---
abstract: 'common documentation publication operations'
author:
  - 'Andrew Speer <andrew.speer@isolutions.com.au>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  version: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Markdown-Publish
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: '0'
  Exporter: '0'
  File::Copy: '0'
  File::Find: '0'
  File::Path: '2.07'
  File::Spec: '0'
  File::Temp: '0'
  Getopt::Long: '0'
  IPC::Run3: '0'
  JSON::PP: '0'
  perl: '5.008'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/aspeer/pm-Markdown-Publish/issues
  homepage: https://github.com/aspeer/pm-Markdown-Publish
  repository: https://github.com/aspeer/pm-Markdown-Publish.git
version: '1.003'
x_authority: cpan:ASPEER
x_documentation:
  publish:
    module: mkdocs
    name: Markdown::Publish
    sources:
      - doc
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
