---
abstract: 'Submit a project to Cavil for a legal review and gate CI on the result'
author:
  - 'Sebastian Riedel <sriedel@suse.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '7.12'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cavil-CLI
no_index:
  directory:
    - t
    - inc
requires:
  IO::Socket::SSL: '2.009'
  Mojolicious: '9.34'
  perl: '5.020'
resources:
  bugtracker: https://github.com/openSUSE/cavil-cli/issues
  license: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
  repository: https://github.com/openSUSE/cavil-cli.git
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
