---
abstract: 'MIDI bytestream decoding and encoding'
author:
  - 'John Barrett <john@jbrt.org>'
build_requires:
  FindBin: '0'
  JSON::MaybeXS: '0'
  JSON::PP: '0'
  Test2::V0: '0'
  Test::Lib: '0'
  Test::Time::HiRes: '0'
  perl: v5.26.0
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: v5.26.0
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MIDI-Stream
no_index:
  directory:
    - t
    - xt
provides:
  MIDI::Stream:
    file: lib/MIDI/Stream.pm
    version: '0.006'
  MIDI::Stream::Decoder:
    file: lib/MIDI/Stream/Decoder.pm
    version: '0.006'
  MIDI::Stream::Encoder:
    file: lib/MIDI/Stream/Encoder.pm
    version: '0.006'
  MIDI::Stream::Event:
    file: lib/MIDI/Stream/Event.pm
    version: '0.006'
  MIDI::Stream::Event::AfterTouch:
    file: lib/MIDI/Stream/Event/AfterTouch.pm
    version: '0.006'
  MIDI::Stream::Event::Channel:
    file: lib/MIDI/Stream/Event/Channel.pm
    version: '0.006'
  MIDI::Stream::Event::ControlChange:
    file: lib/MIDI/Stream/Event/ControlChange.pm
    version: '0.006'
  MIDI::Stream::Event::Note:
    file: lib/MIDI/Stream/Event/Note.pm
    version: '0.006'
  MIDI::Stream::Event::PitchBend:
    file: lib/MIDI/Stream/Event/PitchBend.pm
    version: '0.006'
  MIDI::Stream::Event::PolyTouch:
    file: lib/MIDI/Stream/Event/PolyTouch.pm
    version: '0.006'
  MIDI::Stream::Event::ProgramChange:
    file: lib/MIDI/Stream/Event/ProgramChange.pm
    version: '0.006'
  MIDI::Stream::Event::SongPosition:
    file: lib/MIDI/Stream/Event/SongPosition.pm
    version: '0.006'
  MIDI::Stream::Event::SongSelect:
    file: lib/MIDI/Stream/Event/SongSelect.pm
    version: '0.006'
  MIDI::Stream::Event::SysEx:
    file: lib/MIDI/Stream/Event/SysEx.pm
    version: '0.006'
  MIDI::Stream::Event::TimeCode:
    file: lib/MIDI/Stream/Event/TimeCode.pm
    version: '0.006'
  MIDI::Stream::FIFO:
    file: lib/MIDI/Stream/FIFO.pm
    version: '0.006'
  MIDI::Stream::Tables:
    file: lib/MIDI/Stream/Tables.pm
    version: '0.006'
requires:
  Feature::Compat::Class: '0.08'
  List::Util: '0'
  Time::HiRes: '0'
  experimental: '0'
  parent: '0'
  perl: v5.26.0
resources:
  bugtracker: https://codeberg.org/jbarrett/MIDI-Stream/issues
  homepage: https://codeberg.org/jbarrett/MIDI-Stream/
  repository: https://codeberg.org/jbarrett/MIDI-Stream.git
version: '0.006'
x_generated_by_perl: v5.44.0
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
