---
abstract: 'A fast PSGI/HTTP server for Perl based on EV/libev'
author:
  - 'Jeremy Stashewsky <stash@cpan.org>'
build_requires:
  AnyEvent: '5.261'
  Test::Fatal: '0.003'
  Test::More: '0.94'
configure_requires:
  EV: '4'
  EV::MakeMaker: '0'
  ExtUtils::CBuilder: '0'
  ExtUtils::MakeMaker: '6.51'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150015'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Feersum
no_index:
  directory:
    - t
    - inc
    - eg
    - picohttpparser-git
    - picotls-git
provides:
  Feersum:
    file: lib/Feersum.pm
    version: '1.507'
  Feersum::Connection:
    file: lib/Feersum/Connection.pm
  Feersum::Connection::Handle:
    file: lib/Feersum/Connection/Handle.pm
  Feersum::Connection::Reader:
    file: lib/Feersum/Connection/Handle.pm
  Feersum::Connection::Writer:
    file: lib/Feersum/Connection/Handle.pm
  Feersum::Runner:
    file: lib/Feersum/Runner.pm
  Plack::Handler::Feersum:
    file: lib/Plack/Handler/Feersum.pm
recommends:
  Alien::OpenSSL: '0'
  Alien::nghttp2: '0'
  Plack: '0.995'
requires:
  EV: '4'
  File::Spec: '0'
  Guard: '1.012'
  List::Util: '1.33'
  Scalar::Util: '1.19'
  perl: '5.014'
resources:
  bugtracker: https://github.com/stash/Feersum/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/vividsnow/Feersum.git
version: '1.507'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
