;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.002

name=App-TextTemplatePermuteUtils

[GenPericmdScript / GenPericmdScript template-permute]
url=/App/TextTemplatePermuteUtils/template_permute

[InsertExecsList]

[@Author::PERLANCAR]
:version=0.610

[Prereqs / TestRequires]
;Test::More=0.98

[Prereqs]
perl=5.010001
strict=0
warnings=0
Clipboard::Any=0.011
List::Util=1.54
Text::Template::Permute=0

[Prereqs / DevelopX_spec]
-phase=develop
-relationship=x_spec
Rinci=1.1.102

