use strict;
use warnings;

# this test was generated with Dist::Zilla::Plugin::Test::EOL 0.19

use Test::More 0.88;
use Test::EOL;

my @files = (
    'lib/Test/YAFT.pm',
    'lib/Test/YAFT.pod',
    'lib/Test/YAFT/Argument.pm',
    'lib/Test/YAFT/Argument/Arrange.pm',
    'lib/Test/YAFT/Argument/Array.pm',
    'lib/Test/YAFT/Argument/Got.pm',
    'lib/Test/YAFT/Argument/Scalar.pm',
    'lib/Test/YAFT/Attributes.pm',
    'lib/Test/YAFT/Cmp.pm',
    'lib/Test/YAFT/Cmp/Compare.pm',
    'lib/Test/YAFT/Cmp/Complement.pm',
    'lib/Test/YAFT/Dumper.pm',
    'lib/Test/YAFT/Introduction.pod',
    'lib/Test/YAFT/Test/Deep.pod',
    'lib/Test/YAFT/Test/Exception.pod',
    'lib/Test/YAFT/Test/More.pod',
    'lib/Test/YAFT/Test/Spec.pod',
    'lib/Test/YAFT/Test/Warnings.pod',
    't/act.t',
    't/arrange.t',
    't/assumptions-with-got.t',
    't/assumptions.t',
    't/bail-out.t',
    't/cmp-details.t',
    't/cmp-overload.t',
    't/deep-diag.t',
    't/diag.t',
    't/done-testing.t',
    't/eq-deeply.t',
    't/examples/test-rest-countries/resource-countries.t',
    't/examples/test-rest-countries/test-helper.pl',
    't/examples/test-type-tiny-constraint/constraint-test.t',
    't/examples/test-type-tiny-constraint/test-helper.pl',
    't/expect-all.t',
    't/expect-any.t',
    't/expect-array-each.t',
    't/expect-array-elements-only.t',
    't/expect-array-length-only.t',
    't/expect-array-length.t',
    't/expect-array.t',
    't/expect-bag.t',
    't/expect-blessed.t',
    't/expect-bool.t',
    't/expect-code.t',
    't/expect-compare.t',
    't/expect-complement.t',
    't/expect-false.t',
    't/expect-hash-each.t',
    't/expect-hash-keys-only.t',
    't/expect-hash-keys.t',
    't/expect-hash.t',
    't/expect-isa.t',
    't/expect-listmethods.t',
    't/expect-methods.t',
    't/expect-no-class.t',
    't/expect-none-of.t',
    't/expect-none.t',
    't/expect-num.t',
    't/expect-obj-isa.t',
    't/expect-re.t',
    't/expect-ref-type.t',
    't/expect-regexp-matches.t',
    't/expect-regexp-only.t',
    't/expect-regexpref-only.t',
    't/expect-regexpref.t',
    't/expect-scalarref-only.t',
    't/expect-scalarref.t',
    't/expect-set.t',
    't/expect-shallow.t',
    't/expect-str.t',
    't/expect-subbag-of.t',
    't/expect-subbag.t',
    't/expect-subhash-of.t',
    't/expect-subhash.t',
    't/expect-subset-of.t',
    't/expect-subset.t',
    't/expect-superbag-of.t',
    't/expect-superbag.t',
    't/expect-superhash-of.t',
    't/expect-superhash.t',
    't/expect-superset-of.t',
    't/expect-superset.t',
    't/expect-true.t',
    't/expect-use-class.t',
    't/expect-value.t',
    't/explain.t',
    't/fail.t',
    't/had-no-warnings.t',
    't/ignore.t',
    't/internals-build-got.t',
    't/nok.t',
    't/note.t',
    't/ok.t',
    't/pass.t',
    't/plan.t',
    't/skip.t',
    't/subtest.t',
    't/test-deep-cmp.t',
    't/test-frame.t',
    't/test-helper.pl',
    't/todo-skip.t'
);

eol_unix_ok($_, { trailing_whitespace => 1 }) foreach @files;
done_testing;
