---
abstract: 'Dedicated user data management system with multiple storage backends'
author:
  - 'Bruce Van Allen <bva@cruzio.com>'
build_requires:
  Capture::Tiny: '0'
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Concierge-Users
no_index:
  directory:
    - t
    - inc
provides:
  Concierge::Users:
    file: lib/Concierge/Users.pm
    version: v0.8.2
  Concierge::Users::Database:
    file: lib/Concierge/Users/Database.pm
    version: v0.8.2
  Concierge::Users::File:
    file: lib/Concierge/Users/File.pm
    version: v0.8.2
  Concierge::Users::Meta:
    file: lib/Concierge/Users/Meta.pm
    version: v0.8.2
  Concierge::Users::YAML:
    file: lib/Concierge/Users/YAML.pm
    version: v0.8.2
requires:
  Carp: '0'
  DBD::SQLite: '0'
  DBI: '0'
  File::Path: '0'
  File::Spec: '0'
  JSON::PP: '0'
  Text::CSV: '0'
  YAML::Tiny: '0'
  perl: '5.036'
resources:
  bugtracker: https://github.com/bwva/Concierge-Users/issues
  repository: https://github.com/bwva/Concierge-Users.git
version: v0.8.3
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
