package Daje::Controller::Authorities::Super::AuthoritiesLicenseFunctionList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Authorities::Super::AuthoritiesLicenseFunctionList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Authorities::Super::vAuthoritiesLicenseFunction##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Authorities::Super::AuthoritiesLicenseFunction is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-03-01 05:33:54.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-03-01 05:33:54 -->

our $VERSION = '0.01';

sub load_all_authorities_license_function($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesLicenseFunctionList::load_all_authorities_license_function ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities_license_function_list->load_all_authorities_license_function_p()->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesLicenseFunctionList::load_all_authorities_license_function ' . $err);
        $self->render
    });
}
sub load_list_authorities_license_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesLicenseFunctionList::load_listauthorities_license_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('authorities_license_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities__list->authorities_license_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesLicenseFunction::load_authorities_license_fkey ' . $err);
        $self->render
    });
}sub load_list_authorities_function_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesLicenseFunctionList::load_listauthorities_function_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('authorities_function_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities__list->authorities_function_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesLicenseFunction::load_authorities_function_fkey ' . $err);
        $self->render
    });
}
1;

