=head1 NAME

Tk::ForDummies::Graph::Splines - DEPRECATED : now use Tk::Chart.

=head1 SYNOPSIS

DEPRECATED : please does not use this module, but use now L<Tk::Chart>.

=head1 DESCRIPTION

You have to use B<Tk::ForDummies::Graph::Lines> module and use 
B<-spline> and B<-bezier> options.

See L<Tk::ForDummies::Graph::Lines/"Options for all lines graph"> and 
L<Tk::ForDummies::Graph::Lines/"Options for spline lines graph">


B<Be careful>, a BE<eacute>zier curve (L<http://en.wikipedia.org/wiki/Bezier_curve>) does not touch all points of dataset, just the extremity points.

But, B<Tk::ForDummies::Graph::Lines> allow you to create a BE<eacute>zier curve crossing by all points (-bezier => 1 and -spline => 1).


=head1 EXAMPLES

  #!/usr/bin/perl
  use strict;
  use warnings;
  use Tk;
  use Tk::ForDummies::Graph::Lines;

  my $mw = new MainWindow(
    -title      => 'bezier curve examples',
    -background => 'white',
  );
  my $GraphDummies = $mw->Lines(
    -title      => 'bezier curves',
    -xlabel     => 'X Label',
    -ylabel     => 'Y Label',
    -background => 'snow',
    -spline => 1,
    -bezier => 1,     
    -linewidth  => 2,
  )->pack(qw / -fill both -expand 1 /);
  
  my @data = (
    [ '1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th' ],
    [ 10,    30,    20,    30,    5,     41,    1,     23 ],
    [ 10,    5,     10,    0,     17,    2,     40,    23 ],
    [ 20,    10,    12,    20,    30,    10,    35,    12 ],
  
  );
 
  # Add a legend to the graph
  my @Legends = ( 'legend 1', 'legend 2', 'legend 3' );
  $GraphDummies->set_legend(
    -title       => 'Title legend',
    -data        => \@Legends,
    -titlecolors => 'blue',
  );

  # Add help identification
  $GraphDummies->set_balloon();

  # Create the graph
  $GraphDummies->plot( \@data );

  MainLoop();

=head1 SEE ALSO

See L<Tk::ForDummies::Lines>, L<Tk::ForDummies::Graph::FAQ>

=head1 COPYRIGHT & LICENSE

Copyright 2010 Djibril Ousmanou, all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.


=cut
