name                    = Mojolicious-Plugin-Fondation-Model-DBIx-Async
author                  = Daniel Brosseau <dab@cpan.org>
license                 = Perl_5
copyright_holder        = Daniel Brosseau
copyright_year          = 2026

version                 = 0.01

[@Basic]

[Prereqs::FromCPANfile]

[PkgVersion]

[PodWeaver]

[MetaJSON]

[GithubMeta]

[ConfirmRelease]
[TestRelease]
[UploadToCPAN]

; Auto-generate README.md from POD
[ReadmeAnyFromPod]
filename = README.md
type     = markdown

[Git::Check]
allow_dirty = dist.ini
allow_dirty = Changes

[Git::Commit]
allow_dirty = dist.ini
allow_dirty = Changes

[Git::Tag]

[Git::Push]
