---
abstract: 'prepare a Perl distribution for release (skeleton)'
author:
  - 'Sergey Kovalev <skov@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::Suite: '0.000139'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-prepare4release
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Tiny: '0.034'
  JSON::PP: '0'
  Pod::Usage: '0'
  perl: '5.010000'
resources:
  bugtracker: https://github.com/neo1ite/prepare4release/issues
  repository: https://github.com/neo1ite/prepare4release.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
