---
abstract: 'MIT No Attribution License (MIT-0)'
author:
  - 'ryoskzypu <ryoskzypu@proton.me>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V1: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Software-License-MIT_0
no_index:
  directory:
    - t
    - inc
    - eg
    - examples
    - share
    - xt
requires:
  Software::License: '0.104007'
  perl: '5.012000'
resources:
  bugtracker: https://github.com/ryoskzypu/Software-License-MIT_0/issues
  repository: https://github.com/ryoskzypu/Software-License-MIT_0.git
version: v1.0.1
x_contributors:
  - 'ryoskzypu <ryoskzypu@proton.me>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
x_spdx_expression: MIT-0
