---
abstract: 'Base exception package as Moo Role for Map::Tube::* family.'
author:
  - 'Mohammad Sajid Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Map-Tube-Exception
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: '0'
  Moo: '2.000000'
  Moo::Role: '0'
  Throwable: '0.200011'
  namespace::autoclean: '0.28'
  overload: '0'
  perl: '5.008'
version: '3.25'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
