--- #YAML:1.0
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
name: BATsh
version: 0.01
abstract: Bilingual Shell: cmd.exe and bash in one script
author:
  - ina <ina@cpan.org>
license: perl
generated_by: pmake.bat
requires:
  Carp: 0
  File::Copy: 2.02
  File::Path: 1.0401
  File::Spec: 0
  perl: 5.00503
  strict: 1.01
  vars: 0
  warnings: 0
build_requires:
  Test: 1.122
minimum_perl_version: 5.00503
provides:
  BATsh:
    file: lib/BATsh.pm
    version: 0.01
  BATsh::CMD:
    file: lib/BATsh/CMD.pm
    version: 0.01
  BATsh::Env:
    file: lib/BATsh/Env.pm
    version: 0.01
  BATsh::SH:
    file: lib/BATsh/SH.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: https://github.com/ina-cpan/BATsh/issues
  repository: https://github.com/ina-cpan/BATsh
