---
abstract: 'A Perl implementation for Cloudflare Turnstile'
author:
  - 'worthmine <worthmine@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.1.29, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Captcha-CLOUDFLARE-Turnstile
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Captcha::Cloudflare::Turnstile:
    file: lib/Captcha/Cloudflare/Turnstile.pm
    version: '0.02'
requires:
  Captcha::reCAPTCHA::V3: '0.12'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/worthmine/Captcha-Cloudflare-Turnstile/issues
  homepage: https://github.com/worthmine/Captcha-Cloudflare-Turnstile
  repository: https://github.com/worthmine/Captcha-Cloudflare-Turnstile.git
version: '0.02'
x_authority: cpan:WORTHMINE
x_contributors:
  - 'Yuki Yoshida <2944869+worthmine@users.noreply.github.com>'
  - 'copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
