---
abstract: 'High-speed DEFLATE, zlib, and gzip compression and decompression using libdeflate'
author:
  - vividsnow
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Temp: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150015'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Deflate-Faster
no_index:
  directory:
    - t
    - inc
provides:
  Deflate::Faster:
    file: lib/Deflate/Faster.pm
    version: '0.01'
requires:
  Carp: '0'
  Exporter: '0'
  XSLoader: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/vividsnow/perl5-deflate-faster/issues
  repository: https://github.com/vividsnow/perl5-deflate-faster.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
