---
abstract: 'CLDR person-name formatter for Perl'
author:
  - 'Jacques Deguest (jack@deguest.jp)'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  Test::More: '1.302120'
  Test::Pod: '1.52'
  lib: '0'
  open: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PersonName-Format
no_index:
  directory:
    - t
    - inc
    - t
    - inc
requires:
  Locale::Unicode: v0.4.3
  Locale::Unicode::Data: v1.9.0
  Scalar::Util: '0'
  Unicode::UCD: '0'
  Wanted: v0.1.2
  XSLoader: '0'
  parent: '0'
  perl: '5.010001'
  strict: '0'
  vars: '0'
  warnings: '0'
  warnings::register: '0'
resources:
  bugtracker: https://gitlab.com/deguest/PersonName-Format/issues
  repository: https://gitlab.com/deguest/PersonName-Format
version: v0.1.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
