---
abstract: 'Handle firewall or similar bans.'
author:
  - 'Zane C. Bowers-Hadley <vvelox@vvelox.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Ereshkigal
no_index:
  directory:
    - t
    - inc
requires:
  App::Cmd: '0'
  Error::Helper: '0'
  JSON::MaybeXS: '0'
  Net::Firewall::BlockerHelper: v0.2.0
  Net::Server::Daemonize: '0'
  POE: '0'
  POE::Component::Server::JSONUnix: v0.2.1
  Regexp::IPv4: '0'
  Regexp::IPv6: '0'
  TOML::Tiny: '0'
  perl: '5.006'
resources:
  repository: https://github.com/LilithSec/Ereshkigal.git
version: v0.0.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
