---
abstract: 'QUIC transport for Perl'
author:
  - 'Joshua S. Day <haxmeister@hotmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Temp: '0'
  FindBin: '0'
  IO::Select: '0'
  IO::Socket::INET: '0'
  Socket: '0'
  Test2::V0: '0'
  Time::HiRes: '0'
configure_requires:
  Alien::ngtcp2: '0.03'
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150015'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-QUIC
no_index:
  directory:
    - t
    - inc
provides:
  Net::QUIC:
    file: lib/Net/QUIC.pm
    version: '0.03'
  Net::QUIC::Connection:
    file: lib/Net/QUIC/Connection.pm
    version: '0.03'
  Net::QUIC::Datagram:
    file: lib/Net/QUIC/Datagram.pm
    version: '0.03'
  Net::QUIC::Driver:
    file: lib/Net/QUIC/Driver.pm
    version: '0.03'
  Net::QUIC::Endpoint:
    file: lib/Net/QUIC/Endpoint.pm
    version: '0.03'
  Net::QUIC::Stream:
    file: lib/Net/QUIC/Stream.pm
    version: '0.03'
requires:
  Alien::ngtcp2: '0.03'
  Carp: '0'
  Hash::Util::FieldHash: '0'
  Scalar::Util: '0'
  XSLoader: '0'
  perl: '5.020'
resources:
  bugtracker: https://github.com/haxmeister/perl-Net-QUIC/issues
  homepage: https://github.com/haxmeister/perl-Net-QUIC
  repository: https://github.com/haxmeister/perl-Net-QUIC.git
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
