---
abstract: 'lexically import functions from non-lexical exporters'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  File::Find: '0'
  File::Temp: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: lexically
no_index:
  directory:
    - t
    - inc
requires:
  Exporter::Lexical: '0.02'
  Module::Runtime: '0'
  strict: '0'
  warnings: '0'
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
