---
abstract: 'Enforce abstract (non-instantiable) base classes for plain-Perl OO'
author:
  - 'Nigel Horne <njh@nigelhorne.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Memory::Cycle: '0'
  Test::Mockingbird: '0'
  Test::Most: '0'
  Test::Returns: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-Abstract
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Readonly: '0'
  Return::Set: '0'
  Scalar::Util: '0'
  perl: '5.008'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Class-Abstract
  homepage: https://metacpan.org/pod/Class::Abstract
  repository: git://github.com/nigelhorne/Class-Abstract.git
version: '0.02'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
