---
abstract: 'User management plugin for Fondation'
author:
  - 'Daniel Brosseau <dab@cpan.org>'
build_requires:
  Test::More: '1.302190'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Fondation-User
requires:
  Crypt::Passphrase: '0'
  Crypt::Passphrase::Argon2: '0'
  DBIx::Class: '0.082843'
  DBIx::Class::TimeStamp: '0'
  Mojolicious: '9.46'
  Mojolicious::Plugin::Fondation: '0.01'
  Mojolicious::Plugin::Fondation::Model::DBIx::Async: '0.01'
  perl: '5.026'
resources:
  homepage: https://github.com/Dabg/Mojolicious-Plugin-Fondation-User
  repository: https://github.com/Dabg/Mojolicious-Plugin-Fondation-User.git
version: '0.01'
x_generated_by_perl: v5.40.1
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
