---
abstract: 'Name reservation for ioqwerty'
author:
  - 'ioqwerty <ping@ioqwerty.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ioqwerty
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.010'
resources:
  bugtracker: https://github.com/ioqwerty/ioqwerty/issues
  homepage: https://ioqwerty.com
  repository: https://github.com/ioqwerty/ioqwerty.git
version: v0.0.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
