---
abstract: 'Log messages to a remote UDP socket'
author:
  - 'Rob Hoelz <rob@hoelz.ro>'
build_requires:
  ExtUtils::MakeMaker: '7.22'
  File::Spec: '0'
  IO::Handle: '0'
  IO::Select: '0'
  IPC::Open3: '0'
  Log::Dispatch: '0'
  Module::Metadata: '1.000015'
  Readonly: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Dispatch-UDP
provides:
  Log::Dispatch::UDP:
    file: lib/Log/Dispatch/UDP.pm
    version: '0.02'
requires:
  Carp: '0'
  IO::Socket::INET: '0'
  Log::Dispatch::Output: '0'
  Socket: '2.026'
  namespace::clean: '0'
  parent: '0'
  perl: v5.8.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/robrwo/perl-Log-Dispatch-UDP/issues
  repository: git://github.com/robrwo/perl-Log-Dispatch-UDP.git
version: '0.02'
x_authority: cpan:RRWO
x_contributors:
  - 'Robert Rothenberg <perl@rhizomnic.com>'
x_generated_by_perl: v5.42.1
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
