;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.002

name=App-FilenameKeyValueUtils

[GenPericmdScript / GenPericmdScript parse-keyvalue-filename]
url=/Filename/KeyValue/parse_keyvalue_filename
read_env=0
read_config=0

[GenPericmdScript / GenPericmdScript modify-keyvalue-filename]
url=/Filename/KeyValue/modify_keyvalue_filename
read_env=0
read_config=0

[GenPericmdScript / GenPericmdScript normalize-keyvalue-filename]
url=/Filename/KeyValue/normalize_keyvalue_filename
read_env=0
read_config=0

[GenPericmdScript / GenPericmdScript rename-add-keyvalue-filenames]
url=/Filename/KeyValue/rename_add_keyvalue_filenames
read_env=0
read_config=0

[GenPericmdScript / GenPericmdScript rename-remove-keyvalue-filenames]
url=/Filename/KeyValue/rename_remove_keyvalue_filenames
read_env=0
read_config=0

[InsertExecsList]

[@Author::PERLANCAR]
:version=0.610

[Prereqs / TestRequires]
;Test::More=0.98

[Prereqs]
strict=0
warnings=0
