/* c/zx-idpdisc-data.h - WARNING: This header was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
/* Datastructure design, topography, and layout
 * Copyright (c) 2006,2010 Sampo Kellomaki (sampo@iki.fi),
 * All Rights Reserved. NO WARRANTY. See file COPYING for
 * terms and conditions of use. Element and attributes names as well
 * as some topography are derived from schema descriptions that were used as
 * input and may be subject to their own copright. */

#ifndef _c_zx_idpdisc_data_h
#define _c_zx_idpdisc_data_h

#include "zx.h"
#include "c/zx-const.h"
#include "c/zx-data.h"

#ifndef ZX_ELEM_EXT
#define ZX_ELEM_EXT  /* This extension point should be defined by who includes this file. */
#endif

/* -------------------------- idpdisc_DiscoveryResponse -------------------------- */
/* refby( zx_md_Extensions_s ) */
#ifndef zx_idpdisc_DiscoveryResponse_EXT
#define zx_idpdisc_DiscoveryResponse_EXT
#endif
struct zx_idpdisc_DiscoveryResponse_s {
  ZX_ELEM_EXT
  zx_idpdisc_DiscoveryResponse_EXT
  struct zx_attr_s* Binding;	/* {1,1} attribute xs:anyURI */
  struct zx_attr_s* Location;	/* {1,1} attribute xs:anyURI */
  struct zx_attr_s* ResponseLocation;	/* {0,1} attribute xs:anyURI */
  struct zx_attr_s* index;	/* {0,1} attribute xs:unsignedShort */
  struct zx_attr_s* isDefault;	/* {0,1} attribute xs:boolean */
};

#define zx_NEW_idpdisc_DiscoveryResponse(c, father) (struct zx_idpdisc_DiscoveryResponse_s*)zx_new_elem((c),(father),zx_idpdisc_DiscoveryResponse_ELEM)
int zx_DEC_ATTR_idpdisc_DiscoveryResponse(struct zx_ctx* c, struct zx_idpdisc_DiscoveryResponse_s* x);
int zx_DEC_ELEM_idpdisc_DiscoveryResponse(struct zx_ctx* c, struct zx_idpdisc_DiscoveryResponse_s* x);

#ifdef ZX_ENA_AUX
struct zx_idpdisc_DiscoveryResponse_s* zx_DEEP_CLONE_idpdisc_DiscoveryResponse(struct zx_ctx* c, struct zx_idpdisc_DiscoveryResponse_s* x, int dup_strs);
void zx_DUP_STRS_idpdisc_DiscoveryResponse(struct zx_ctx* c, struct zx_idpdisc_DiscoveryResponse_s* x);
int zx_WALK_SO_idpdisc_DiscoveryResponse(struct zx_ctx* c, struct zx_idpdisc_DiscoveryResponse_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx));
int zx_WALK_WO_idpdisc_DiscoveryResponse(struct zx_ctx* c, struct zx_idpdisc_DiscoveryResponse_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx));
#endif

#ifdef ZX_ENA_GETPUT
struct zx_attr_s* zx_idpdisc_DiscoveryResponse_GET_Binding(struct zx_idpdisc_DiscoveryResponse_s* x);
struct zx_attr_s* zx_idpdisc_DiscoveryResponse_GET_Location(struct zx_idpdisc_DiscoveryResponse_s* x);
struct zx_attr_s* zx_idpdisc_DiscoveryResponse_GET_ResponseLocation(struct zx_idpdisc_DiscoveryResponse_s* x);
struct zx_attr_s* zx_idpdisc_DiscoveryResponse_GET_index(struct zx_idpdisc_DiscoveryResponse_s* x);
struct zx_attr_s* zx_idpdisc_DiscoveryResponse_GET_isDefault(struct zx_idpdisc_DiscoveryResponse_s* x);





void zx_idpdisc_DiscoveryResponse_PUT_Binding(struct zx_idpdisc_DiscoveryResponse_s* x, struct zx_attr_s* y);
void zx_idpdisc_DiscoveryResponse_PUT_Location(struct zx_idpdisc_DiscoveryResponse_s* x, struct zx_attr_s* y);
void zx_idpdisc_DiscoveryResponse_PUT_ResponseLocation(struct zx_idpdisc_DiscoveryResponse_s* x, struct zx_attr_s* y);
void zx_idpdisc_DiscoveryResponse_PUT_index(struct zx_idpdisc_DiscoveryResponse_s* x, struct zx_attr_s* y);
void zx_idpdisc_DiscoveryResponse_PUT_isDefault(struct zx_idpdisc_DiscoveryResponse_s* x, struct zx_attr_s* y);





#endif

#endif
