requires 'perl' => '5.20.2';
requires 'Carp';
requires 'Digest::SHA';
requires 'List::Util' => '1.33';
requires 'Minion' => '10.20';
requires 'Mojolicious' => '9.02';
requires 'Mojo::Redis' => '3.25';
requires 'Sort::Versions';
requires 'Sys::Hostname';
requires 'Time::HiRes';
test_requires 'Test::More' => '0.88';
test_requires 'POSIX';
author_requires 'Minion' => '10.20';
