---
abstract: 'NIST SP 800-38G FF1 format-preserving encryption (XS binding)'
author:
  - 'Alexander Pepper <axpepper@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-FPE-FF1
no_index:
  directory:
    - t
    - inc
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
