--- #YAML:1.0
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
name: Perl7-Handy
version: 0.14
abstract: Handy Perl7 scripting environment on Perl5
author:
  - ina <ina@cpan.org>
license: perl
generated_by: pmake.bat
requires:
  Fcntl: 1.03
  bareword::filehandles: 0
  multidimensional: 0
  perl: 5.00503
  strict: 1.01
  vars: 0
build_requires:
  Test: 1.122
minimum_perl_version: 5.00503
provides:
  Perl7::Handy:
    file: lib/Perl7/Handy.pm
    version: 0.14
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: https://github.com/ina-cpan/Perl7-Handy/issues
  repository: https://github.com/ina-cpan/Perl7-Handy
