--- #YAML:1.0
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
name: Modern-Open
version: 0.15
abstract: Autovivification, Autodie, and 3-args open support
author:
  - ina <ina@cpan.org>
license: perl
generated_by: pmake.bat
requires:
  Fcntl: 1.03
  perl: 5.00503
  strict: 1.01
  vars: 0
build_requires:
  Test: 1.122
minimum_perl_version: 5.00503
provides:
  Modern::Open:
    file: lib/Modern/Open.pm
    version: 0.15
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: https://github.com/ina-cpan/Modern-Open/issues
  repository: https://github.com/ina-cpan/Modern-Open
