---
abstract: DarkPAN::Utils
author:
  - 'Rob Lauer <rclauer@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DarkPAN-Utils
no_index:
  directory:
    - t
    - inc
provides:
  DarkPAN::Utils:
    file: lib/DarkPAN/Utils.pm
    version: v1.0.0
  DarkPAN::Utils::Docs:
    file: lib/DarkPAN/Utils/Docs.pm
    version: v1.0.0
requires:
  Archive::Tar: '3.02'
  Class::Accessor::Validated: '0.04'
  HTTP::Tiny: '0.088'
  IO::Scalar: '2.113'
  IO::Socket::SSL: '0'
  IO::Uncompress::Gunzip: '2.213'
  List::Util: '0'
  Log::Log4perl: '1.57'
  Log::Log4perl::Level: '0'
  Net::SSLeay: '0'
  Pod::Extract: '0.02'
  Readonly: '2.05'
  Text::Markdown::Discount: '0.18'
  perl: '5.010'
resources:
  bugtracker: http://github.com/rlauer6/DarkPAN-Utils
  homepage: http://github.com/rlauer6/DarkPAN-Utils
  repository: git://github.com/rlauer6/DarkPAN-Utils.git
version: v1.0.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
