package titles;
%hash = (
          'So your topgit patch was merged upstream' => 'So+your+topgit+patch+was+merged+upstream',
          'Yet another git+quilt Debian packaging workflow' => 'Yet+another+git=r=quilt+Debian+packaging+workflow',
          'user level NetworkManager dispatcher' => 'user+level+NetworkManager+dispatcher',
          'Beamer overlays in highlighted source code' => 'Beamer+overlays+in+highlighted+source+code',
          'Fetching git bundles' => 'Fetching+git+bundles',
          'wifi 4965agn' => 'wifi+4965agn',
          'wanderlust whitelisting' => 'wanderlust+whitelisting',
          'Tunnel versus MUX: a race to the git' => 'Tunnel+versus+MUX=6=+a+race+to+the+git',
          'A topgit testimonial' => 'A+topgit+testimonial',
          'The little train that couldn\'t' => 'The+little+train+that+couldn=n=t',
          'digikam and raw part I (software)' => 'digikam+and+raw+part+I+=o=software=p=',
          'blorg bugs?' => 'blorg+bugs=.=',
          'A music download service that doesn\'t suck (mostly)' => 'A+music+download+service+that+doesn=n=t+suck+=o=mostly=p=',
          'Functional programming on the JVM' => 'Functional+programming+on+the+JVM',
          'Prolegomenon to any future tg-buildpackage' => 'Prolegomenon+to+any+future+tg-buildpackage',
          'Which git commits should I send to upstream?' => 'Which+git+commits+should+I+send+to+upstream=.=',
          'Tags are notmuch the point' => 'Tags+are+notmuch+the+point',
          'Housing prices in Ulaanbaatar' => 'Housing+prices+in+Ulaanbaatar',
          'Laptop Ikiwiki extended' => 'Laptop+Ikiwiki+extended',
          'managing many git repos' => 'managing+many+git+repos',
          'Copyright board inspired Dickens?' => 'Copyright+board+inspired+Dickens=.=',
          'Batch processing mails from caff' => 'Batch+processing+mails+from+caff',
          'lenovo x61 under debian unstable' => 'lenovo+x61+under+debian+unstable',
          'Welcome to IkiWiki' => 'Welcome+to+IkiWiki',
          'Encoding arbitrary strings into email addresses' => 'Encoding+arbitrary+strings+into+email+addresses',
          'filling in forms with pdftk' => 'filling+in+forms+with+pdftk',
          'Can I haz a distributed news reader?' => 'Can+I+haz+a+distributed+news+reader=.=',
          'America\'s funniest error messages' => 'America=n=s+funniest+error+messages',
          'suspend to disk key' => 'suspend+to+disk+key',
          'pushmi and ssh-agent' => 'pushmi+and+ssh-agent',
          'Mirroring a gitolite collection' => 'Mirroring+a+gitolite+collection',
          'alsa for the AD1984' => 'alsa+for+the+AD1984',
          'Printing fancier, or just different keysigining slips' => 'Printing+fancier=s=+or+just+different+keysigining+slips',
          'I hate logrotate' => 'I+hate+logrotate',
          'Converting META.yml to META.json' => 'Converting+META.yml+to+META.json',
          'The mailbox plugin for ikiwiki' => 'The+mailbox+plugin+for+ikiwiki',
          'Counting symbols from a debian symbols file' => 'Counting+symbols+from+a+debian+symbols+file',
          'Comfortable Editing of Literate Haskell' => 'Comfortable+Editing+of+Literate+Haskell',
          'Fixing flac metadata' => 'Fixing+flac+metadata',
          'I\'m root dammit, connect to the xserver.' => 'I=n=m+root+dammit=s=+connect+to+the+xserver.',
          'Using GLPK from C++' => 'Using+GLPK+from+C=r==r=',
          'Which netbook to buy' => 'Which+netbook+to+buy',
          'Using Org Mode as a time tracker' => 'Using+Org+Mode+as+a+time+tracker',
          'Converting svn-buildpackage type 2 to git' => 'Converting+svn-buildpackage+type+2+to+git',
          'Extracting text from pdf with pdfedit' => 'Extracting+text+from+pdf+with+pdfedit',
          'Converting svn-buildpackage /debian only to git' => 'Converting+svn-buildpackage+~debian+only+to+git',
          'Remote invocation of sbuild' => 'Remote+invocation+of+sbuild',
          'getting blorg working' => 'getting+blorg+working',
          'Distributed Issue Tracking with Git' => 'Distributed+Issue+Tracking+with+Git',
          'Audio Player Fail' => 'Audio+Player+Fail',
          'source-highlight and oz' => 'source-highlight+and+oz',
          'managing many git repos II' => 'managing+many+git+repos+II',
          'Trivial example using python to hack ical' => 'Trivial+example+using+python+to+hack+ical',
          'The dim screen after wakeup problem' => 'The+dim+screen+after+wakeup+problem',
          'Yet another tale of converting Debian packaging to Git' => 'Yet+another+tale+of+converting+Debian+packaging+to+Git',
          'transcoding to M4A in Amarok 1.4.7' => 'transcoding+to+M4A+in+Amarok+1.4.7',
	 'blog/posts/debug-duplicity' => 'blog~posts~debug-duplicity'
);

1;
