---
abstract: Data::NestedKey
author:
  - 'Rob Lauer <rclauer@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
  JSON: '4.10'
  YAML::XS: v0.904.0
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-NestedKey
no_index:
  directory:
    - t
    - inc
provides:
  Data::NestedKey:
    file: lib/Data/NestedKey.pm
    version: v1.2.1
  Data::NestedKey::CLI:
    file: lib/Data/NestedKey/CLI.pm
    version: '0'
requires:
  CLI::Simple: v2.0.12
  CLI::Simple::Constants: v2.0.12
  CLI::Simple::Utils: v2.0.12
  JSON: '4.10'
  YAML::XS: v0.904.0
  perl: '5.010'
resources:
  bugtracker: https://github.com/rlauer6/Data-NestedKey/issues
  homepage: https://github.com/rlauer6/Data-NestedKey
  repository: https://github.com/rlauer6/Data-NestedKey
version: v1.2.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
