---
abstract: 'Convert numeric values into their Romanian string equivalents and viceversa'
author:
  - 'Daniel Șuteu <trizen@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 0
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-RO-Numbers
provides:
  Lingua::RO::Numbers:
    file: lib/Lingua/RO/Numbers.pm
    version: '0.23'
requires:
  Encode: '0'
  perl: '5.0080001'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: https://github.com/trizen/Lingua-RO-Numbers
version: '0.23'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
