=head1 Math::Numerical

This distribution provides methods to operate on numerical functions.

=head1 Installation

  cpan Math::Numerical

=head1 Installation from source

You need C<cpanm> installed:

  cpan App::cpanminus

Then run:

  git clone https://github.com/mkende/math_numerical.git
  cd math_numerical
  perl Makefile.PL
  cpanm --installdeps --notest .
  make
  make test
  sudo make install

=head1 Documentation

All the methods of this distribution are documented with the
C<L<Math::Numerical>> module.

=head1 Author

Mathias Kende

=head1 Copyright and license

Copyright 2022 Mathias Kende

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
