# Speak configuration file
# Popular languages:
# en:    US English
# en-gb: UK English
# en-au: Australian English
# en-in: Indian English
# fr:    French
# es:    Spanish
# de:    German

# Default language and persona
language: en
persona: Random
server: speakserver
port: 5000

# WAN Failover (for off-LAN fallback)
wan_server: speakserver.example.com
wan_port: 443
wan_scheme: https
