name    = Hash-Wrap
author  = Diab Jerius <djerius@cpan.org>
license = GPL_3
copyright_holder = Smithsonian Astrophysical Observatory
copyright_year   = 2017

[@Starter]
revision = 5
installer = ModuleBuildTiny
managed_versions = 1
-remove = GatherDir
regenerate = META.json
regenerate = LICENSE
regenerate = Build.PL
regenerate = CONTRIBUTING.md
regenerate = README
regenerate = README.md

[GatherDir]
exclude_filename = LICENSE
exclude_filename = Build.PL
exclude_filename = CONTRIBUTING.md
exclude_filename = pod2htmd.tmp
exclude_filename = html-it
exclude_filename = README
exclude_filename = README.md
prune_directory = local
prune_directory = dev
exclude_match = [#~]$
exclude_match = ^META[.].*
exclude_match = GTAGS|GRTAGS|GPATH

[GatherDir::Template]
root = templates

[ReadmeAnyFromPod]
filename = README.md
type = markdown

[PodWeaver]
replacer = replace_with_blank
post_code_replacer = replace_with_nothing

[InsertExample]
remove_boiler = 1

[InsertCopyright]

[MetaResources]
bugtracker.web = https://rt.cpan.org/Public/Dist/Display.html?Name=Hash-Wrap
bugtracker.mailto = bug-hash-wrap@rt.cpan.org
repository.web = https://codeberg.org/djerius/p5-Hash-Wrap
repository.url = https://codeberg.org/djerius/p5-Hash-Wrap.git
repository.type = git

[CheckMetaResources]

[MetaNoIndex]
directory = t
directory = xt
directory = inc
directory = share
directory = eg
directory = examples

[Regenerate]
filenames = META.json
filenames = LICENSE
filenames = Build.PL
filenames = CONTRIBUTING.md

[Test::Compile]
[Test::NoTabs]
[Test::Fixme]
[Test::Version]
[Test::NoBreakpoints]
[Test::TrailingSpace]
[Test::DistManifest]
[Test::CPAN::Changes]
[Test::CPAN::Meta::JSON]
[Test::Perl::Critic]
critic_config = perlcritic.rc

[Test::CleanNamespaces]
[Test::PodSpelling]
stopword = DCONWAY

[PodCoverageTests]

[Prereqs::AuthorDeps]
[EnsurePrereqsInstalled]

[EnsureChangesHasContent]

; --- Project-specific directives

[Prereqs]
Scalar::Util = 0
perl = 5.010

[Prereqs / ConfigureRequires ]
Module::Build::Tiny      = 0

[Prereqs / TestRequires]
Test2::V0                = 0

; authordep Pod::Weaver::Plugin::StopWords
; authordep Pod::Weaver::Section::Contributors
; authordep Pod::Weaver::Section::GenerateSection
; authordep Pod::Weaver::Section::SeeAlso

[Prereqs / DevelopRequires ]
Pod::Coverage::TrustPod  = 0
Test::CPAN::Changes      = 0
Test::CPAN::Meta::JSON   = 0
Test::CleanNamespaces    = 0
Test::DistManifest       = 0
Test::More               = 0
Test::NoBreakpoints      = 0
Test::NoTabs             = 0
Test::Pod                = 0
Test::Pod::Coverage      = 0
Test::Version            = 0
