#!perl

# Note: This script is a CLI for Riap function /Module/DataPack/datapack_modules
# and generated automatically using Perinci::CmdLine::Gen version 0.496

our $AUTHORITY = 'cpan:PERLANCAR'; # AUTHORITY
our $DATE = '2020-04-30'; # DATE
our $DIST = 'App-DataPackUtils'; # DIST
our $VERSION = '0.06'; # VERSION

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

my $cmdline = Perinci::CmdLine::Any->new(
    url => "/Module/DataPack/datapack_modules",
    program_name => "datapack-modules",
);

$cmdline->run;

# ABSTRACT: Like Module::FatPack, but uses datapacking instead of fatpack
# PODNAME: datapack-modules

__END__

=pod

=encoding UTF-8

=head1 NAME

datapack-modules - Like Module::FatPack, but uses datapacking instead of fatpack

=head1 VERSION

This document describes version 0.06 of datapack-modules (from Perl distribution App-DataPackUtils), released on 2020-04-30.

=head1 SYNOPSIS

Usage:

 % datapack-modules [--config-path=path | -c] [--config-profile=profile |
     -P] [--format=name] [--json] [-m=s+] [--module-name=s+]
     [--module-names-json=s] [--module-src key=s] [--module-srcs-json=s]
     [--(no)naked-res] [--no-config | -C] [--no-env] [--no-overwrite]
     [--no-stripper] [--no-stripper-comment] [--no-stripper-log]
     [--no-stripper-maintain-linum] [--no-stripper-pod] [--no-stripper-ws]
     [--nooverwrite] [--nostripper] [--nostripper-comment]
     [--nostripper-log] [--nostripper-maintain-linum] [--nostripper-pod]
     [--nostripper-ws] [-o=s] [--output=s] [--overwrite]
     [--page-result[=program]] [--postamble=s] [--preamble=s]
     [--put-hook-at-the-end] [--stripper] [--stripper-comment]
     [--stripper-log] [--stripper-maintain-linum] [--stripper-pod]
     [--stripper-ws] [module_name] ...

Examples:

Datapack two modules:

 % datapack-modules Text::Table::Tiny Try::Tiny

=head1 DESCRIPTION

Both this module and C<Module:FatPack> generate source code that embeds modules'
source codes and load them on-demand via require hook. The difference is that
the modules' source codes are put in C<__DATA__> section instead of regular Perl
hashes (fatpack uses C<%fatpacked>). This reduces compilation overhead, although
this is not noticeable unless when the number of embedded modules is quite
large. For example, in C<App::pause>, the C<pause> script embeds ~320 modules with
a total of ~54000 lines. The overhead of fatpack code is ~49ms on my PC, while
with datapack the overhead is about ~10ms.

There are two downsides of this technique. The major one is that you cannot load
modules during BEGIN phase (e.g. using C<use>) because at that point, DATA
section is not yet available. You can only use run-time require()'s.

Another downside of this technique is that you cannot use C<__DATA__> section for
other purposes (well, actually with some care, you still can).

=head1 OPTIONS

C<*> marks required options.

=head2 Main options

=over

=item B<--put-hook-at-the-end>

Put the require hook at the end of @INC using "push" instead of at the front using "unshift".

=back

=head2 Configuration options

=over

=item B<--config-path>=I<s>, B<-c>

Set path to configuration file.

=item B<--config-profile>=I<s>, B<-P>

Set configuration profile to use.

=item B<--no-config>, B<-C>

Do not use any configuration file.

=back

=head2 Environment options

=over

=item B<--no-env>

Do not read environment for default options.

=back

=head2 Input options

=over

=item B<--module-name>=I<modulename>, B<-m>

Module names to search.

Can be specified multiple times.

=item B<--module-names-json>=I<modulename>

Module names to search (JSON-encoded).

See C<--module-name>.

=item B<--module-src>=I<s>%

Module source codes (a hash, keys are module names).

Each value is a name-value pair, use I<key=value> syntax. Can be specified multiple times.

=item B<--module-srcs-json>=I<s>

Module source codes (a hash, keys are module names) (JSON-encoded).

See C<--module-src>.

=item B<--postamble>=I<s>

Perl source code to add after the datapack code (but before the __DATA__ section).

=item B<--preamble>=I<s>

Perl source code to add before the datapack code.

=back

=head2 Output options

=over

=item B<--format>=I<s>

Choose output format, e.g. json, text.

Default value:

 undef

=item B<--json>

Set output format to json.

=item B<--naked-res>

When outputing as JSON, strip result envelope.

Default value:

 0

By default, when outputing as JSON, the full enveloped result is returned, e.g.:

    [200,"OK",[1,2,3],{"func.extra"=>4}]

The reason is so you can get the status (1st element), status message (2nd
element) as well as result metadata/extra result (4th element) instead of just
the result (3rd element). However, sometimes you want just the result, e.g. when
you want to pipe the result for more post-processing. In this case you can use
`--naked-res` so you just get:

    [1,2,3]


=item B<--output>=I<filename>, B<-o>

Output filename.

=item B<--overwrite>

Overwrite output if previously exists.

=item B<--page-result>

Filter output through a pager.

=back

=head2 Stripping options

=over

=item B<--no-stripper-comment>

Set strip_comment=0 (don't strip comments) in Perl::Stripper.

=item B<--no-stripper-pod>

Set strip_pod=0 (don't strip POD) in Perl::Stripper.

=item B<--no-stripper-ws>

Set strip_ws=0 (don't strip whitespace) in Perl::Stripper.

=item B<--stripper>

Strip included modules using Perl::Stripper.

=item B<--stripper-log>

Set strip_log=1 (strip log statements) in Perl::Stripper.

=item B<--stripper-maintain-linum>

Set maintain_linum=1 in Perl::Stripper.

=back

=head2 Other options

=over

=item B<--help>, B<-h>, B<-?>

Display help message and exit.

=item B<--version>, B<-v>

Display program's version and exit.

=back

=head1 COMPLETION

This script has shell tab completion capability with support for several
shells.

=head2 bash

To activate bash completion for this script, put:

 complete -C datapack-modules datapack-modules

in your bash startup (e.g. F<~/.bashrc>). Your next shell session will then
recognize tab completion for the command. Or, you can also directly execute the
line above in your shell to activate immediately.

It is recommended, however, that you install modules using L<cpanm-shcompgen>
which can activate shell completion for scripts immediately.

=head2 tcsh

To activate tcsh completion for this script, put:

 complete datapack-modules 'p/*/`datapack-modules`/'

in your tcsh startup (e.g. F<~/.tcshrc>). Your next shell session will then
recognize tab completion for the command. Or, you can also directly execute the
line above in your shell to activate immediately.

It is also recommended to install L<shcompgen> (see above).

=head2 other shells

For fish and zsh, install L<shcompgen> as described above.

=head1 CONFIGURATION FILE

This script can read configuration files. Configuration files are in the format of L<IOD>, which is basically INI with some extra features.

By default, these names are searched for configuration filenames (can be changed using C<--config-path>): F<~/.config/datapack-modules.conf>, F<~/datapack-modules.conf>, or F</etc/datapack-modules.conf>.

All found files will be read and merged.

To disable searching for configuration files, pass C<--no-config>.

You can put multiple profiles in a single file by using section names like C<[profile=SOMENAME]> or C<[SOMESECTION profile=SOMENAME]>. Those sections will only be read if you specify the matching C<--config-profile SOMENAME>.

You can also put configuration for multiple programs inside a single file, and use filter C<program=NAME> in section names, e.g. C<[program=NAME ...]> or C<[SOMESECTION program=NAME]>. The section will then only be used when the reading program matches.

Finally, you can filter a section by environment variable using the filter C<env=CONDITION> in section names. For example if you only want a section to be read if a certain environment variable is true: C<[env=SOMEVAR ...]> or C<[SOMESECTION env=SOMEVAR ...]>. If you only want a section to be read when the value of an environment variable has value equals something: C<[env=HOSTNAME=blink ...]> or C<[SOMESECTION env=HOSTNAME=blink ...]>. If you only want a section to be read when the value of an environment variable does not equal something: C<[env=HOSTNAME!=blink ...]> or C<[SOMESECTION env=HOSTNAME!=blink ...]>. If you only want a section to be read when an environment variable contains something: C<[env=HOSTNAME*=server ...]> or C<[SOMESECTION env=HOSTNAME*=server ...]>. Note that currently due to simplistic parsing, there must not be any whitespace in the value being compared because it marks the beginning of a new section filter or section name.

List of available configuration parameters:

 format (see --format)
 module_names (see --module-name)
 module_srcs (see --module-src)
 naked_res (see --naked-res)
 output (see --output)
 overwrite (see --overwrite)
 postamble (see --postamble)
 preamble (see --preamble)
 put_hook_at_the_end (see --put-hook-at-the-end)
 stripper (see --stripper)
 stripper_comment (see --no-stripper-comment)
 stripper_log (see --stripper-log)
 stripper_maintain_linum (see --stripper-maintain-linum)
 stripper_pod (see --no-stripper-pod)
 stripper_ws (see --no-stripper-ws)

=head1 ENVIRONMENT

=head2 DATAPACK_MODULES_OPT => str

Specify additional command-line options.

=head1 FILES

F<~/.config/datapack-modules.conf>

F<~/datapack-modules.conf>

F</etc/datapack-modules.conf>

=head1 HOMEPAGE

Please visit the project's homepage at L<https://metacpan.org/release/App-DataPackUtils>.

=head1 SOURCE

Source repository is at L<https://github.com/perlancar/perl-App-DataPackUtils>.

=head1 BUGS

Please report any bugs or feature requests on the bugtracker website L<https://rt.cpan.org/Public/Dist/Display.html?Name=App-DataPackUtils>

When submitting a bug or request, please include a test-file or a
patch to an existing test-file that illustrates the bug or desired
feature.

=head1 AUTHOR

perlancar <perlancar@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2020, 2017, 2016, 2015 by perlancar@cpan.org.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
