---
abstract: 'roles with composition parameters'
author:
  - 'Tiago Peczenyj <tiago.peczenyj+cpan@gmail.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Role::Tiny: '2.000000'
  Test::Exception: '0.43'
  Test::More: '0.94'
  Test::Pod: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-Role-Parameterized
provides:
  MooX::Role::Parameterized:
    file: lib/MooX/Role/Parameterized.pm
    version: '0.701'
  MooX::Role::Parameterized::Cookbook:
    file: lib/MooX/Role/Parameterized/Cookbook.pm
    version: '0.701'
  MooX::Role::Parameterized::Mop:
    file: lib/MooX/Role/Parameterized/Mop.pm
    version: '0.701'
  MooX::Role::Parameterized::With:
    file: lib/MooX/Role/Parameterized/With.pm
    version: '0.701'
requires:
  Carp: '0'
  Module::Runtime: '0'
  Moo: '2'
  MooX::BuildClass: '0.213360'
  perl: '5.012'
resources:
  bugtracker: https://github.com/peczenyj/MooX-Role-Parameterized/issues
  homepage: https://github.com/peczenyj/MooX-Role-Parameterized
  repository: https://github.com/peczenyj/MooX-Role-Parameterized.git
version: '0.701'
x_authority: cpan:PACMAN
x_generated_by_perl: v5.42.2
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: MIT
