--- #YAML:1.0
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
name: mb
version: 0.60
abstract: Can easy script in Big5, Big5-HKSCS, GBK, Sjis(also CP932), UHC, UTF-8, ...
author:
  - ina <ina@cpan.org>
license: perl
generated_by: pmake.bat
requires:
  perl: 5.00503
  strict: 1.01
build_requires:
  Test: 1.122
minimum_perl_version: 5.00503
provides:
  mb:
    file: lib/mb.pm
    version: 0.60
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: https://github.com/ina-cpan/mb/issues
  repository: https://github.com/ina-cpan/mb
