---
abstract: 'automatically load test helpers by walking the directory tree'
author:
  - 'Branislav Zahradník <barney@cpan.org>'
build_requires:
  Module::Build: '0.28'
  Path::Tiny: '0.018'
  Test::EOL: '0'
  Test::YAFT: '0'
  constant: '0'
  require::relative: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Load-Helper
provides:
  Test::Load::Helper:
    file: lib/Test/Load/Helper.pm
    version: v1.0.0
requires:
  Carp: '0'
  Path::Tiny: '0.018'
  perl: '5.014'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/happy-barney/perl-Test-Load-Helper/issues
  repository: git://github.com/happy-barney/perl-Test-Load-Helper.git
version: 1.0.0
x_generated_by_perl: v5.38.2
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: Artistic-2.0
