package Daje::Database::View::Super::vAuthoritiesRoleCompanyList;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vAuthoritiesRoleCompanyList - Daje db view
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vAuthoritiesRoleCompanyList;
#
#       my $table = Daje::Database::View::Super::vAuthoritiesRoleCompanyList->new(db => $db);
#
#       my $result = $table->load_authorities_role_company_pkey($self, $authorities_role_company_pkey);
#
#       my $result = $table->load_authorities_role_fkey($self, $authorities_role_fkey);
#
#       my $result = $table->load_authorities_companies_fkey($self, $authorities_companies_fkey);
##
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::AuthoritiesRoleCompanyList is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-10 03:59:39.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-02-10 03:59:39 -->

our $VERSION = '0.01';

has 'fields' => '"authorities_role_company_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime",
"authorities_role_fkey",
"companies_companies_fkey"';
has 'primary_key_name' => "authorities_role_company_pkey";
has 'table_name' => "v_authorities_role_company_list";

async sub load_all_authorities_role_list_p($self) {
    return $self->load_all_authorities_role_list();
}

sub load_all_authorities_role_list($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}

async sub load_authorities_role_list_p($self, $key_value) {
    return $self->load_authorities_role_list($key_value);
}

sub load_authorities_role_list($self, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
async sub load_all_companies_companies_list_p($self) {
    return $self->load_all_companies_companies_list();
}

sub load_all_companies_companies_list($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}

async sub load_companies_companies_list_p($self, $key_value) {
    return $self->load_authorities_companies_list($key_value);
}

sub load_companies_companies_list($self, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
async sub load_all_authorities_role_company_p($self) {
    return $self->load_all_authorities_role_company();
}

sub load_all_authorities_role_company($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}
1;




#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Database::View::Super::vAuthoritiesRoleCompanyList - Daje db view



=head1 SYNOPSIS



      use Daje::Database::View::Super::vAuthoritiesRoleCompanyList;

      my $table = Daje::Database::View::Super::vAuthoritiesRoleCompanyList->new(db => $db);

      my $result = $table->load_authorities_role_company_pkey($self, $authorities_role_company_pkey);

      my $result = $table->load_authorities_role_fkey($self, $authorities_role_fkey);

      my $result = $table->load_authorities_companies_fkey($self, $authorities_companies_fkey);

      my $result = $table->insert($self, $data);

      $table->update($self, $data) ;




=head1 DESCRIPTION


Daje::Database::View::Super::AuthoritiesRoleCompanyList is a Model super class



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

