---
abstract: 'Fast type-specialized hash maps with TTL and LRU, in C'
author:
  - vividsnow
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  Devel::PPPort: '0'
  ExtUtils::MakeMaker: '0'
  Module::Metadata: '0'
  XS::Parse::Keyword::Builder: '0.40'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150014'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-HashMap
no_index:
  directory:
    - t
    - inc
provides:
  Data::HashMap:
    file: lib/Data/HashMap.pm
    version: '0.09'
  Data::HashMap::I16:
    file: lib/Data/HashMap/I16.pm
    version: '0.09'
  Data::HashMap::I16A:
    file: lib/Data/HashMap/I16A.pm
    version: '0.09'
  Data::HashMap::I16S:
    file: lib/Data/HashMap/I16S.pm
    version: '0.09'
  Data::HashMap::I32:
    file: lib/Data/HashMap/I32.pm
    version: '0.09'
  Data::HashMap::I32A:
    file: lib/Data/HashMap/I32A.pm
    version: '0.09'
  Data::HashMap::I32S:
    file: lib/Data/HashMap/I32S.pm
    version: '0.09'
  Data::HashMap::IA:
    file: lib/Data/HashMap/IA.pm
    version: '0.09'
  Data::HashMap::II:
    file: lib/Data/HashMap/II.pm
    version: '0.09'
  Data::HashMap::IS:
    file: lib/Data/HashMap/IS.pm
    version: '0.09'
  Data::HashMap::SA:
    file: lib/Data/HashMap/SA.pm
    version: '0.09'
  Data::HashMap::SI:
    file: lib/Data/HashMap/SI.pm
    version: '0.09'
  Data::HashMap::SI16:
    file: lib/Data/HashMap/SI16.pm
    version: '0.09'
  Data::HashMap::SI32:
    file: lib/Data/HashMap/SI32.pm
    version: '0.09'
  Data::HashMap::SS:
    file: lib/Data/HashMap/SS.pm
    version: '0.09'
requires:
  XS::Parse::Keyword: '0.40'
  perl: '5.022'
resources:
  bugtracker: https://github.com/vividsnow/perl5-data-hashmap/issues
  repository: https://github.com/vividsnow/perl5-data-hashmap.git
version: '0.09'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
