---
abstract: 'base API class for Net::Flickr::* libraries'
author:
  - 'Aaron Straup Cope E<lt>ascope@cpan.orgE<gt>'
build_requires:
  Log::Dispatch::Code: '2.36'
  Test::Simple: '0.47'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Flickr-API
provides:
  Net::Flickr::API:
    file: lib/Net/Flickr/API.pm
    version: '1.8'
requires:
  Config::Simple: '0'
  Flickr::API: '1.04'
  Flickr::Upload: '1.32'
  HTTP::Date: '0'
  List::Util: '0'
  Log::Dispatch: '2.10'
  Readonly: '0'
  Time::HiRes: '0'
  XML::XPath: '1.13'
resources:
  license: http://dev.perl.org/licenses/
version: '1.8'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
