#!perl

# Note: This script is a CLI for Riap function /App/MineralUtils/convert_magnesium_unit
# and generated automatically using Perinci::CmdLine::Gen version 0.502

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

our $AUTHORITY = 'cpan:PERLANCAR'; # AUTHORITY
our $DATE = '2024-12-04'; # DATE
our $DIST = 'App-MineralUtils'; # DIST
our $VERSION = '0.020'; # VERSION

my $cmdline = Perinci::CmdLine::Any->new(
    url => "/App/MineralUtils/convert_magnesium_unit",
    program_name => "convert-magnesium-unit",
    pass_cmdline_object => 1,
    read_config => 0,
    read_env => 0,
);

$cmdline->run;

# ABSTRACT: Convert a magnesium quantity from one unit to another
# PODNAME: convert-magnesium-unit

__END__

=pod

=encoding UTF-8

=head1 NAME

convert-magnesium-unit - Convert a magnesium quantity from one unit to another

=head1 VERSION

This document describes version 0.020 of convert-magnesium-unit (from Perl distribution App-MineralUtils), released on 2024-12-04.

=head1 SYNOPSIS

B<convert-magnesium-unit> B<L<--help|/"--help, -h, -?">> (or B<L<-h|/"--help, -h, -?">>, B<L<-?|/"--help, -h, -?">>)

B<convert-magnesium-unit> B<L<--version|/"--version, -v">> (or B<L<-v|/"--version, -v">>)

B<convert-magnesium-unit> [B<L<--format|/"--format=s">>=I<name>|B<L<--json|/"--json">>] [B<L<--(no)naked-res|/"--naked-res">>] [B<L<--page-result|/"--page-result">>[=I<program>]|B<L<--view-result|/"--view-result">>[=I<program>]] -- [I<L<quantity|/"--quantity=s">>] [I<L<to_unit|/"--to-unit=s">>]



See examples in the L</EXAMPLES> section.

=head1 DESCRIPTION

If target unit is not specified, will show all known conversions.

=head1 OPTIONS

C<*> marks required options.

=head2 Main options

=over

=item B<--quantity>=I<s>

Default value:

 "1 mg"

Can also be specified as the 1st command-line argument.

=item B<--to-unit>=I<s>

Valid values:

 ["mg","mg-mg-elem","mg-trimagnesium-dicitrate","mg-mg-citrate-dibasic","mg-mg-citrate-anhydrous","mg-mg-citrate-anhydrous-nowfoods","mg-mg-citrate-nonahydrate","mg-mg-glycinate-anhydrous","mg-mg-bisglycinate-anhydrous","mg-mg-bisglycinate-nowfoods","mg-mg-ascorbate-dihydrate","mg-mg-pidolate","mg-mg-l-threonate","mg-mg-oxide-anhydrous","mg-magshape","mg-mg-lactate-anhydrous","mg-mg-lactate-dihydrate","mg-mg-chloride-ah","mg-mg-chloride-hexahydrate","mg-mg-malate","mg-mg-malate-trihydrate","mg-mg-sulfate-anhydrous","mg-mg-sulfate-monohydrate","mg-mg-sulfate-heptahydrate","mg-mg-carbonate-anhydrous","mg-mg-carbonate-trihydrate","mg-mg-hydroxide-anhydrous","mg-mg-hydroxide-pentahydrate","mg-mg-acetate-anhydrous","mg-mg-acetate-tetrahydrate","mg-mg-gluconate-dihydrate","mg-mg-gluconate-hydrate","mg-mg-glycerophosphate-anhydrous","mg-mg-glycerophosphate-hydrate","mg-trimagnesium-orthophosphate-anhydrous","mg-sunactive-mg","mg-mg-taurate"]

Can also be specified as the 2nd command-line argument.

=back

=head2 Output options

=over

=item B<--format>=I<s>

Choose output format, e.g. json, text.

Default value:

 undef

Output can be displayed in multiple formats, and a suitable default format is
chosen depending on the application and/or whether output destination is
interactive terminal (i.e. whether output is piped). This option specifically
chooses an output format.


=item B<--json>

Set output format to json.

=item B<--naked-res>

When outputing as JSON, strip result envelope.

Default value:

 0

By default, when outputing as JSON, the full enveloped result is returned, e.g.:

 [200,"OK",[1,2,3],{"func.extra"=>4}]

The reason is so you can get the status (1st element), status message (2nd
element) as well as result metadata/extra result (4th element) instead of just
the result (3rd element). However, sometimes you want just the result, e.g. when
you want to pipe the result for more post-processing. In this case you can use
C<--naked-res> so you just get:

 [1,2,3]


=item B<--page-result>

Filter output through a pager.

This option will pipe the output to a specified pager program. If pager program
is not specified, a suitable default e.g. C<less> is chosen.


=item B<--view-result>

View output using a viewer.

This option will first save the output to a temporary file, then open a viewer
program to view the temporary file. If a viewer program is not chosen, a
suitable default, e.g. the browser, is chosen.


=back

=head2 Other options

=over

=item B<--help>, B<-h>, B<-?>

Display help message and exit.

=item B<--version>, B<-v>

Display program's version and exit.

=back

=head1 COMPLETION

This script has shell tab completion capability with support for several
shells.

=head2 bash

To activate bash completion for this script, put:

 complete -C convert-magnesium-unit convert-magnesium-unit

in your bash startup (e.g. F<~/.bashrc>). Your next shell session will then
recognize tab completion for the command. Or, you can also directly execute the
line above in your shell to activate immediately.

It is recommended, however, that you install modules using L<cpanm-shcompgen>
which can activate shell completion for scripts immediately.

=head2 tcsh

To activate tcsh completion for this script, put:

 complete convert-magnesium-unit 'p/*/`convert-magnesium-unit`/'

in your tcsh startup (e.g. F<~/.tcshrc>). Your next shell session will then
recognize tab completion for the command. Or, you can also directly execute the
line above in your shell to activate immediately.

It is also recommended to install L<shcompgen> (see above).

=head2 other shells

For fish and zsh, install L<shcompgen> as described above.

=head1 EXAMPLES

=head2 Show all possible conversions

 % convert-magnesium-unit
 +--------+---------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
 | amount |  pct_mg | unit                                     | summary                                                                                                                                           |
 +--------+---------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
 |  1.000 | 100.000 | mg-mg-elem                               | Elemental magnesium, in milligrams                                                                                                                |
 |  6.173 |  16.163 | mg-trimagnesium-dicitrate                | Magnesium citrate a.k.a trimagnesium dicitrate (C12H10Mg3O14), in milligrams                                                                      |
 |  8.850 |  11.336 | mg-mg-citrate-dibasic                    | Magnesium citrate dibasic (C6H6MgO7), in milligrams                                                                                               |
 |  6.289 |  15.950 | mg-mg-citrate-anhydrous                  | Magnesium citrate anhydrous ((C6H5O7)2Mg3, C12H16Mg3O14), in milligrams                                                                           |
 |  6.897 |  15.950 | mg-mg-citrate-anhydrous-nowfoods         | Magnesium citrate in NOW Foods supplement (anhydrous, C12H16Mg3O14, 90.9% pure, contains citric acid etc), in milligrams                          |
 | 25.000 |   3.963 | mg-mg-citrate-nonahydrate                | Magnesium citrate nonahydrate ((C6H5O7)2Mg3 · 9H2O, C12H28Mg3O23) [most common hydrate form of Mg-citrate at room temp], in milligrams            |
 |  7.092 |  14.096 | mg-mg-glycinate-anhydrous                | Magnesium glycinate/bisglycinate anhydrous (C4H8MgN2O4) [most common hydrate form of Mg-glycinate], in milligrams                                 |
 |  7.092 |  14.096 | mg-mg-bisglycinate-anhydrous             | Magnesium glycinate/bisglycinate (C4H8MgN2O4) [most common hydrate form of Mg-glycinate], in milligrams                                           |
 | 10.000 |  14.096 | mg-mg-bisglycinate-nowfoods              | Magnesium bisglycinate in NOW Foods supplement (C4H8MgN2O4, 70.5% pure, contains citric acid etc), in milligrams                                  |
 | 15.385 |   6.489 | mg-mg-ascorbate-dihydrate                | Magnesium ascorbate hydrate (C12H14MgO12) [anhydrous and dihydrate are the most common hydrate forms of Mg-ascorbate at room temp], in milligrams |
 | 11.494 |   8.664 | mg-mg-pidolate                           | Magnesium pidolate (C10H12MgN2O6), in milligrams                                                                                                  |
 | 12.048 |   8.253 | mg-mg-l-threonate                        | Magnesium L-threonate (C8H14MgO10), in milligrams                                                                                                 |
 |  1.658 |  60.304 | mg-mg-oxide-anhydrous                    | Magnesium oxide anhydrous (MgO) [most common hydrate form of MgO at room temp], in milligrams                                                     |
 |  3.125 |  32.000 | mg-magshape                              | MAGSHAPE (microencapsulated form of magnesium oxide), in milligrams                                                                               |
 |  8.333 |  12.005 | mg-mg-lactate-anhydrous                  | Magnesium lactate dihydrate (C6H10MgO6), in milligrams                                                                                            |
 |  9.804 |  10.192 | mg-mg-lactate-dihydrate                  | Magnesium lactate dihydrate (C6H14MgO8), in milligrams                                                                                            |
 |  3.922 |  25.528 | mg-mg-chloride-ah                        | Magnesium chloride (anhydrous, MgCl2), in milligrams                                                                                              |
 |  8.333 |  11.955 | mg-mg-chloride-hexahydrate               | Magnesium chloride (hexahydrate, H12Cl2MgO6), in milligrams                                                                                       |
 |  6.452 |  15.543 | mg-mg-malate                             | Magnesium malate (C4H4MgO5), in milligrams                                                                                                        |
 |  8.621 |  11.552 | mg-mg-malate-trihydrate                  | Magnesium malate (MgC4H4O5.3H2O), in milligrams                                                                                                   |
 |  4.950 |  20.192 | mg-mg-sulfate-anhydrous                  | Magnesium sulfate anhydrous (MgSO4), in milligrams                                                                                                |
 |  5.682 |  17.563 | mg-mg-sulfate-monohydrate                | Magnesium sulfate monohydrate (MgSO4.H2O), in milligrams                                                                                          |
 | 10.101 |   9.861 | mg-mg-sulfate-heptahydrate               | Magnesium sulfate heptahydrate (MgSO4.7H2O) a.k.a. Epsom salt, in milligrams                                                                      |
 |  3.472 |  28.828 | mg-mg-carbonate-anhydrous                | Magnesium carbonate anhydrous (MgCO3), in milligrams                                                                                              |
 |  6.024 |  16.603 | mg-mg-carbonate-trihydrate               | Magnesium carbonate trihydrate (MgCO3.3H2O), in milligrams                                                                                        |
 |  2.398 |  41.675 | mg-mg-hydroxide-anhydrous                | Magnesium hydroxide anhydrous (Mg(OH)2), in milligrams                                                                                            |
 |  5.682 |  17.566 | mg-mg-hydroxide-pentahydrate             | Magnesium hydroxide pentahydrate (Mg(OH)2.5H2O), in milligrams                                                                                    |
 |  5.848 |  17.069 | mg-mg-acetate-anhydrous                  | Magnesium acetate anhydrous (Mg(CH3COO)2), in milligrams                                                                                          |
 |  8.850 |  11.334 | mg-mg-acetate-tetrahydrate               | Magnesium acetate tetrahydrate (Mg(CH3COO)2.4H2O), in milligrams                                                                                  |
 | 18.519 |   5.394 | mg-mg-gluconate-dihydrate                | Magnesium gluconate dihydrate (C12H26MgO16), in milligrams                                                                                        |
 | 17.857 |   5.618 | mg-mg-gluconate-hydrate                  | Magnesium gluconate dihydrate (C12H26MgO16), in milligrams                                                                                        |
 |  8.000 |  12.505 | mg-mg-glycerophosphate-anhydrous         | Magnesium glycerophosphate anhydrous (C₃H₇MgO₆P), in milligrams                                                                                   |
 |  8.772 |  11.444 | mg-mg-glycerophosphate-hydrate           | Magnesium glycerophosphate anhydrous (C₃H₇MgO₆P.H2O, C3H9MgO7P), in milligrams                                                                    |
 |  3.610 |  27.739 | mg-trimagnesium-orthophosphate-anhydrous | Trimagnesium orthophosphate (Mg3O8P2), in milligrams                                                                                              |
 |  8.333 |  12.000 | mg-sunactive-mg                          | SunActive Magnesium (a micronized, microencapsulated form of trimagnesium orthophosphate), in milligrams                                          |
 | 11.236 |   8.916 | mg-mg-taurate                            | Magnesium taurate (C4H12MgN2O6S2), in milligrams                                                                                                  |
 +--------+---------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+

=head2 How much of magnesium oxide provides 350 mg of elemental magnesium?

 % convert-magnesium-unit '350 mg-mg-oxide-anhydrous' mg-mg-elem
 211.05

=head2 Sort by highest magnesium content

 % convert-magnesium-unit | td sort -- -pct_mg
 1.000	100.000	mg-mg-elem	Elemental magnesium, in milligrams
 1.658	60.304	mg-mg-oxide-anhydrous	Magnesium oxide anhydrous (MgO) [most common hydrate form of MgO at room temp], in milligrams
 2.398	41.675	mg-mg-hydroxide-anhydrous	Magnesium hydroxide anhydrous (Mg(OH)2), in milligrams
 3.125	32.000	mg-magshape	MAGSHAPE (microencapsulated form of magnesium oxide), in milligrams
 3.472	28.828	mg-mg-carbonate-anhydrous	Magnesium carbonate anhydrous (MgCO3), in milligrams
 3.610	27.739	mg-trimagnesium-orthophosphate-anhydrous	Trimagnesium orthophosphate (Mg3O8P2), in milligrams
 3.922	25.528	mg-mg-chloride-ah	Magnesium chloride (anhydrous, MgCl2), in milligrams
 4.950	20.192	mg-mg-sulfate-anhydrous	Magnesium sulfate anhydrous (MgSO4), in milligrams
 5.682	17.566	mg-mg-hydroxide-pentahydrate	Magnesium hydroxide pentahydrate (Mg(OH)2.5H2O), in milligrams
 5.682	17.563	mg-mg-sulfate-monohydrate	Magnesium sulfate monohydrate (MgSO4.H2O), in milligrams
 5.848	17.069	mg-mg-acetate-anhydrous	Magnesium acetate anhydrous (Mg(CH3COO)2), in milligrams
 6.024	16.603	mg-mg-carbonate-trihydrate	Magnesium carbonate trihydrate (MgCO3.3H2O), in milligrams
 6.173	16.163	mg-trimagnesium-dicitrate	Magnesium citrate a.k.a trimagnesium dicitrate (C12H10Mg3O14), in milligrams
 6.289	15.950	mg-mg-citrate-anhydrous	Magnesium citrate anhydrous ((C6H5O7)2Mg3, C12H16Mg3O14), in milligrams
 6.897	15.950	mg-mg-citrate-anhydrous-nowfoods	Magnesium citrate in NOW Foods supplement (anhydrous, C12H16Mg3O14, 90.9% pure, contains citric acid etc), in milligrams
 6.452	15.543	mg-mg-malate	Magnesium malate (C4H4MgO5), in milligrams
 7.092	14.096	mg-mg-glycinate-anhydrous	Magnesium glycinate/bisglycinate anhydrous (C4H8MgN2O4) [most common hydrate form of Mg-glycinate], in milligrams
 7.092	14.096	mg-mg-bisglycinate-anhydrous	Magnesium glycinate/bisglycinate (C4H8MgN2O4) [most common hydrate form of Mg-glycinate], in milligrams
 10.000	14.096	mg-mg-bisglycinate-nowfoods	Magnesium bisglycinate in NOW Foods supplement (C4H8MgN2O4, 70.5% pure, contains citric acid etc), in milligrams
 8.000	12.505	mg-mg-glycerophosphate-anhydrous	Magnesium glycerophosphate anhydrous (C\xE2\x82\x83H\xE2\x82\x87MgO\xE2\x82\x86P), in milligrams
 8.333	12.005	mg-mg-lactate-anhydrous	Magnesium lactate dihydrate (C6H10MgO6), in milligrams
 8.333	12.000	mg-sunactive-mg	SunActive Magnesium (a micronized, microencapsulated form of trimagnesium orthophosphate), in milligrams
 8.333	11.955	mg-mg-chloride-hexahydrate	Magnesium chloride (hexahydrate, H12Cl2MgO6), in milligrams
 8.621	11.552	mg-mg-malate-trihydrate	Magnesium malate (MgC4H4O5.3H2O), in milligrams
 8.772	11.444	mg-mg-glycerophosphate-hydrate	Magnesium glycerophosphate anhydrous (C\xE2\x82\x83H\xE2\x82\x87MgO\xE2\x82\x86P.H2O, C3H9MgO7P), in milligrams
 8.850	11.336	mg-mg-citrate-dibasic	Magnesium citrate dibasic (C6H6MgO7), in milligrams
 8.850	11.334	mg-mg-acetate-tetrahydrate	Magnesium acetate tetrahydrate (Mg(CH3COO)2.4H2O), in milligrams
 9.804	10.192	mg-mg-lactate-dihydrate	Magnesium lactate dihydrate (C6H14MgO8), in milligrams
 10.101	9.861	mg-mg-sulfate-heptahydrate	Magnesium sulfate heptahydrate (MgSO4.7H2O) a.k.a. Epsom salt, in milligrams
 11.236	8.916	mg-mg-taurate	Magnesium taurate (C4H12MgN2O6S2), in milligrams
 11.494	8.664	mg-mg-pidolate	Magnesium pidolate (C10H12MgN2O6), in milligrams
 12.048	8.253	mg-mg-l-threonate	Magnesium L-threonate (C8H14MgO10), in milligrams
 15.385	6.489	mg-mg-ascorbate-dihydrate	Magnesium ascorbate hydrate (C12H14MgO12) [anhydrous and dihydrate are the most common hydrate forms of Mg-ascorbate at room temp], in milligrams
 17.857	5.618	mg-mg-gluconate-hydrate	Magnesium gluconate dihydrate (C12H26MgO16), in milligrams
 18.519	5.394	mg-mg-gluconate-dihydrate	Magnesium gluconate dihydrate (C12H26MgO16), in milligrams
 25.000	3.963	mg-mg-citrate-nonahydrate	Magnesium citrate nonahydrate ((C6H5O7)2Mg3 \xC2\xB7 9H2O, C12H28Mg3O23) [most common hydrate form of Mg-citrate at room temp], in milligrams

=head1 HOMEPAGE

Please visit the project's homepage at L<https://metacpan.org/release/App-MineralUtils>.

=head1 SOURCE

Source repository is at L<https://github.com/perlancar/perl-App-MineralUtils>.

=head1 AUTHOR

perlancar <perlancar@cpan.org>

=head1 CONTRIBUTING


To contribute, you can send patches by email/via RT, or send pull requests on
GitHub.

Most of the time, you don't need to build the distribution yourself. You can
simply modify the code, then test via:

 % prove -l

If you want to build the distribution (e.g. to try to install it locally on your
system), you can install L<Dist::Zilla>,
L<Dist::Zilla::PluginBundle::Author::PERLANCAR>,
L<Pod::Weaver::PluginBundle::Author::PERLANCAR>, and sometimes one or two other
Dist::Zilla- and/or Pod::Weaver plugins. Any additional steps required beyond
that are considered a bug and can be reported to me.

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2024 by perlancar <perlancar@cpan.org>.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=head1 BUGS

Please report any bugs or feature requests on the bugtracker website L<https://rt.cpan.org/Public/Dist/Display.html?Name=App-MineralUtils>

When submitting a bug or request, please include a test-file or a
patch to an existing test-file that illustrates the bug or desired
feature.

=cut
