;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.006

name=App-KDEActivityUtils

[GenPericmdScript / GenPericmdScript get-current-kde-activities]
url=/Desktop/XWindowManager/Util/move_windows_to_kde_activity
enable_log=1
read_config=0
read_env=0

[GenPericmdScript / GenPericmdScript getkact]
name=getkact
summary=Shorter alias for get-current-kde-activity
url=/Desktop/KDEActivity/Util/get_current_kde_activity
enable_log=1
read_config=0
read_env=0

[GenPericmdScript / GenPericmdScript list-kde-activities]
url=/Desktop/KDEActivity/Util/list_kde_activities
enable_log=1
read_config=0
read_env=0

[GenPericmdScript / GenPericmdScript set-current-kde-activity]
url=/Desktop/KDEActivity/Util/set_current_kde_activity
enable_log=1
read_config=0
read_env=0

[GenPericmdScript / GenPericmdScript setkact]
name=setkact
summary=Shorter alias for set-current-kde-activity
url=/Desktop/KDEActivity/Util/set_current_kde_activity
enable_log=1
read_config=0
read_env=0

[InsertExecsList]

[@Author::PERLANCAR]
:version=0.610

[Prereqs / TestRequires]
;Test::More=0.98

[Prereqs]
perl=5.010001
strict=0
warnings=0
Exporter=5.57
Log::ger=0.038

[Prereqs / DevelopX_spec]
-phase=develop
-relationship=x_spec
Rinci=1.1.102
