---
abstract: 'Do not "return" in mapping blocks (map, grep)'
author:
  - hogashi
build_requires:
  Perl::Critic: '0'
  Test2::V0: '0'
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.1.29, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-Policy-ControlStructures-ProhibitReturnInMappingBlock
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Perl::Critic::Policy::ControlStructures::ProhibitReturnInMappingBlock:
    file: lib/Perl/Critic/Policy/ControlStructures/ProhibitReturnInMappingBlock.pm
    version: '0.02'
requires:
  List::Util: '0'
  Perl::Critic::Policy: '0'
  Perl::Critic::Utils: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/hogashi/Perl-Critic-Policy-ControlStructures-ProhibitReturnInMappingBlock/issues
  homepage: https://github.com/hogashi/Perl-Critic-Policy-ControlStructures-ProhibitReturnInMappingBlock
  repository: https://github.com/hogashi/Perl-Critic-Policy-ControlStructures-ProhibitReturnInMappingBlock.git
version: '0.02'
x_contributors:
  - 'hogashi <azuma.ginkakuji@gmail.com>'
  - 'utgwkk <utagawakiki@gmail.com>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
