---
abstract: 'CHI Storage Driver for PAGI::FastAPI Rate Limiting'
author:
  - 'Mohammad Sajid Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '1.302'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PAGI-FastAPI-RateLimit-Driver-CHI
no_index:
  directory:
    - t
    - inc
provides:
  PAGI::FastAPI::RateLimit::Driver::CHI:
    file: lib/PAGI/FastAPI/RateLimit/Driver/CHI.pm
    version: v0.0.1
requires:
  PAGI::FastAPI: v1.0.0
  perl: '5.036'
resources:
  bugtracker: https://github.com/manwar/PAGI-FastAPI-RateLimit-Driver-CHI/issues
  repository: https://github.com/manwar/PAGI-FastAPI-RateLimit-Driver-CHI.git
version: v0.0.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
