name    = Test2-Harness2-ChildSubReaper
author  = Chad Granum <exodist@cpan.org>
license = Perl_5
copyright_holder = Chad Granum

[RewriteVersion] ; sets dist version from main module's $VERSION
[License]
[ManifestSkip]
[Manifest]
[NextRelease]

[GatherDir]
exclude_filename = LICENSE
exclude_filename = Makefile.PL
exclude_filename = README
exclude_filename = cpanfile

[PodSyntaxTests]
[TestRelease]

[MetaResources]
bugtracker.web  = https://github.com/Test-More/Test2-Harness2-ChildSubReaper/issues
repository.url  = https://github.com/Test-More/Test2-Harness2-ChildSubReaper.git
repository.web  = https://github.com/Test-More/Test2-Harness2-ChildSubReaper
repository.type = git

[Prereqs]
perl     = 5.014000
XSLoader = 0
Exporter = 0
strict   = 0
warnings = 0

[Prereqs / TestRequires]
Test2::V0 = 0.000163
POSIX     = 0

[Prereqs / ConfigureRequires]
ExtUtils::MakeMaker = 0

[MakeMaker::Awesome]
:version = 0.26
delimiter = |
header = |use Config qw/%Config/;

[CPANFile]
[MetaYAML]
[MetaJSON]

; authordep Pod::Markdown
[ReadmeFromPod]
filename = lib/Test2/Harness2/ChildSubReaper.pm
type = text
readme = README

[CopyFilesFromBuild]
copy = LICENSE
copy = cpanfile
copy = README
copy = Makefile.PL

[Git::Check]
allow_dirty = Makefile.PL
allow_dirty = README
allow_dirty = cpanfile
allow_dirty = LICENSE
allow_dirty = Changes

[Git::Commit]
allow_dirty = Makefile.PL
allow_dirty = README
allow_dirty = cpanfile
allow_dirty = LICENSE
allow_dirty = Changes

[Git::Tag]

[FakeRelease]

[BumpVersionAfterRelease]

[Git::Commit / Commit_Changes]
munge_makefile_pl = true
allow_dirty_match = ^lib
allow_dirty = Makefile.PL
allow_dirty = README
allow_dirty = cpanfile
allow_dirty = LICENSE
commit_msg = Automated Version Bump
