---
abstract: 'Google Cloud Pub/Sub V1 API Client'
author:
  - 'C.J. Collier <cjac@google.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Google-Cloud-PubSub-V1
no_index:
  directory:
    - t
    - inc
requires:
  Google::Api::Common: '0.01'
  Google::Auth: '0.02'
  Google::gRPC::Client: '0.02'
  Log::Any: '0'
  Moo: '0'
  Protobuf: '0.05'
  perl: '5.008003'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
