---
X_No_Archive: Yes
abstract: 'The Bluesky Social Network'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  Test2::V0: '0'
configure_requires:
  Module::Build::Tiny: '0'
dynamic_config: 0
generated_by: 'App::mii v1.0.0, CPAN::Meta::Converter version 2.150012'
keywords: []
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bluesky
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
optional_features:
  websockets:
    description: 'Websocket based streaming services'
    requires:
      Codec::CBOR: '0'
      Mojo::UserAgent: '0'
provides:
  Bluesky:
    file: lib/Bluesky.pm
    version: '1.01'
recommends:
  Mojo::UserAgent: '0'
requires:
  At: '0'
  HTTP::Tiny: '0'
  Mozilla::CA: '0'
  Path::Tiny: '0'
  URI: '0'
  URI::QueryParam: '0'
  perl: v5.42.0
resources:
  bugtracker: https://github.com/sanko/Bluesky.pm/issues
  homepage: https://github.com/sanko/Bluesky.pm
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/sanko/Bluesky.pm.git
version: '1.01'
x_ignore:
  - github
  - .gitignore
  - .tidyallrc
  - .clang-format
  - .github/**
  - session.json
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
