---
abstract: 'Bindings for librtmidi - Realtime MIDI library'
author:
  - 'John Barrett <john@jbrt.org>'
build_requires:
  Future::AsyncAwait: '0'
  Future::IO: '0'
  Proc::Find: '0'
  Test2::Require::Module: '0'
  Test2::V0: '0'
  Test::Lib: '0'
  ok: '0'
  perl: v5.26.0
configure_requires:
  Alien::RtMidi: '0.12'
  ExtUtils::MakeMaker: '0'
  FFI::Build::MM: '0.83'
  perl: v5.26.0
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.036, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MIDI-RtMidi-FFI
no_index:
  directory:
    - examples
    - t
    - xt
  package:
    - RtMidiWrapper
provides:
  MIDI::RtMidi::FFI:
    file: lib/MIDI/RtMidi/FFI.pm
    version: '0.12'
  MIDI::RtMidi::FFI::AbstractDevice:
    file: lib/MIDI/RtMidi/FFI/AbstractDevice.pm
    version: '0.12'
  MIDI::RtMidi::FFI::Device:
    file: lib/MIDI/RtMidi/FFI/Device.pm
    version: '0.12'
  MIDI::RtMidi::FFI::Device::In:
    file: lib/MIDI/RtMidi/FFI/Device/In.pm
    version: '0.12'
  MIDI::RtMidi::FFI::Device::Out:
    file: lib/MIDI/RtMidi/FFI/Device/Out.pm
    version: '0.12'
  RtMidiIn:
    file: lib/MIDI/RtMidi/FFI/Device.pm
    version: '0.12'
  RtMidiOut:
    file: lib/MIDI/RtMidi/FFI/Device.pm
    version: '0.12'
requires:
  FFI::CheckLib: '0.25'
  FFI::Platypus: '2.00'
  FFI::Platypus::Buffer: '0'
  FFI::Platypus::Memory: '0'
  FFI::Platypus::Record: '0'
  Feature::Compat::Class: '0'
  IO::Handle: '0'
  IO::Socket: '0'
  MIDI::Stream: '0.005'
  MIDI::Stream::Decoder: '0'
  MIDI::Stream::Encoder: '0'
  MIDI::Stream::Tables: '0'
  Time::HiRes: '0'
  experimental: '0'
  perl: v5.26.0
resources:
  bugtracker: https://codeberg.org/jbarrett/Alien-RtMidi/issues
  homepage: https://codeberg.org/jbarrett/Alien-RtMidi/
  repository: https://codeberg.org/jbarrett/Alien-RtMidi.git
version: '0.12'
x_generated_by_perl: v5.42.0
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
