From: "X. Ample" <example@example.com>
To: example@example.org
Subject: this is some message
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary=123

--123
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

This is from Ricardo Julián Besteiro Signes.  He likes Queensrÿche.

--123
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

This is from Ricardo Julian Besteiro Signes.  He likes Queensryche.

--123--

