name                = App-PDFLibrarian
author              = Karl Wette <karl.wette@cpan.org>
license             = GPL_3
copyright_holder    = Karl Wette
copyright_year      = 2016
version             = 6.0.2

[GitHub::Meta]

[@Filter]
-bundle = @Basic
-remove = MakeMaker
-remove = Readme

[MakeMaker::Awesome]

[CheckBin / editor]
bin = editor

[CheckBin / gs]
bin = gs

[CheckBin / pdftotext]
bin = pdftotext

[CheckBin / wx-config]
bin = wx-config

[CheckBin / xclip]
bin = xclip

[CheckBin / xdg-open]
bin = xdg-open

; authordep IO::Scalar            2.111
; authordep Pod::Markdown::Github 0.04
; authordep Pod::Select           1.67

[Run::BeforeBuild]
run = perl maint/generate-README.pl

[PkgVersion]

[ExecDir]
dir = bin

[PruneFiles]
match = ^maint/

[Prereqs]
perl                = 5.018
Capture::Tiny       = 0.48
Carp::Assert        = 0.22
Clipboard           = 0.28
Config::IniFiles    = 3.000003
File::BaseDir       = 0.09
File::MimeInfo      = 0.34
File::ShareDir      = 1.00
JSON                = 4.10
LWP                 = 6.76
PDF::API2           = 2.045
Parallel::Iterator  = 1.002
Pod::Usage          = 2.03
System::Info        = 0.067
Text::BibTeX        = 0.89
Text::CSV::Encoded  = 0.25
Text::Unidecode     = 1.30
URI                 = 5.27
URI::Encode         = 1.1.1
XML::LibXML         = 2.0134
XML::LibXSLT        = 2.002001

[Git::Check]

[Git::Tag]
tag_format = v%V
