---
abstract: 'Minimalist high-performance async control flow for EV'
author:
  - vividsnow
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.96'
configure_requires:
  EV: '4.37'
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: EV-Future
no_index:
  directory:
    - t
    - inc
provides:
  EV::Future:
    file: lib/EV/Future.pm
    version: '0.06'
  EV::Future::Handle:
    file: lib/EV/Future.pm
    version: '0.06'
requires:
  EV: '4.37'
  perl: '5.014000'
resources:
  repository: https://github.com/vividsnow/perl5-ev-future.git
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
