---
abstract: "PHP's Mink inspired multi-protocol web-testing library for Perl"
author:
  - 'Erik Huelsmann <ehuels@gmail.com>'
build_requires:
  File::Find: '0'
  File::Util: '0'
  Test2::V1: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Weasel-Driver-Selenium4
requires:
  Carp::Clan: '0'
  MIME::Base64: '0'
  Moose: '0'
  Selenium::Client: '0'
  Time::HiRes: '0'
  Weasel: '0'
  Weasel::DriverRole: '0.03'
  namespace::autoclean: '0'
  perl: v5.12.0
resources:
  bugtracker: https://github.com/perl-weasel/weasel-driver-selenium4/issues
  repository: https://github.com/perl-weasel/weasel-driver-selenium4.git
version: '0.02'
x_contributors:
  - 'renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>'
x_generated_by_perl: v5.38.2
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
