---
abstract: 'check if a value is any of the given values'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  Test::Code::TidyAll: '0'
  Test::More: '1.00'
  Test::Perl::Critic: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-IsAny
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Data::Dumper: '0'
  Exporter: '0'
  List::MoreUtils: '0'
  Test::Builder: '1.001'
resources:
  bugtracker: https://github.com/szabgab/Test-IsAny
  repository: https://github.com/szabgab/Test-IsAny.git
version: '0.01'
x_contributors:
  - 'Gabor Szabo <szabgab@cpan.org>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
