apiVersion: v1
kind: ConfigMap
metadata:
  name: zitadel-auth-proxy
  namespace: zitadel
data:
  ZITADEL_ISSUER: https://zitadel.avatar.conflict.industries
  ZITADEL_AUDIENCE: ""
  ZITADEL_REQUIRED_SCOPES: ""
  UPSTREAM_BASE: http://my-app.default.svc.cluster.local:8080
