---
abstract: 'DKIM2 signing and verification for email'
author:
  - 'Bron Gondwana <brong@fastmailteam.com>'
build_requires:
  Path::Tiny: '0'
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mail-DKIM2
no_index:
  directory:
    - t
    - inc
recommends:
  Mail::AuthenticationResults: '0'
  Mail::Milter::Authentication: '0'
  Net::SMTP: '0'
  Sendmail::PMilter: '1.28'
  Sys::Syslog: '0'
requires:
  Algorithm::Diff: '0'
  Carp: '0'
  CryptX: '0.060'
  Email::MIME: '0'
  Exporter: '0'
  File::Path: '0'
  JSON: '0'
  List::Util: '0'
  MIME::Base64: '0'
  Net::DNS: '0'
  perl: '5.020000'
resources:
  bugtracker: https://github.com/dkim2wg/interop/issues
  repository: https://github.com/dkim2wg/interop.git
version: '0.10'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
