---
abstract: 'getopts implementation that follows POSIX utility guidelines'
author:
  - 'Sven Willenbuecher <sven.willenbuecher@gmx.de>'
build_requires:
  Config: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Spec::Functions: '0'
  Test::Fatal: '0'
  Test::More: '1.001005'
  Test::Needs: '0'
  Test::Output: '0'
  Test::Script: '1.31'
  Test::Warn: '0'
configure_requires:
  CPAN::Meta: '0'
  ExtUtils::MakeMaker: '6.76'
  ExtUtils::MakeMaker::CPANfile: '0.09'
  File::Spec::Functions: '0'
  strict: '0'
  warnings: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Getopt-Guided
no_index:
  directory:
    - t
    - inc
provides:
  Getopt::Guided:
    file: lib/Getopt/Guided.pm
    version: v3.1.2
requires:
  Carp: '1.32'
  File::Basename: '0'
  File::Spec::Functions: '0'
  perl: '5.010000'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://codeberg.org/XSven/Getopt-Guided/issues
  repository: https://codeberg.org/XSven/Getopt-Guided.git
version: v3.1.2
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
