---
abstract: 'Consulta e emissão de NFS-e (Nota Fiscal de Serviços Eletrônica) via API REST do Emissor Nacional (Sefin)'
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-BR-NFSe
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Crypt::PK::RSA: '0'
  Digest::SHA: '0'
  Encode: '0'
  HTTP::Tiny: '0'
  IO::Compress::Gzip: '0'
  MIME::Base64: '0'
  Test::More: '0'
resources:
  bugtracker: https://github.com/garu/Business-BR-NFSe/issues/
  license: http://dev.perl.org/licenses/
  repository: https://github.com/garu/Business-BR-NFSe
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
