---
abstract: 'Automatically hand off tickets while an owner is away'
author:
  - 'Christian Mehlmauer'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: gpl_3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-AwayMode
no_index:
  directory:
    - etc
    - html
    - inc
    - t
requires:
  perl: 5.36.0
resources:
  bugtracker: https://github.com/firefart/RT-Extension-AwayMode/issues
  license: https://opensource.org/licenses/gpl-3.0.html
  repository: https://github.com/firefart/RT-Extension-AwayMode.git
version: '0.01'
x_module_install_rtx_version: '0.45'
x_requires_rt: 6.0.0
