---
abstract: 'make a hole to the original main compartment in the Safe compartment'
author:
  - 'Sey Nakajima <nakajima@netstock.co.jp>'
  - 'Brian McCauley <nobull@cpan.org>'
  - 'Todd Rinaldo <toddr@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.40'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Safe-Hole
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.014'
resources:
  bugtracker: https://github.com/cpan-authors/Safe-Hole/issues
  homepage: https://github.com/cpan-authors/Safe-Hole
  repository: https://github.com/cpan-authors/Safe-Hole.git
version: '0.15'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
