name    = File-Rotate-Simple
author  = Robert Rothenberg <perl@rhizomnic.com>
license = Artistic_2_0
copyright_holder = Robert Rothenberg
copyright_year   = 2015-2026

[Keywords]
keyword = devops
keyword = file
keyword = logrotate
keyword = logs
keyword = ops

[GatherDir]
exclude_match = cpanfile*
exclude_filename = LICENSE
exclude_filename = SECURITY.md
exclude_filename = doap.xml

[PruneCruft]
[CPANFile]
[License]
[DOAP]
[ExecDir]
[ShareDir]
[MakeMaker]
[Manifest]
[TestRelease]
[CheckExtraTests]
[ConfirmRelease]
[SigStore::SignRelease]

[RecommendedPrereqs]
[AutoPrereqs]
;; [RemovePrereqs]

[StaticInstall]
mode = auto
dry_run = 0

[Prereqs / BuildRequires ]
-phase = build
-relationship = recommends
ExtUtils::MakeMaker = 7.22
Module::Metadata = 1.000015

[Prereqs / DevelopRequires ]
-phase = develop
-relationship = requires
Software::Security::Policy::Individual = 0.10
Test::CPAN::Changes = 0
Test::Vars = 0.015

[Prereqs / RunRequires]
-phase = runtime
-relationship = requires
List::Util = 1.43

; [EnsurePrereqsInstalled]
; :version = 0.003
; type = requires
; type = recommends

[AutomationPolicy]
template = human_supervised

[SecurityPolicy]
; authordep Software::Security::Policy::Individual
-policy = Individual
timeframe = 2 weeks
perl_support_years = 10
git_url = https://github.com/robrwo/File-Rotate-Simple
report_url = https://github.com/robrwo/File-Rotate-Simple/security/advisories

[GitHub::Meta]
repo = robrwo/File-Rotate-Simple.git

[PodWeaver]
; authordep Pod::Weaver::Plugin::AppendPrepend
; authordep Pod::Weaver::Section::Contributors
; authordep Pod::Weaver::Section::SourceGitHub

[UsefulReadme]
; authordep Pod::Markdown::Github
type     = gfm
filename = README.md
location = build

[CopyFilesFromBuild]
copy = LICENSE
copy = README.md
copy = SECURITY.md
copy = cpanfile
copy = doap.xml

[PruneFiles]
match = ~$

[Metadata]
x_authority    = cpan:RRWO

[MetaProvides::Package]
[MetaJSON]
[MetaYAML]

; authordep Test::Warnings

[PodSyntaxTests]
[Test::DistManifest]
; authordep Test::DistManifest
[Test::CleanNamespaces]
; authordep Test::CleanNamespaces
[Test::EOF]
; authordep Test::EOF
[Test::EOL]
:version = 0.14
[Test::Fixme]
[Test::MinimumVersion]
[Test::NoTabs]
[Test::Perl::Critic]
critic_config = xt/etc/perlcritic.rc

[Test::Pod::Coverage::Configurable]
[Test::Pod::LinkCheck]
[Test::Portability]
[Test::TrailingSpace]
; authordep Test::TrailingSpace
filename_regex = \.(?:p[lm]|pod)\z
[Test::Kwalitee]
; authordep Test::Kwalitee
skiptest = use_strict

[Test::CPAN::Changes]
; authordep Test::CPAN::Changes
[Test::UnusedVars]
[Test::MixedScripts]
[MojibakeTests]
[Test::PodSpelling]

[Test::Version]
[Test::Compile]
; authordep Test::Compile
filename = xt/00-compile.t

[Test::CVE]

[Test::ReportPrereqs]
:version = 0.022
version_extractor = Module::Metadata
verify_prereqs = 1

[@Git]
allow_dirty = dist.ini
push_to     = origin master:master
tag_format  = %v
commit_msg  = %v%n%n%c

[Git::Contributors]
:version = 0.019
remove   = robrwo

[RewriteVersion]
[NextRelease]
[BumpVersionAfterRelease]

[Git::Commit / Commit_Changes] ; commit Changes (for new dev)
allow_dirty_match = ^lib/
commit_msg = Commit Changes and bump $VERSION
