=pod

=encoding utf8

=head1 NAME

RosettaCode - A tool to extract RosettaCode's code samples

=head1 SYNOPSIS

From the command line:

    $ git clone https://github.com/acmeism/RosettaCodeData
    $ cd RosettaCodeData
    $ rosettacode           # or `make build`

=head1 DESCRIPTION

RosettaCode.org is a fantastic wiki that contains ~1200 programming tasks, each implemented in up to ~900 programming languages. There are over 100,000 code samples!

This tool aims to make it easier for programmers to obtain and try the various code samples.

At this point, the main function is to extract the code examples and organize them into this git repository on GitHub:

=over

=item * L<https://github.com/acmeism/RosettaCodeData|https://github.com/acmeism/RosettaCodeData>

=back

The C<make build> command in that repository requires this CPAN module, which does all the work.

=head1 COPYRIGHT AND LICENSE

Copyright 2013-2023 by Ingy döt Net

This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

See L<http://www.perl.com/perl/misc/Artistic.html|http://www.perl.com/perl/misc/Artistic.html>

=cut
