=pod

=encoding UTF-8

=head1 NAME

Bot::Cobalt::Plugin::Bitly - Bot::Cobalt plugin for auto-shortening URL via Bit.ly

=head1 VERSION

version 0.001

=head1 SYNOPSIS

   ## In plugins.conf
   Bitly:
      Module: Bot::Cobalt::Plugin::Bitly
      Opts:
         min_length: <minumum URL length> # default 160
         creds:
            user_name:        <bit.ly user name>
            user_api_key:     <bit.ly user api key>
            end_user_name:    <bit.ly end-user name>    # optional
            end_user_api_key: <bit.ly end-user api key> # optional
            domain:           <domain name to use>      # optional

=head1 DESCRIPTION

A L<Bot::Cobalt> plugin.

Automatically takes any URLs in a given message, and if they are too long,
shortens them via the bit.ly webservice (L<WebService::Bitly>), and then 
broadcasts the newly shortened URL to the channel.

=head1 SEE ALSO

L<WebService::Bitly>

=head1 AUTHOR

Scott Miller <scott.j.miller@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2014 by Scott Miller.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

