---
abstract: 'parent entry point and shared make-target methods for MakeMaker plugins'
author:
  - 'Andrew Speer <andrew.speer@isolutions.com.au>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Path: '0'
  File::Temp: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Tie::File: '0'
  version: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ASPEER-MakeMaker
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Cwd: '0'
  Data::Dumper: '0'
  Exporter: '0'
  ExtUtils::MM: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Spec: '0'
  File::Temp: '0'
  FindBin: '0'
  IO::File: '0'
  Software::LicenseUtils: '0'
  Tie::File: '0'
  base: '0'
  perl: '5.008'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/aspeer/pm-ASPEER-MakeMaker/issues
  homepage: https://github.com/aspeer/pm-ASPEER-MakeMaker
  repository: https://github.com/aspeer/pm-ASPEER-MakeMaker.git
version: '1.012'
x_authority: cpan:ASPEER
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
