---
abstract: Amazon::API::Help
author:
  - 'Rob Lauer <rclauer@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Amazon-API-Help
no_index:
  directory:
    - t
    - inc
provides:
  Amazon::API::Help:
    file: lib/Amazon/API/Help.pm
    version: v1.0.3
requires:
  Amazon::API::BuildInfo: v2.6.0
  CLI::Simple: v2.2.1
  CLI::Simple::Constants: v2.2.1
  CLI::Simple::Utils: v2.2.1
  File::ShareDir: '1.118'
  Pod::HTML2Pod: '4.05'
  Template: '3.102'
  Text::ASCIITable: '0.22'
  perl: '5.010'
resources:
  bugtracker: https://github.com/rlauer6/Amazon-API-Help/issues
  homepage: https://github.com/rlauer6/Amazon-API-Help
  repository: https://github.com/rlauer6/Amazon-API-Help
version: v1.0.3
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
