[@CorePrep]

[-SingleEncoding]

[Name]
[Version]

[Region  / prelude]

[Generic / SYNOPSIS]
[Generic / DESCRIPTION]
[Generic / OVERVIEW]

[Collect / ATTRIBUTES]
command = attr

[Collect / METHODS]
command = method

[Collect / FUNCTIONS]
command = func

[Leftovers]

[SeeAlso]
[Bugs]

[Region  / postlude]

; [Authors]
[GenerateSection / AUTHORS ]
text = Current Maintainers:
text =
text = =over 4
text =
text = =item *
text =
text = George S. Baugh <teodesian@gmail.com>
text =
text = =back
text =
text = Original author, of Perl::Critic::Policy::Plicease::ProhibitLeadingZeros:
text =
text = =over 4
text =
text = =item *
text =
text = Graham Ollis <plicease@cpan.org>
text =
text = =back

[Contributors]
[GenerateSection / COPYRIGHT AND LICENSE]
text = This software is copyright (c) 2019-2024 by Graham Ollis, as
text = Perl::Critic::Policy::Plicease::ProhibitLeadingZeros in Perl-Critic-Plicease.
text =
text = Modifications are copyright (c) 2026 by Troglodyne LLC.
text =
text = This is free software; you can redistribute it and/or modify it under
text = the same terms as the Perl 5 programming language system itself.

[-Transformer]
transformer = List
