requires 'Path::Tiny', '0.076';
requires 'Ref::Util';
requires 'File::Glob';
requires 'Exporter::Tiny', 1;

on test => sub {
    requires 'File::Share', '0.03';
    requires 'Test2::Tools::Spec';
    requires 'Test2::V0';
};

on develop => sub {
    requires 'Test::Pod';
};
