---
abstract: 'Keep files updated in a repository by weaving them from POD documents and other files, and then testing their content.'
author:
  - 'Mikko Koivunalho <mikkoi@cpan.org>'
build_requires:
  English: '0'
  File::Find: '0'
  File::Spec: '0'
  FindBin: '1.51'
  Module::Load: '0'
  Test2::Suite: '1.302200'
  Test2::Tools::GenTemp: '1.302200'
  Test2::Tools::Subtest: '0'
  Test2::V0: '0'
  Test2::V1: '1.302200'
  Test::DZil: '0'
  Test::Script: '1.26'
  lib: '0'
  perl: '5.010'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
keywords:
  - dist
  - zilla
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-WeaveFile
requires:
  Carp: '0'
  Data::Section: '0.004'
  Dist::Zilla::App: '0'
  Dist::Zilla::File::InMemory: '0'
  Dist::Zilla::Role::FileGatherer: '0'
  Dist::Zilla::Role::Plugin: '0'
  Dist::Zilla::Role::PrereqSource: '0'
  Dist::Zilla::Role::TextTemplate: '0'
  List::Util: '0'
  Moose: '0'
  Path::Tiny: '0'
  Pod::Markdown: '0'
  Sub::Exporter::ForMethods: '0'
  Template: '0'
  Test::Perl::Critic: '0'
  YAML: '0'
  feature: '0'
  namespace::autoclean: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-WeaveFile
  homepage: https://metacpan.org/release/Dist-Zilla-Plugin-WeaveFile
  repository: git://github.com/mikkoi/dist-zilla-plugin-weavefile.git
version: '0.002'
x_generated_by_perl: v5.34.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
