[@CorePrep]

[-SingleEncoding]

;; [-Transformer]
;; transformer = List

[Region  / prelude]

[Name]
[Version]

[Generic / SYNOPSIS]

[Generic / STATUS]

[Generic / DESCRIPTION]

[Collect / CONFIG VARIABLES]
command = attr

[Collect / PARAMETERS]
command = param

[Collect / METHODS]
command = method


[Leftovers]

[Region  / postlude]

[SourceGitHub]
[Bugs]
header = SUPPORT

[Authors]

[Contributors]

[Legal]

[-AppendPrepend]
