---
abstract: 'Service layer orchestrator for authentication, sessions, and user data'
author:
  - 'Bruce Van Allen <bva@cruzio.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Concierge
no_index:
  directory:
    - t
    - inc
provides:
  Concierge:
    file: lib/Concierge.pm
    version: v0.7.0
  Concierge::Base:
    file: lib/Concierge/Base.pm
    version: v0.7.0
  Concierge::Setup:
    file: lib/Concierge/Setup.pm
    version: v0.7.0
  Concierge::User:
    file: lib/Concierge/User.pm
    version: v0.7.0
requires:
  Carp: '0'
  Concierge::Auth: '0'
  Concierge::Sessions: '0'
  Concierge::Users: '0'
  JSON::PP: '0'
  Params::Filter: '0.014'
  perl: '5.036'
resources:
  bugtracker: https://github.com/bwva/Concierge/issues
  repository: https://github.com/bwva/Concierge.git
version: v0.7.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
