---
abstract: 'Interface to L<https://open-meteo.com> for historical weather data'
author:
  - 'Nigel Horne <njh@nigelhorne.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Glob: '0'
  File::Slurp: '0'
  File::stat: '0'
  Geo::Location::Point: '0.09'
  IPC::System::Simple: '0'
  POSIX: '0'
  Readonly: '0'
  Test::Carp: '0'
  Test::Compile: '0'
  Test::DescribeMe: '0'
  Test::MockModule: '0'
  Test::Most: '0'
  Test::Needs: '0'
  Test::NoWarnings: '0'
  WWW::RT::CPAN: '0'
  autodie: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Weather-Meteo
no_index:
  directory:
    - t
    - inc
requires:
  CHI: '0'
  Encode: '0'
  ExtUtils::MakeMaker: '6.64'
  JSON::MaybeXS: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  Object::Configure: '0'
  Params::Get: '0.13'
  Params::Validate::Strict: '0'
  Return::Set: '0'
  Scalar::Util: '0'
  Time::HiRes: '0'
  URI: '0'
  constant: '0'
  perl: '5.006002'
resources:
  bugtracker: https://github.com/nigelhorne/Weather-Meteo/issues
  repository: git://github.com/nigelhorne/Weather-Meteo.git
version: '0.13'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
