name    = IPC-Manager-Client-SharedMem
author  = Chad Granum <exodist@cpan.org>
license = Perl_5
copyright_holder = Chad Granum

[RewriteVersion] ; sets dist version from main module's $VERSION
[License]
[ManifestSkip]
[Manifest]
[NextRelease]
[GatherDir]
exclude_match = ^xt/downstream      ; only run these tests locally
exclude_match = ^inc/               ; configure-time helpers, inlined into Makefile.PL
exclude_filename = LICENSE
exclude_filename = Makefile.PL
exclude_filename = cpanfile
exclude_filename = README
exclude_filename = README.md

[PodSyntaxTests]
[TestRelease]

[MetaResources]
bugtracker.web  = https://github.com/exodist/IPC-Manager-Client-SharedMem/issues
repository.url  = https://github.com/exodist/IPC-Manager-Client-SharedMem/
repository.type = git

[Prereqs]
perl             = 5.012000
parent           = 0
Carp             = 0
IPC::SysV        = 2.09
IPC::Manager     = 0.000033
Object::HashBase = 0.015

[Prereqs / TestRequires]
Test2::V0              = 1.302219
Test2::V1              = 1.302219
Test2::IPC             = 1.302219
Test2::API             = 1.302219
Test2::Require::Module = 1.302219

; authordep Dist::Zilla::Plugin::MakeMaker::Awesome
[MakeMaker::Awesome]
header_file = inc/configure-probe.pl
[CPANFile]
[MetaYAML]
[MetaJSON]

; authordep Pod::Markdown
[ReadmeFromPod / Markdown]
filename = lib/IPC/Manager/Client/SharedMem.pm
type = markdown
readme = README.md

[ReadmeFromPod / Text]
filename = lib/IPC/Manager/Client/SharedMem.pm
type = text
readme = README

[CopyFilesFromBuild]
copy = LICENSE
copy = cpanfile
copy = README
copy = README.md
copy = Makefile.PL

[Git::Check]
allow_dirty = Makefile.PL
allow_dirty = README
allow_dirty = README.md
allow_dirty = cpanfile
allow_dirty = LICENSE
allow_dirty = Changes

[Git::Commit]
allow_dirty = Makefile.PL
allow_dirty = README
allow_dirty = README.md
allow_dirty = cpanfile
allow_dirty = LICENSE
allow_dirty = Changes

[Git::Tag]

[FakeRelease]

[BumpVersionAfterRelease]

[Git::Commit / Commit_Changes]
munge_makefile_pl = true
allow_dirty_match = ^lib
allow_dirty = Makefile.PL
allow_dirty = README
allow_dirty = README.md
allow_dirty = cpanfile
allow_dirty = LICENSE
commit_msg = Automated Version Bump
