=head1 Needed URLs

Details of a JiffyBox

 Verb: GET URL: /jiffyBoxes/<box_id>
 # curl https://api.jiffybox.de/<token>/v1.0/jiffyBoxes/<box_id>


new Jiffybox

 Verb: POST URL: /jiffyBoxes
 # curl -d <parameter> https://api.jiffybox.de/<token>/v1.0/jiffyBoxes

 required parameters:
 name         - max. 30 Symbols, not double
 planid       - id or name of a plan (/plans)
 backupid     - id of a backup (/backups)
 or
 distribution - (/distribution)

 optional parameters:
 password
 use_sshkey
 metadata

start/stop JiffyBox

 Verb: PUT URL: /jiffyBoxes/<box_id>
 # curl -X PUT -d <parameter> https://api.jiffybox.de/<token>/v1.0/jiffyBoxes/<box_id>

 required parameters:
 status   - START, SHUTDOWN, PULLPLUG, FREEZE, THAW

 optional parameters:
 planid   - required if THAW 
 metadata

delete JiffyBox

 DELETE URL:/jiffyBoxes/<Box-ID>
 curl -X DELETE https://api.jiffybox.de/<token>/v1.0/jiffyBoxes/<id>

