package Shipment::UPS::WSDL::RateTypes::ShipToPhoneType;
$Shipment::UPS::WSDL::RateTypes::ShipToPhoneType::VERSION = '3.05';
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns {'http://www.ups.com/XMLSchema/XOLTWS/Rate/v1.1'}

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(Shipment::UPS::WSDL::RateTypes::PhoneType);

# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{    # BLOCK to scope variables

    my %Number_of : ATTR(:get<Number>);

    __PACKAGE__->_factory(
        [   qw(        Number
              )
        ],
        {'Number' => \%Number_of,},
        {'Number' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',},
        {'Number' => 'Number',}
    );

}    # end BLOCK


1;

__END__

=pod

=encoding UTF-8

=head1 NAME

Shipment::UPS::WSDL::RateTypes::ShipToPhoneType

=head1 VERSION

version 3.05

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ShipToPhoneType from the namespace http://www.ups.com/XMLSchema/XOLTWS/Rate/v1.1.

=back

=head1 NAME

Shipment::UPS::WSDL::RateTypes::ShipToPhoneType

=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # Shipment::UPS::WSDL::RateTypes::ShipToPhoneType
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=head1 AUTHOR

Andrew Baerg <baergaj@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2018 by Andrew Baerg.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
