---
abstract: 'Fast KDL parser and emitter via libckdl'
author:
  - 'Davenonymous <perl@davenonymous.com>'
build_requires:
  Alien::ckdl: '0'
  Test::More: '0.88'
configure_requires:
  Alien::ckdl: '0'
  Devel::PPPort: '3.68'
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-KDL-XS
no_index:
  directory:
    - t
    - inc
requires:
  Alien::ckdl: '0'
  XSLoader: '0'
  perl: '5.012'
resources:
  bugtracker: https://github.com/Davenonymous/perl-kdl-xs/issues
  homepage: https://github.com/Davenonymous/perl-kdl-xs
  repository: https://github.com/Davenonymous/perl-kdl-xs.git
version: '0.001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
