---
abstract: 'Generate mock test data for DBIx::Class schemas'
author:
  - 'Mohammad Sajid Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  DBD::SQLite: '0'
  DBI: '0'
  ExtUtils::MakeMaker: '0'
  File::Temp: '0'
  IPC::Open3: '0'
  Symbol: '0'
  Test::Exception: '0'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Class-MockData
no_index:
  directory:
    - t
    - inc
provides:
  DBIx::Class::MockData:
    file: lib/DBIx/Class/MockData.pm
    version: '0.04'
requires:
  Carp: '0'
  DBIx::Class: '0.082841'
  File::Spec: '0'
  Scalar::Util: '0'
  perl: '5.016'
resources:
  bugtracker: https://github.com/manwar/DBIx-Class-MockData/issues
  repository: https://github.com/manwar/DBIx-Class-MockData.git
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
