---
abstract: 'Recursively find all reverse dependencies for a distribution or module'
author:
  - 'Dan Book <dbook@cpan.org>'
build_requires:
  File::Spec: '0'
  HTTP::Tiny: '0.014'
  Module::Metadata: '0'
  Test::More: '0.88'
  Test::RequiresInternet: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.037, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-CPAN-Dependents
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  App::CPAN::Dependents:
    file: lib/App/CPAN/Dependents.pm
    version: '1.002'
requires:
  Carp: '0'
  Exporter: '0'
  Getopt::Long::Modern: '0'
  MetaCPAN::Client: '2.037000'
  perl: '5.010001'
resources:
  IRC: irc://irc.perl.org/#metacpan
  bugtracker: https://github.com/Grinnz/App-CPAN-Dependents/issues
  homepage: https://github.com/Grinnz/App-CPAN-Dependents
  repository: https://github.com/Grinnz/App-CPAN-Dependents.git
version: '1.002'
x_contributors:
  - 'Dan Book <grinnz@gmail.com>'
  - 'Dan Book <grinnz@grinnz.com>'
x_generated_by_perl: v5.42.1
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: Artistic-2.0
