---
abstract: 'Abstract (virtual) methods for plain-Perl OO'
author:
  - 'Nigel Horne <njh@nigelhorne.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  IPC::System::Simple: '0'
  Moo: '0'
  Test::DescribeMe: '0'
  Test::Memory::Cycle: '0'
  Test::Mockingbird: '0'
  Test::Most: '0'
  Test::Needs: '0'
  Test::NoWarnings: '0'
  Test::Returns: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sub-Abstract
no_index:
  directory:
    - t
    - inc
requires:
  Attribute::Handlers: '0'
  Carp: '0'
  Params::Validate::Strict: '0.33'
  Readonly: '0'
  Return::Set: '0'
  perl: '5.008'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Sub-Abstract
  homepage: https://metacpan.org/pod/Sub::Abstract
  repository: git://github.com/nigelhorne/Sub-Abstract.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
