=pod

=head1 NAME

IUP::Canvas::Stipple - [special Canvas helper] Fill stipple for use with IUP::Canvas

=head1 SYNOPSIS

 $sti= IUP::Canvas::Stipple->new( [ [...], [...], [...] ] );     #1 param
 $sti= IUP::Canvas::Stipple->new( $w, $h );                      #2 params
 
 $value = $sti->Pixel($x, $y);
 $sti->Pixel($x, $y, $value);
 $sti->Width();
 $sti->Height();
 $sti->Data();
 
 $canvas->cdStipple($sti);
 $canvas->wdStipple($sti, $w_mm, $h_mm);
 $cursti = $canvas->cdGetStipple();

=head1 DESCRIPTION

B<IUP::Canvas::Bitmap> is a helper class used by L<IUP::Canvas> methods: L<cdStipple|IUP::Canvas/"cdStipple()">, L<wdStipple|IUP::Canvas/"wdStipple()"> and L<cdGetStipple|IUP::Canvas/"cdGetStipple()">

=head1 SEE ALSO

L<IUP::Canvas>

=cut