---
abstract: 'Asynchronous redis client using hiredis and EV'
author:
  - 'Daisuke Murase (typester)'
  - vividsnow
build_requires:
  Devel::Refcount: '0'
  ExtUtils::MakeMaker: '0'
  Test::Deep: '0'
  Test::More: '0.98'
  Test::RedisServer: '0.12'
  Test::TCP: '1.18'
configure_requires:
  EV::MakeMaker: '0'
  ExtUtils::MakeMaker: '6.64'
  File::Which: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.78, CPAN::Meta::Converter version 2.150013'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: EV-Redis
no_index:
  directory:
    - t
    - inc
    - t
    - xt
    - deps
    - src
requires:
  EV: '4.11'
  XSLoader: '0.02'
  perl: '5.012000'
resources:
  bugtracker: https://github.com/vividsnow/perl5-ev-redis/issues
  repository: https://github.com/vividsnow/perl5-ev-redis.git
version: '0.08'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
