---
abstract: 'NaCl compatible modern, easy-to-use library for encryption, decryption, signatures, password hashing and more'
author:
  - 'Alex J. G. Burzyński <ajgb@cpan.org>'
build_requires:
  Alien::Base::Wrapper: '2.15'
  Alien::Sodium: '2.000'
  Config: '0'
  Cwd: '0'
  Devel::Peek: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Spec: '0'
  Test::More: '0.88'
  strict: '0'
  utf8: '0'
  warnings: '0'
configure_requires:
  Alien::Base::Wrapper: '2.15'
  Alien::Sodium: '2.000'
  Config: '0'
  Devel::CheckLib: '0'
  ExtUtils::MakeMaker: '6.52'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.033, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-NaCl-Sodium
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Crypt::NaCl::Sodium:
    file: lib/Crypt/NaCl/Sodium.pm
    version: '2.003'
requires:
  Carp: '0'
  Sub::Exporter: '0'
  XSLoader: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/cpan-authors/crypt-nacl-sodium/issues
  homepage: https://github.com/cpan-authors/crypt-nacl-sodium
  repository: https://github.com/cpan-authors/crypt-nacl-sodium.git
version: '2.003'
x_contributors:
  - 'Brad Barden <perlmodules@5c30.org>'
  - 'Chase Whitener <capoeirab@cpan.org>'
  - 'Timothy Legge <timlegge@gmail.com>'
x_generated_by_perl: v5.42.0
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
