name = "App-Greple-wordle"

license       = "perl_5"
badges        = [ 'github-actions/test', 'metacpan' ]
authority     = "cpan:UTASHIRO"

module_maker   = "ModuleBuildTiny"
static_install = "auto"

[FileGatherer]
exclude_match = [
    "^.claude/",
    "^CLAUDE.md$",
    "^AGENTS.md$",
    "^tools/"
]

[release]
branch = "main"
