---
abstract: 'TCF v2.3 distribution: parser, validator, CMP-validator, and CLI'
author:
  - 'Tiago Peczenyj <tiago.peczenyj+cpan@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  IO::Compress::Gzip: '0'
  IO::Uncompress::Gunzip: '0'
  JSON::PP: '0'
  Test::Exception: '0.43'
  Test::More: '0.94'
  Test::Pod: '0'
  Test::Synopsis: '0'
  Test::Warn: '0.3'
  Time::Piece: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GDPR-IAB-TCFv2
no_index:
  directory:
    - t
    - inc
    - xt
    - bench
    - docs
provides:
  GDPR::IAB::TCFv2:
    file: lib/GDPR/IAB/TCFv2.pm
    version: '0.530'
  GDPR::IAB::TCFv2::BitField:
    file: lib/GDPR/IAB/TCFv2/BitField.pm
    version: '0.530'
  GDPR::IAB::TCFv2::BitUtils:
    file: lib/GDPR/IAB/TCFv2/BitUtils.pm
    version: '0.530'
  GDPR::IAB::TCFv2::CMPValidator:
    file: lib/GDPR/IAB/TCFv2/CMPValidator.pm
    version: '0.530'
  GDPR::IAB::TCFv2::Constants::Purpose:
    file: lib/GDPR/IAB/TCFv2/Constants/Purpose.pm
    version: '0.530'
  GDPR::IAB::TCFv2::Constants::RestrictionType:
    file: lib/GDPR/IAB/TCFv2/Constants/RestrictionType.pm
    version: '0.530'
  GDPR::IAB::TCFv2::Constants::SpecialFeature:
    file: lib/GDPR/IAB/TCFv2/Constants/SpecialFeature.pm
    version: '0.530'
  GDPR::IAB::TCFv2::Parser:
    file: lib/GDPR/IAB/TCFv2/Parser.pm
    version: '0.530'
  GDPR::IAB::TCFv2::Publisher:
    file: lib/GDPR/IAB/TCFv2/Publisher.pm
    version: '0.530'
  GDPR::IAB::TCFv2::PublisherRestrictions:
    file: lib/GDPR/IAB/TCFv2/PublisherRestrictions.pm
    version: '0.530'
  GDPR::IAB::TCFv2::PublisherTC:
    file: lib/GDPR/IAB/TCFv2/PublisherTC.pm
    version: '0.530'
  GDPR::IAB::TCFv2::RangeSection:
    file: lib/GDPR/IAB/TCFv2/RangeSection.pm
    version: '0.530'
  GDPR::IAB::TCFv2::Validator:
    file: lib/GDPR/IAB/TCFv2/Validator.pm
    version: '0.530'
  GDPR::IAB::TCFv2::Validator::Failure:
    file: lib/GDPR/IAB/TCFv2/Validator/Failure.pm
    version: '0.530'
  GDPR::IAB::TCFv2::Validator::Reason:
    file: lib/GDPR/IAB/TCFv2/Validator/Reason.pm
    version: '0.530'
  GDPR::IAB::TCFv2::Validator::Result:
    file: lib/GDPR/IAB/TCFv2/Validator/Result.pm
    version: '0.530'
  iabtcfv2:
    file: lib/iabtcfv2.pm
    version: '0.530'
recommends:
  DateTimeX::TO_JSON: '0'
  HTTP::Tiny: '0'
  JSON: '0'
  JSON::PP: '0'
  JSON::XS: '0'
  Time::Piece: '0'
requires:
  perl: '5.012000'
resources:
  X_security_policy: https://github.com/peczenyj/GDPR-IAB-TCFv2/blob/devel/SECURITY.md
  bugtracker: https://github.com/peczenyj/GDPR-IAB-TCFv2/issues
  homepage: https://github.com/peczenyj/GDPR-IAB-TCFv2
  license: http://dev.perl.org/licenses/
  repository: https://github.com/peczenyj/GDPR-IAB-TCFv2.git
version: '0.530'
x_authority: cpan:PACMAN
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
