#!perl

# Note: This script is a CLI for Riap function /App/ANSIColorUtils/show_assigned_rgb_colors
# and generated automatically using Perinci::CmdLine::Gen version 0.497

our $AUTHORITY = 'cpan:PERLANCAR'; # AUTHORITY
our $DATE = '2021-01-20'; # DATE
our $DIST = 'App-ANSIColorUtils'; # DIST
our $VERSION = '0.009'; # VERSION

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Classic;

my $cmdline = Perinci::CmdLine::Classic->new(
    url => "/App/ANSIColorUtils/show_assigned_rgb_colors",
    program_name => "show-assigned-rgb-colors",
    read_config => 0,
    read_env => 0,
    use_utf8 => 1,
);

$cmdline->run;

# ABSTRACT: Take arguments, pass them through assign_rgb_color(), show the results
# PODNAME: show-assigned-rgb-colors

__END__

=pod

=encoding UTF-8

=head1 NAME

show-assigned-rgb-colors - Take arguments, pass them through assign_rgb_color(), show the results

=head1 VERSION

This document describes version 0.009 of show-assigned-rgb-colors (from Perl distribution App-ANSIColorUtils), released on 2021-01-20.

=head1 SYNOPSIS

Usage:

 % show-assigned-rgb-colors [--dark] [--format-options=s] [--format=name]
     [--json] [--light] [--(no)naked-res] [--tone=s] <strings> ...

=head1 DESCRIPTION

C<assign_rgb_color()> from L<Color::RGB::Util> takes a string, produce SHA1
digest from it, then take 24bit from the digest as the assigned color.

=head1 OPTIONS

C<*> marks required options.

=head2 Main options

=over

=item B<--dark>

Shortcut for --tone=dark.

See C<--tone>.

=item B<--light>

Shortcut for --tone=light.

See C<--tone>.

=item B<--strings-json>=I<s>

See C<--strings>.

=item B<--strings>=I<s@>*

Can be specified multiple times.

=item B<--tone>=I<s>

Valid values:

 ["light","dark"]

=back

=head2 Output options

=over

=item B<--format-options>=I<s>

Pass options to formatter.

=item B<--format>=I<s>

Choose output format, e.g. json, text.

Default value:

 undef

=item B<--json>

Equivalent to --format=json-pretty.

=item B<--naked-res>

When outputing as JSON, strip result envelope.

Default value:

 0

By default, when outputing as JSON, the full enveloped result is returned, e.g.:

    [200,"OK",[1,2,3],{"func.extra"=>4}]

The reason is so you can get the status (1st element), status message (2nd
element) as well as result metadata/extra result (4th element) instead of just
the result (3rd element). However, sometimes you want just the result, e.g. when
you want to pipe the result for more post-processing. In this case you can use
`--naked-res` so you just get:

    [1,2,3]


=back

=head2 Other options

=over

=item B<--help>, B<-h>, B<-?>

Display help message and exit.

=item B<--version>, B<-v>

Display program's version and exit.

=back

=head1 COMPLETION

This script has shell tab completion capability with support for several
shells.

=head2 bash

To activate bash completion for this script, put:

 complete -C show-assigned-rgb-colors show-assigned-rgb-colors

in your bash startup (e.g. F<~/.bashrc>). Your next shell session will then
recognize tab completion for the command. Or, you can also directly execute the
line above in your shell to activate immediately.

It is recommended, however, that you install modules using L<cpanm-shcompgen>
which can activate shell completion for scripts immediately.

=head2 tcsh

To activate tcsh completion for this script, put:

 complete show-assigned-rgb-colors 'p/*/`show-assigned-rgb-colors`/'

in your tcsh startup (e.g. F<~/.tcshrc>). Your next shell session will then
recognize tab completion for the command. Or, you can also directly execute the
line above in your shell to activate immediately.

It is also recommended to install L<shcompgen> (see above).

=head2 other shells

For fish and zsh, install L<shcompgen> as described above.

=head1 HOMEPAGE

Please visit the project's homepage at L<https://metacpan.org/release/App-ANSIColorUtils>.

=head1 SOURCE

Source repository is at L<https://github.com/perlancar/perl-App-ANSIColorUtils>.

=head1 BUGS

Please report any bugs or feature requests on the bugtracker website L<https://github.com/perlancar/perl-App-ANSIColorUtils/issues>

When submitting a bug or request, please include a test-file or a
patch to an existing test-file that illustrates the bug or desired
feature.

=head1 AUTHOR

perlancar <perlancar@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2021, 2020, 2019, 2017 by perlancar@cpan.org.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
