package Google::Cloud::BigQuery::V2::DatasetReference;

use strict;
use warnings;

our $VERSION = '0.05';

use Protobuf::Message;
use Protobuf::DescriptorPool;
use Protobuf::Internal qw(:all);
use MIME::Base64;

BEGIN {
    eval { require Google::Api::FieldBehavior };
    my $descriptor_b64 = <<'EOF';
CjBnb29nbGUvY2xvdWQvYmlncXVlcnkvdjIvZGF0YXNldF9yZWZlcmVuY2UucHJvdG8SGGdv
b2dsZS5jbG91ZC5iaWdxdWVyeS52MhofZ29vZ2xlL2FwaS9maWVsZF9iZWhhdmlvci5wcm90
byJaChBEYXRhc2V0UmVmZXJlbmNlEiIKCmRhdGFzZXRfaWQYASABKAlCA+BBAlIJZGF0YXNl
dElkEiIKCnByb2plY3RfaWQYAiABKAlCA+BBAVIJcHJvamVjdElkQnIKHGNvbS5nb29nbGUu
Y2xvdWQuYmlncXVlcnkudjJCFURhdGFzZXRSZWZlcmVuY2VQcm90b1o7Y2xvdWQuZ29vZ2xl
LmNvbS9nby9iaWdxdWVyeS92Mi9hcGl2Mi9iaWdxdWVyeXBiO2JpZ3F1ZXJ5cGJK+QgKBhIE
DgAhAQq8BAoBDBIDDgASMrEEIENvcHlyaWdodCAyMDI2IEdvb2dsZSBMTEMKCiBMaWNlbnNl
ZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2Ui
KTsKIHlvdSBtYXkgbm90IHVzZSB0aGlzIGZpbGUgZXhjZXB0IGluIGNvbXBsaWFuY2Ugd2l0
aCB0aGUgTGljZW5zZS4KIFlvdSBtYXkgb2J0YWluIGEgY29weSBvZiB0aGUgTGljZW5zZSBh
dAoKICAgICBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAKCiBV
bmxlc3MgcmVxdWlyZWQgYnkgYXBwbGljYWJsZSBsYXcgb3IgYWdyZWVkIHRvIGluIHdyaXRp
bmcsIHNvZnR3YXJlCiBkaXN0cmlidXRlZCB1bmRlciB0aGUgTGljZW5zZSBpcyBkaXN0cmli
dXRlZCBvbiBhbiAiQVMgSVMiIEJBU0lTLAogV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJ
VElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuCiBTZWUgdGhl
IExpY2Vuc2UgZm9yIHRoZSBzcGVjaWZpYyBsYW5ndWFnZSBnb3Zlcm5pbmcgcGVybWlzc2lv
bnMgYW5kCiBsaW1pdGF0aW9ucyB1bmRlciB0aGUgTGljZW5zZS4KCggKAQISAxAAIQoJCgID
ABIDEgApCggKAQgSAxQAUgoJCgIICxIDFABSCggKAQgSAxUANgoJCgIICBIDFQA2CggKAQgS
AxYANQoJCgIIARIDFgA1CicKAgQAEgQZACEBGhsgSWRlbnRpZmllciBmb3IgYSBkYXRhc2V0
LgoKCgoDBAABEgMZCBgKywEKBAQAAgASAx0CQRq9ASBSZXF1aXJlZC4gQSB1bmlxdWUgSUQg
Zm9yIHRoaXMgZGF0YXNldCwgd2l0aG91dCB0aGUgcHJvamVjdCBuYW1lLiBUaGUgSUQKIG11
c3QgY29udGFpbiBvbmx5IGxldHRlcnMgKGEteiwgQS1aKSwgbnVtYmVycyAoMC05KSwgb3Ig
dW5kZXJzY29yZXMgKF8pLgogVGhlIG1heGltdW0gbGVuZ3RoIGlzIDEsMDI0IGNoYXJhY3Rl
cnMuCgoMCgUEAAIABRIDHQIICgwKBQQAAgABEgMdCRMKDAoFBAACAAMSAx0WFwoMCgUEAAIA
CBIDHRhACg8KCAQAAgAInAgAEgMdGT8KRwoEBAACARIDIAJBGjogT3B0aW9uYWwuIFRoZSBJ
RCBvZiB0aGUgcHJvamVjdCBjb250YWluaW5nIHRoaXMgZGF0YXNldC4KCgwKBQQAAgEFEgMg
AggKDAoFBAACAQESAyAJEwoMCgUEAAIBAxIDIBYXCgwKBQQAAgEIEgMgGEAKDwoIBAACAQic
CAASAyAZP2IGcHJvdG8z
EOF
    Protobuf::DescriptorPool->generated_pool->add_serialized_file(MIME::Base64::decode_base64($descriptor_b64));
}

# Message definitions

# === Message: Google::Cloud::BigQuery::V2::DatasetReference::DatasetReference ===
    # Fields for DatasetReference
    # Field: dataset_id Type: 9 ()
    # Field: project_id Type: 9 ()

1;
