package Google::Cloud::BigQuery::V2::SessionInfo;

use strict;
use warnings;

our $VERSION = '0.05';

use Protobuf::Message;
use Protobuf::DescriptorPool;
use Protobuf::Internal qw(:all);
use MIME::Base64;

BEGIN {
    eval { require Google::Api::FieldBehavior };
    my $descriptor_b64 = <<'EOF';
Citnb29nbGUvY2xvdWQvYmlncXVlcnkvdjIvc2Vzc2lvbl9pbmZvLnByb3RvEhhnb29nbGUu
Y2xvdWQuYmlncXVlcnkudjIaH2dvb2dsZS9hcGkvZmllbGRfYmVoYXZpb3IucHJvdG8iMQoL
U2Vzc2lvbkluZm8SIgoKc2Vzc2lvbl9pZBgBIAEoCUID4EEDUglzZXNzaW9uSWRCbwocY29t
Lmdvb2dsZS5jbG91ZC5iaWdxdWVyeS52MkIQU2Vzc2lvbkluZm9Qcm90b1ABWjtjbG91ZC5n
b29nbGUuY29tL2dvL2JpZ3F1ZXJ5L3YyL2FwaXYyL2JpZ3F1ZXJ5cGI7YmlncXVlcnlwYkrz
BgoGEgQOAB0BCrwECgEMEgMOABIysQQgQ29weXJpZ2h0IDIwMjYgR29vZ2xlIExMQwoKIExp
Y2Vuc2VkIHVuZGVyIHRoZSBBcGFjaGUgTGljZW5zZSwgVmVyc2lvbiAyLjAgKHRoZSAiTGlj
ZW5zZSIpOwogeW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5j
ZSB3aXRoIHRoZSBMaWNlbnNlLgogWW91IG1heSBvYnRhaW4gYSBjb3B5IG9mIHRoZSBMaWNl
bnNlIGF0CgogICAgIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNlcy9MSUNFTlNFLTIu
MAoKIFVubGVzcyByZXF1aXJlZCBieSBhcHBsaWNhYmxlIGxhdyBvciBhZ3JlZWQgdG8gaW4g
d3JpdGluZywgc29mdHdhcmUKIGRpc3RyaWJ1dGVkIHVuZGVyIHRoZSBMaWNlbnNlIGlzIGRp
c3RyaWJ1dGVkIG9uIGFuICJBUyBJUyIgQkFTSVMsCiBXSVRIT1VUIFdBUlJBTlRJRVMgT1Ig
Q09ORElUSU9OUyBPRiBBTlkgS0lORCwgZWl0aGVyIGV4cHJlc3Mgb3IgaW1wbGllZC4KIFNl
ZSB0aGUgTGljZW5zZSBmb3IgdGhlIHNwZWNpZmljIGxhbmd1YWdlIGdvdmVybmluZyBwZXJt
aXNzaW9ucyBhbmQKIGxpbWl0YXRpb25zIHVuZGVyIHRoZSBMaWNlbnNlLgoKCAoBAhIDEAAh
CgkKAgMAEgMSACkKCAoBCBIDFABSCgkKAggLEgMUAFIKCAoBCBIDFQAiCgkKAggKEgMVACIK
CAoBCBIDFgAxCgkKAggIEgMWADEKCAoBCBIDFwA1CgkKAggBEgMXADUKOAoCBAASBBoAHQEa
LCBbUHJldmlld10gSW5mb3JtYXRpb24gcmVsYXRlZCB0byBzZXNzaW9ucy4KCgoKAwQAARID
GggTCjIKBAQAAgASAxwCRBolIE91dHB1dCBvbmx5LiBUaGUgaWQgb2YgdGhlIHNlc3Npb24u
CgoMCgUEAAIABRIDHAIICgwKBQQAAgABEgMcCRMKDAoFBAACAAMSAxwWFwoMCgUEAAIACBID
HBhDCg8KCAQAAgAInAgAEgMcGUJiBnByb3RvMw==
EOF
    Protobuf::DescriptorPool->generated_pool->add_serialized_file(MIME::Base64::decode_base64($descriptor_b64));
}

# Message definitions

# === Message: Google::Cloud::BigQuery::V2::SessionInfo::SessionInfo ===
    # Fields for SessionInfo
    # Field: session_id Type: 9 ()

1;
