package Daje::Database::View::Super::vKanbanPriority;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vKanbanPriority - Daje db model
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vKanbanPriority;
#
#       my $table = Daje::Database::View::Super::vKanbanPriority->new(db => $db);
#
#       my $result = $table->load_kanban_priority_pkey($self, $kanban_priority_pkey);
##
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::vKanbanPriority is a View super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-03-28 17:58:34.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-03-28 17:58:34 -->

our $VERSION = '0.01';

has 'fields' => '"kanban_priority_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","color","title"';
has 'primary_key_name' => "kanban_priority_pkey";
has 'table_name' => "v_kanban_priority";


async sub load_kanban_priority_pkey_p($self, $kanban_priority_pkey) {
    return $self->load_kanban_priority_pkey($kanban_priority_pkey);
}

sub load_kanban_priority_pkey($self, $kanban_priority_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $kanban_priority_pkey
    );
}

1;

