---
abstract: 'Chemical Vapor Deposition simulation framework'
author:
  - 'Jovan Trujillo'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Physics-CVD
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  File::Path: '0'
  List::Util: '0'
  POSIX: '0'
  perl: '5.016'
resources:
  repository: https://github.com/jtrujil43/Physics-CVD.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
