=encoding UTF-8

=head1 NAME

Gungho::Manual::Intro.ja - 高性能クローラーフレームワーク

=head1 SYNOPSIS

  use Gungho;
  Gungho->run(\%config);

=head1 DESCRIPTION

=head2 Gunghoとは

一般的にWebクローラーは(1)ページを取得する (2)解析する を永続的に行う
ものですが、この一連の動作の中にrobots.txtの処理やスロットリング等、
複数のクローラーを開発しているとその度に繰り返し実装し直す必要のある部品が
多々あります。

Gunghoはそれらの機能をなるべくフレームワーク側で吸収し、アプリケーション開発者
はクローラーの基本部品の事は考えずにそのアプリケーション独自の仕組みの開発に
専念できるよう開発されたWebクローラーフレームワークです。

0.09xxxバージョンでは基本機能はほぼかたまり、1.00000に向けてインターフェースや
細かいユーザビリティの面での改善を見据えて開発が進んでいます。

=head2 マニュアル

=over 4

=item Basics

Gunghoについて、設計思想、基本的な構成等

=item Tutorial

簡単なクローラーの作成方法等、チュートリアル

=item FAQ

よくある質問等

=item TODO

これから開発が予定されている部品、機能。

=cut